"""Tests for scripts/toc/ — generator, check, cli (mirrors test_codemap.py)."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from toc.generator import _slugify, _display, parse_headers, generate_toc  # noqa: E402
from toc.check import check_toc  # noqa: E402


# A doc with the markers present but EMPTY — generating into it produces drift
# until --write fills the block (the natural "needs regeneration" state).
DOC_TEMPLATE = (
    "# Doc\n\n"
    "<!-- TOC:START -->\n"
    "<!-- TOC:END -->\n\n"
    "## Alpha [CORE]\n\n"
    "### Beta\n\n"
    "## Gamma\n"
)


def _write(tmp_path: Path, body: str) -> Path:
    f = tmp_path / "DOC.md"
    f.write_text(body, encoding="utf-8")
    return f


# ---------------------------------------------------------------------------
# slugify — GitHub-compatible anchors
# ---------------------------------------------------------------------------


def test_slugify_basic():
    assert _slugify("Purpose") == "purpose"


def test_slugify_keeps_tag_in_anchor():
    # GitHub slugs the full header text incl. the [CORE] tag.
    assert _slugify("Purpose [CORE]") == "purpose-core"


def test_slugify_ampersand_double_hyphen():
    # GitHub does not collapse the gap left by a removed '&'.
    assert _slugify("Layer Boundaries & Invariants [CORE]") == "layer-boundaries--invariants-core"


def test_slugify_parens_and_spaces():
    assert _slugify("The methodology engine (feedback loop)") == "the-methodology-engine-feedback-loop"
    assert _slugify("Module-to-layer assignment") == "module-to-layer-assignment"


# ---------------------------------------------------------------------------
# display — clean link text
# ---------------------------------------------------------------------------


def test_display_strips_trailing_tag():
    assert _display("Purpose [CORE]") == "Purpose"


def test_display_keeps_parens_and_plain():
    assert _display("Layer model") == "Layer model"
    assert _display("The methodology engine (feedback loop)") == "The methodology engine (feedback loop)"


# ---------------------------------------------------------------------------
# parse_headers
# ---------------------------------------------------------------------------


def test_parse_headers_levels():
    md = "# Title\n\n## A\n\n### B\n\n## C\n"
    assert parse_headers(md) == [(2, "A"), (3, "B"), (2, "C")]


def test_parse_headers_skips_fenced():
    md = "## Real\n\n```\n## NotAHeader\n```\n\n## Also Real\n"
    assert parse_headers(md) == [(2, "Real"), (2, "Also Real")]


def test_parse_headers_ignores_h1_and_h4():
    md = "# Title\n\n## Two\n\n#### Four\n"
    assert parse_headers(md) == [(2, "Two")]


# ---------------------------------------------------------------------------
# generate_toc — nesting, dedup, idempotence
# ---------------------------------------------------------------------------


def test_generate_toc_nesting(tmp_path):
    f = _write(tmp_path, "# T\n\n## Purpose [CORE]\n\n### Layer model\n\n## Done\n")
    toc = generate_toc(f)
    assert "- [Purpose](#purpose-core)" in toc
    assert "  - [Layer model](#layer-model)" in toc
    assert "- [Done](#done)" in toc
    assert toc.endswith("<!-- generated by toc tool; do not edit by hand -->\n")


def test_generate_toc_dedup_anchor(tmp_path):
    f = _write(tmp_path, "## Foo\n\n## Foo\n")
    toc = generate_toc(f)
    assert "(#foo)" in toc
    assert "(#foo-1)" in toc


def test_generate_toc_idempotent(tmp_path):
    f = _write(tmp_path, "## A\n\n### B\n\n## C\n")
    assert generate_toc(f) == generate_toc(f)


# ---------------------------------------------------------------------------
# check — exit codes (mirror codemap check)
# ---------------------------------------------------------------------------


def test_check_clean_after_write(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    _run_cli("generate", str(f), "--write")
    code, out = check_toc(f)
    assert code == 0
    assert out == ""


def test_check_drift(tmp_path):
    # Markers present but empty while headers exist -> stale.
    f = _write(tmp_path, DOC_TEMPLATE)
    code, out = check_toc(f)
    assert code == 1
    assert "---" in out or "+++" in out


def test_check_missing_file(tmp_path):
    code, out = check_toc(tmp_path / "nope.md")
    assert code == 2
    assert "not found" in out


def test_check_missing_markers(tmp_path):
    f = _write(tmp_path, "# Doc\n\n## A\n")
    code, out = check_toc(f)
    assert code == 3
    assert "TOC" in out


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------

_ENV = {**os.environ, "PYTHONPATH": str(SCRIPTS_DIR)}


def _run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "toc.cli", *args],
        capture_output=True,
        text=True,
        env=_ENV,
    )


def test_cli_generate_stdout(tmp_path):
    f = _write(tmp_path, "# T\n\n## Alpha [CORE]\n\n### Beta\n")
    r = _run_cli("generate", str(f))
    assert r.returncode == 0
    assert "- [Alpha](#alpha-core)" in r.stdout
    assert "  - [Beta](#beta)" in r.stdout


def test_cli_generate_write_replaces_block(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    r = _run_cli("generate", str(f), "--write")
    assert r.returncode == 0
    content = f.read_text(encoding="utf-8")
    assert "<!-- TOC:START -->" in content
    assert "<!-- TOC:END -->" in content
    assert "- [Alpha](#alpha-core)" in content
    assert "  - [Beta](#beta)" in content
    assert "- [Gamma](#gamma)" in content
    assert "<!-- generated by toc tool; do not edit by hand -->" in content


def test_cli_generate_write_idempotent(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    _run_cli("generate", str(f), "--write")
    first = f.read_text(encoding="utf-8")
    _run_cli("generate", str(f), "--write")
    second = f.read_text(encoding="utf-8")
    assert first == second


def test_cli_check_drift(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    r = _run_cli("check", str(f))
    assert r.returncode == 1


def test_cli_help():
    r = _run_cli("--help")
    assert r.returncode == 0
    assert "generate" in r.stdout
    assert "check" in r.stdout
