"""Tests for scripts/codemap/ — ast_walker, text_emit, mermaid_emit, generator, check, cli.

Canonical output is compact text (ADR-51 amendment 2026-07-05); mermaid_emit is
retained for the future visualization surface and keeps its own pinning tests.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FIXTURES = Path(__file__).parent / "fixtures"
SIMPLE_REPO = FIXTURES / "codemap-simple-repo"
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"

sys.path.insert(0, str(SCRIPTS_DIR))

from codemap.ast_walker import analyze_repo  # noqa: E402
from codemap.mermaid_emit import emit_mermaid  # noqa: E402
from codemap.text_emit import emit_text  # noqa: E402
from codemap.generator import generate_codemap  # noqa: E402
from codemap.check import check_codemap  # noqa: E402


# ---------------------------------------------------------------------------
# Step 1 — ast_walker
# ---------------------------------------------------------------------------


def test_ast_walker_simple_repo():
    result = analyze_repo(SIMPLE_REPO)
    assert result["packages"] == ["pkg_a", "pkg_b"]
    assert result["edges"] == [("pkg_a", "pkg_b")]


def test_ast_walker_no_src_dir(tmp_path, capsys):
    result = analyze_repo(tmp_path)
    assert result == {"packages": [], "edges": []}
    captured = capsys.readouterr()
    assert "warning" in captured.err.lower()


def test_ast_walker_skips_relative(tmp_path):
    src = tmp_path / "src"
    pkg_a = src / "pkg_a"
    pkg_b = src / "pkg_b"
    for d in [pkg_a, pkg_b]:
        d.mkdir(parents=True)
        (d / "__init__.py").write_text("")
    (pkg_a / "mod.py").write_text("from . import something\nfrom .sub import x\n")
    result = analyze_repo(tmp_path)
    assert result["edges"] == []


def test_ast_walker_deterministic():
    r1 = analyze_repo(SIMPLE_REPO)
    r2 = analyze_repo(SIMPLE_REPO)
    assert r1 == r2


# ---------------------------------------------------------------------------
# Step 2a — text_emit (canonical output form, ADR-51 amendment 2026-07-05)
# ---------------------------------------------------------------------------


def test_text_emit_no_fence_no_mermaid():
    out = emit_text(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")])
    assert "```" not in out
    assert "mermaid" not in out.lower()
    assert "<!-- generated by codemap tool; do not edit by hand -->" in out


def test_text_emit_module_table_and_dependency_list():
    out = emit_text(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")])
    assert "| module | layer | path | flags |" in out
    assert "| pkg_a | - | src/pkg_a/ | - |" in out
    assert "| pkg_b | - | src/pkg_b/ | - |" in out
    assert "- pkg_a -> pkg_b" in out


def test_text_emit_orphan_flag():
    out = emit_text(["pkg_a", "pkg_b", "pkg_c"], [("pkg_a", "pkg_b")])
    assert "| pkg_c | - | src/pkg_c/ | orphan |" in out


def test_text_emit_cycle_flag():
    out = emit_text(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b"), ("pkg_b", "pkg_a")])
    assert "- pkg_a -> pkg_b [cycle]" in out
    assert "- pkg_b -> pkg_a [cycle]" in out


def test_text_emit_layers_and_source_root():
    layers = {"pkg_a": "core", "pkg_b": "foundation"}
    out = emit_text(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")], layers=layers,
                    source_root="scripts")
    assert "| pkg_a | core | scripts/pkg_a/ | - |" in out
    assert "| pkg_b | foundation | scripts/pkg_b/ | - |" in out
    assert "source root: `scripts/`" in out


def test_text_emit_empty_repo():
    out = emit_text([], [])
    assert "| (none) | - | - | - |" in out
    assert "- (none)" in out


def test_text_emit_deterministic():
    packages = ["pkg_b", "pkg_a"]
    edges = [("pkg_b", "pkg_a"), ("pkg_a", "pkg_b")]
    assert emit_text(packages, edges) == emit_text(packages, edges)


# ---------------------------------------------------------------------------
# Step 2b — mermaid_emit (RETAINED for the visualization surface; not wired
# into the generator — ADR-51 amendment 2026-07-05 Decision 2/3)
# ---------------------------------------------------------------------------


def test_emit_includes_mermaid_fence():
    out = emit_mermaid(["pkg_a"], [])
    assert out.startswith("```mermaid\n")
    assert out.rstrip().endswith("-->")  # ends with do-not-edit comment
    # closing fence present
    assert "\n```\n" in out


def test_mermaid_emit_simple():
    out = emit_mermaid(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")])
    assert out.startswith("```mermaid\n")
    assert "flowchart TD" in out
    assert "pkg_a[pkg_a]" in out
    assert "pkg_b[pkg_b]" in out
    assert "pkg_a --> pkg_b" in out
    assert "classDef foundation" in out
    assert "<!-- generated by codemap tool; do not edit by hand -->" in out


def test_mermaid_emit_orphan_class():
    out = emit_mermaid(["pkg_a", "pkg_b", "pkg_c"], [("pkg_a", "pkg_b")])
    assert "pkg_c[pkg_c]:::orphan" in out


def test_mermaid_emit_cycle_class():
    packages = ["pkg_a", "pkg_b"]
    edges = [("pkg_a", "pkg_b"), ("pkg_b", "pkg_a")]
    out = emit_mermaid(packages, edges)
    assert "linkStyle" in out
    assert "stroke:#e03131" in out


def test_mermaid_emit_layers():
    layers = {"pkg_a": "core", "pkg_b": "foundation"}
    out = emit_mermaid(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")], layers=layers)
    assert "pkg_a[pkg_a]:::core" in out
    assert "pkg_b[pkg_b]:::foundation" in out


def test_mermaid_emit_click_directives():
    out = emit_mermaid(["pkg_a", "pkg_b"], [], click_directives=True)
    assert 'click pkg_a href "src/pkg_a/"' in out
    assert 'click pkg_b href "src/pkg_b/"' in out


def test_mermaid_emit_deterministic():
    packages = ["pkg_b", "pkg_a"]
    edges = [("pkg_b", "pkg_a"), ("pkg_a", "pkg_b")]
    r1 = emit_mermaid(packages, edges)
    r2 = emit_mermaid(packages, edges)
    assert r1 == r2


# ---------------------------------------------------------------------------
# Step 3 — generator
# ---------------------------------------------------------------------------

WITH_TACH = FIXTURES / "codemap-with-tach"
WITH_ORPHAN = FIXTURES / "codemap-with-orphan"
WITH_CYCLE = FIXTURES / "codemap-with-cycle"


def test_generator_full_flow():
    text, warnings = generate_codemap(SIMPLE_REPO)
    assert "| module | layer | path | flags |" in text
    assert "| pkg_a |" in text
    assert "| pkg_b |" in text
    assert "- pkg_a -> pkg_b" in text
    assert "mermaid" not in text.lower()
    assert warnings == []


def test_generator_with_tach():
    text, warnings = generate_codemap(WITH_TACH)
    assert "| pkg_a | core |" in text
    assert "| pkg_b | foundation |" in text


def test_generator_orphan_warning():
    text, warnings = generate_codemap(WITH_ORPHAN)
    assert any("orphan" in w for w in warnings)
    assert "| pkg_orphan | - | src/pkg_orphan/ | orphan |" in text


def test_generator_cycle_warning():
    text, warnings = generate_codemap(WITH_CYCLE)
    assert any("circular" in w for w in warnings)
    assert "[cycle]" in text


def test_generator_no_tach():
    text, warnings = generate_codemap(SIMPLE_REPO)
    # no tach.toml in simple-repo → no layer assignments, no tach warning
    assert not any("tach" in w.lower() for w in warnings)
    assert "| pkg_a | - |" in text


# ---------------------------------------------------------------------------
# Step 4 — check
# ---------------------------------------------------------------------------

ARCH_CLEAN = FIXTURES / "codemap-arch-clean"
ARCH_DRIFT = FIXTURES / "codemap-arch-drift"
ARCH_NOMARKERS = FIXTURES / "codemap-arch-nomarkers"


def test_check_clean():
    code, out = check_codemap(ARCH_CLEAN)
    assert code == 0
    assert out == ""


def test_check_drift():
    code, out = check_codemap(ARCH_DRIFT)
    assert code == 1
    assert "---" in out or "+++" in out  # unified diff present


def test_check_no_architecture_md(tmp_path):
    code, out = check_codemap(tmp_path)
    assert code == 2
    assert "ARCHITECTURE.md" in out


def test_check_no_markers():
    code, out = check_codemap(ARCH_NOMARKERS)
    assert code == 3
    assert "CODEMAP" in out


def test_check_arch_file_override(tmp_path):
    # Target a doc at a non-default path; the default ARCHITECTURE.md is absent.
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    alt = tmp_path / "repo" / "ARCHITECTURE-ALT.md"
    (tmp_path / "repo" / "ARCHITECTURE.md").rename(alt)

    # Default derivation now fails (no ARCHITECTURE.md at the repo root)...
    code_default, _ = check_codemap(tmp_path / "repo")
    assert code_default == 2

    # ...but the explicit arch_file resolves and is clean.
    code_alt, out_alt = check_codemap(tmp_path / "repo", arch_file=alt)
    assert code_alt == 0
    assert out_alt == ""


# ---------------------------------------------------------------------------
# Step 5 — CLI integration tests
# ---------------------------------------------------------------------------

CLI_MODULE = ["python", "-m", "codemap.cli"]
_ENV = {**os.environ, "PYTHONPATH": str(SCRIPTS_DIR)}


def _run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "codemap.cli", *args],
        capture_output=True,
        text=True,
        env=_ENV,
    )


def test_cli_generate_stdout():
    r = _run_cli("generate", str(SIMPLE_REPO))
    assert r.returncode == 0
    assert "| module | layer | path | flags |" in r.stdout
    assert "pkg_a" in r.stdout


def test_cli_generate_write(tmp_path):
    # Copy arch-clean fixture to a tmp location so --write can mutate it
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    r = _run_cli("generate", str(tmp_path / "repo"), "--write")
    assert r.returncode == 0
    content = (tmp_path / "repo" / "ARCHITECTURE.md").read_text()
    assert "<!-- CODEMAP:START -->" in content
    assert "<!-- CODEMAP:END -->" in content
    assert "| module | layer | path | flags |" in content
    assert "<!-- generated by codemap tool; do not edit by hand -->" in content


def test_cli_generate_write_produces_text_block(tmp_path):
    # The block between the markers is compact text — no fence, no Mermaid
    # (ADR-51 amendment 2026-07-05).
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    _run_cli("generate", str(tmp_path / "repo"), "--write")
    content = (tmp_path / "repo" / "ARCHITECTURE.md").read_text()
    start = content.index("<!-- CODEMAP:START -->") + len("<!-- CODEMAP:START -->")
    end = content.index("<!-- CODEMAP:END -->")
    block = content[start:end]
    assert "```" not in block
    assert "mermaid" not in block.lower()
    assert "| module | layer | path | flags |" in block
    assert "Dependencies (`from -> to`" in block
    assert "<!-- generated by codemap tool; do not edit by hand -->" in block


def test_cli_check_clean():
    r = _run_cli("check", str(ARCH_CLEAN))
    assert r.returncode == 0


def test_cli_check_drift():
    r = _run_cli("check", str(ARCH_DRIFT))
    assert r.returncode == 1


def test_cli_help():
    r = _run_cli("--help")
    assert r.returncode == 0
    assert "generate" in r.stdout
    assert "check" in r.stdout


def test_cli_arch_file_check_and_generate(tmp_path):
    # --arch-file targets a doc at a non-default path for both check and generate.
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    repo = tmp_path / "repo"
    alt = repo / "ARCHITECTURE-ALT.md"
    (repo / "ARCHITECTURE.md").rename(alt)

    # check against the alt doc is clean (default would be exit 2 — missing)
    assert _run_cli("check", str(repo), "--arch-file", str(alt)).returncode == 0
    assert _run_cli("check", str(repo)).returncode == 2

    # generate --write targets the alt doc
    r = _run_cli("generate", str(repo), "--arch-file", str(alt), "--write")
    assert r.returncode == 0
    assert "<!-- CODEMAP:START -->" in alt.read_text()
    assert not (repo / "ARCHITECTURE.md").exists()
