"""Tests for scripts/toc/ — generator, check, cli (mirrors test_codemap.py)."""
from __future__ import annotations

import os
from collections import Counter

import pytest
import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

from toc.generator import _slugify, _display, _HEADER_RE, parse_headers, generate_toc  # noqa: E402
from toc.check import check_toc  # noqa: E402


# A doc with the markers present but EMPTY — generating into it produces drift
# until --write fills the block (the natural "needs regeneration" state).
DOC_TEMPLATE = (
    "# Doc\n\n"
    "<!-- TOC:START -->\n"
    "<!-- TOC:END -->\n\n"
    "## Alpha [CORE]\n\n"
    "### Beta\n\n"
    "## Gamma\n"
)


def _write(tmp_path: Path, body: str) -> Path:
    f = tmp_path / "DOC.md"
    f.write_text(body, encoding="utf-8")
    return f


# ---------------------------------------------------------------------------
# slugify — GitHub-compatible anchors
# ---------------------------------------------------------------------------


def test_slugify_basic():
    assert _slugify("Purpose") == "purpose"


def test_slugify_keeps_tag_in_anchor():
    # GitHub slugs the full header text incl. the [CORE] tag.
    assert _slugify("Purpose [CORE]") == "purpose-core"


def test_slugify_ampersand_double_hyphen():
    # GitHub does not collapse the gap left by a removed '&'.
    assert _slugify("Layer Boundaries & Invariants [CORE]") == "layer-boundaries--invariants-core"


def test_slugify_parens_and_spaces():
    assert _slugify("The methodology engine (feedback loop)") == "the-methodology-engine-feedback-loop"
    assert _slugify("Module-to-layer assignment") == "module-to-layer-assignment"


# ---------------------------------------------------------------------------
# display — clean link text
# ---------------------------------------------------------------------------


def test_display_strips_trailing_tag():
    assert _display("Purpose [CORE]") == "Purpose"


def test_display_keeps_parens_and_plain():
    assert _display("Layer model") == "Layer model"
    assert _display("The methodology engine (feedback loop)") == "The methodology engine (feedback loop)"


# ---------------------------------------------------------------------------
# parse_headers
# ---------------------------------------------------------------------------


def test_parse_headers_levels():
    md = "# Title\n\n## A\n\n### B\n\n## C\n"
    assert parse_headers(md) == [(2, "A"), (3, "B"), (2, "C")]


def test_parse_headers_skips_fenced():
    md = "## Real\n\n```\n## NotAHeader\n```\n\n## Also Real\n"
    assert parse_headers(md) == [(2, "Real"), (2, "Also Real")]


def test_parse_headers_ignores_h1_and_h4():
    md = "# Title\n\n## Two\n\n#### Four\n"
    assert parse_headers(md) == [(2, "Two")]


# ---------------------------------------------------------------------------
# generate_toc — nesting, dedup, idempotence
# ---------------------------------------------------------------------------


def test_generate_toc_nesting(tmp_path):
    f = _write(tmp_path, "# T\n\n## Purpose [CORE]\n\n### Layer model\n\n## Done\n")
    toc = generate_toc(f)
    assert "- [Purpose](#purpose-core)" in toc
    assert "  - [Layer model](#layer-model)" in toc
    assert "- [Done](#done)" in toc
    assert toc.endswith("<!-- generated by toc tool; do not edit by hand -->\n")


def test_generate_toc_dedup_anchor(tmp_path):
    f = _write(tmp_path, "## Foo\n\n## Foo\n")
    toc = generate_toc(f)
    assert "(#foo)" in toc
    assert "(#foo-1)" in toc


def test_generate_toc_idempotent(tmp_path):
    f = _write(tmp_path, "## A\n\n### B\n\n## C\n")
    assert generate_toc(f) == generate_toc(f)


# ---------------------------------------------------------------------------
# check — exit codes (mirror codemap check)
# ---------------------------------------------------------------------------


def test_check_clean_after_write(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    _run_cli("generate", str(f), "--write")
    code, out = check_toc(f)
    assert code == 0
    assert out == ""


def test_check_drift(tmp_path):
    # Markers present but empty while headers exist -> stale.
    f = _write(tmp_path, DOC_TEMPLATE)
    code, out = check_toc(f)
    assert code == 1
    assert "---" in out or "+++" in out


def test_check_missing_file(tmp_path):
    code, out = check_toc(tmp_path / "nope.md")
    assert code == 2
    assert "not found" in out


def test_check_missing_markers(tmp_path):
    f = _write(tmp_path, "# Doc\n\n## A\n")
    code, out = check_toc(f)
    assert code == 3
    assert "TOC" in out


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------

_ENV = {**os.environ, "PYTHONPATH": str(SCRIPTS_DIR)}


def _run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "toc.cli", *args],
        capture_output=True,
        text=True,
        env=_ENV,
    )


def test_cli_generate_stdout(tmp_path):
    f = _write(tmp_path, "# T\n\n## Alpha [CORE]\n\n### Beta\n")
    r = _run_cli("generate", str(f))
    assert r.returncode == 0
    assert "- [Alpha](#alpha-core)" in r.stdout
    assert "  - [Beta](#beta)" in r.stdout


def test_cli_generate_write_replaces_block(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    r = _run_cli("generate", str(f), "--write")
    assert r.returncode == 0
    content = f.read_text(encoding="utf-8")
    assert "<!-- TOC:START -->" in content
    assert "<!-- TOC:END -->" in content
    assert "- [Alpha](#alpha-core)" in content
    assert "  - [Beta](#beta)" in content
    assert "- [Gamma](#gamma)" in content
    assert "<!-- generated by toc tool; do not edit by hand -->" in content


def test_cli_generate_write_idempotent(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    _run_cli("generate", str(f), "--write")
    first = f.read_text(encoding="utf-8")
    _run_cli("generate", str(f), "--write")
    second = f.read_text(encoding="utf-8")
    assert first == second


def test_cli_check_drift(tmp_path):
    f = _write(tmp_path, DOC_TEMPLATE)
    r = _run_cli("check", str(f))
    assert r.returncode == 1


def test_cli_help():
    r = _run_cli("--help")
    assert r.returncode == 0
    assert "generate" in r.stdout
    assert "check" in r.stdout


# ---------------------------------------------------------------------------
# Fence handling — the `startswith("```")` toggle diverges from CommonMark BOTH ways.
# This generator feeds a DEPLOYED freshness hook, so a wrong header set means a wrong
# TOC that then fails the gate (or passes with content silently missing).
# ---------------------------------------------------------------------------

def test_parse_headers_does_not_swallow_the_document_after_an_odd_fence_count():
    """FALSE NEGATIVE — the defect that actually bites the corpus.

    A closing fence may not carry an info string, so ```` ```markdown ```` after an open
    fence is CONTENT, not a close. The naive toggle counts it anyway, ends up stuck
    "inside a fence", and silently drops every heading in the rest of the document.
    Measured on the live corpus this is the dominant cause: 9 of 1577 files diverge, e.g.
    docs/handoffs/archive/2026-05-09-ai-council-audit-sync/stage1-question.md, where the
    toggle finds 5 headings against CommonMark's 13.
    """
    md = (
        "## Before\n\n"
        "```\n"
        "code\n"
        "```markdown\n"      # NOT a close (info string) -> still inside the fence
        "still code\n"
        "```\n"              # the real close
        "\n## After\n"
    )
    assert parse_headers(md) == [(2, "Before"), (2, "After")]


def test_parse_headers_skips_tilde_fenced_content():
    """FALSE POSITIVE — the mirror image. `~~~` is a legal CommonMark fence and the
    toggle only knows backticks, so sample markdown inside a tilde fence is harvested as
    real headings and lands in the generated TOC."""
    md = "## Real\n\n~~~\n## NotAHeader\n~~~\n\n## Also Real\n"
    assert parse_headers(md) == [(2, "Real"), (2, "Also Real")]


def test_parse_headers_respects_a_longer_fence_wrapping_a_shorter_one():
    """A 4-backtick fence legally contains 3-backtick lines; the toggle closes early."""
    md = "## Real\n\n````\n```\n## NotAHeader\n```\n````\n\n## Also Real\n"
    assert parse_headers(md) == [(2, "Real"), (2, "Also Real")]


# ---------------------------------------------------------------------------
# Corpus safety property: the fence fix RECOVERS headers, it never drops them.
# ---------------------------------------------------------------------------

_SKIP_PARTS = {".venv", ".git", "node_modules", "__pycache__", ".pytest_cache"}


def _legacy_parse_headers(content: str) -> list[tuple[int, str]]:
    """The pre-fix `startswith("```")` toggle, kept ONLY as a reference implementation for
    the corpus comparison below. It is the thing being replaced, not a second copy in use."""
    headers: list[tuple[int, str]] = []
    in_fence = False
    for line in content.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = _HEADER_RE.match(line)
        if m:
            headers.append((len(m.group(1)), m.group(2)))
    return headers


@pytest.mark.live_repo
def test_corpus_fence_fix_only_recovers_headers_and_never_drops_one() -> None:
    """The safety property, over every markdown file in the repo: switching the fence
    decision to CommonMark may only ADD headers the toggle wrongly swallowed — it must never
    REMOVE one the toggle correctly found.

    That direction is what matters for a DEPLOYED freshness hook: a recovered header makes a
    TOC more complete, while a lost header would silently shrink a generated TOC and the gate
    would happily accept the smaller one as fresh.

    Measured when written: 3 of 1577 files changed, all strictly gaining (+6, +8, +8), with
    ZERO headers lost anywhere. Recovery itself is pinned deterministically by the three
    fence-shape unit tests above rather than by a live-corpus count, so ordinary edits to
    those documents cannot turn this into a spurious RED.
    """
    root = Path(__file__).resolve().parent.parent
    files = [p for p in sorted(root.rglob("*.md")) if not _SKIP_PARTS.intersection(p.parts)]
    assert len(files) > 100, f"corpus implausibly small ({len(files)}) — glob is wrong"

    compared = 0
    for p in files:
        content = p.read_text(encoding="utf-8", errors="replace")
        legacy, fixed = _legacy_parse_headers(content), parse_headers(content)
        compared += len(legacy)
        # MULTISET, not membership (terra HIGH, 2026-08-03). `h not in fixed` compares
        # presence, so legacy [(2,"Foo"), (2,"Foo")] vs fixed [(2,"Foo")] passed while a real
        # TOC row was lost — and duplicate occurrences are exactly what drives the `#foo-1`
        # anchor numbering, so a dropped duplicate silently renumbers every later anchor.
        lost = Counter(legacy) - Counter(fixed)
        assert not lost, f"{p}: the fence fix DROPPED header occurrence(s) {list(lost)[:3]}"
    assert compared > 1000, f"only {compared} headers compared — proof too thin"


def test_headers_inside_an_html_block_are_still_returned():
    """The compatibility contract the token-gate revision broke (terra HIGH, 2026-08-03).

    A `##` line inside an HTML block or an unterminated HTML comment is NOT a CommonMark
    heading, so gating on `heading_open` tokens DROPPED these — shrinking the TOC and shifting
    anchor numbering. The parser locates CODE RANGES instead, so raw-line behaviour outside
    fences is preserved and this arc can only recover headers, never lose them.
    """
    md = "## Real\n\n<div>\n## InsideHtmlBlock\n</div>\n\n<!-- unterminated\n## InsideComment\n"
    assert parse_headers(md) == [
        (2, "Real"), (2, "InsideHtmlBlock"), (2, "InsideComment")]


def test_duplicate_headers_keep_every_occurrence():
    """Occurrence count is load-bearing: `generate_toc` numbers repeat anchors (#foo-1), so
    losing one duplicate renumbers every later anchor in the document."""
    md = "## Foo\n\n```\n## Fenced\n```\n\n## Foo\n\n## Foo\n"
    assert parse_headers(md) == [(2, "Foo"), (2, "Foo"), (2, "Foo")]
