"""Tests for scripts/file_purpose_graph.py — FPG-1, the file-purpose graph's first slice.

RED-FIRST, and the refusal came first. The contract's own words: *"Build the refusal first and
test it with a planted unknown; that is the RED-first witness for this lane."* So the first
test written was `test_why_refuses_a_planted_unknown_file`, and it was RED — with the whole
module absent — before a line of `file_purpose_graph.py` existed. A green test that never went
red proves the assertion runs, not that it discriminates.

THE FIXTURE REPO IS SYNTHETIC AND COMPLETE. Every structural test builds a miniature repo under
`tmp_path` carrying all five inputs in their REAL shapes (a `declaration_docs:` registry with a
live `<!-- rule: -->`/`# rule:` pair, a generated audits index, an audit citing `[#42]`, two
`tasks/` rows with a `depends-on` edge, a deploy manifest with a carrier and a component). That
is deliberate: pinning live counts would encode today's moment and break on the next commit,
which is the standing practice in `tests/test_fleet_analytics.py`. The live repo is exercised
too, but only for SHAPE and INVARIANTS — plus the three `why` transcripts the lane's ex-ante
names, which assert answer STRUCTURE rather than today's neighbour lists.

WHY `_load()` AND NOT A BARE IMPORT. `pythonpath = [".", "scripts", "deploy"]` would make a
bare `import file_purpose_graph` work, but loading by path keeps this module's name stable and
independent of collection order — the same reason `tests/test_fleet_analytics.py` loads by
spec.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
_P = _REPO / "scripts" / "file_purpose_graph.py"
_MODNAME = "scripts.file_purpose_graph"


def _load():
    spec = importlib.util.spec_from_file_location(_MODNAME, _P)
    module = importlib.util.module_from_spec(spec)
    sys.modules[_MODNAME] = module
    spec.loader.exec_module(module)
    return module


fpg = _load()


# --------------------------------------------------------------------------- fixture repo


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@pytest.fixture
def mini(tmp_path: Path) -> Path:
    """A miniature repo carrying all five inputs in their real shapes."""
    root = tmp_path / "repo"

    # --- input 1: the doc->code edge registry, with one genuinely resolvable rule ----------
    _write(root / "ecosystem" / "doc-code-edge.yaml", (
        "declaration_docs:\n"
        "  - protocols/PLAYBOOK.md\n"
        "coverage_scope:\n"
        "  - demo-rule\n"
        "multi_site: {}\n"
        "exempt: []\n"
    ))
    _write(root / "protocols" / "PLAYBOOK.md",
           "# PLAYBOOK\n\nThe universal-protocols reference.\n\n<!-- rule: demo-rule -->\n")
    _write(root / "scripts" / "enforce_demo.py",
           '"""enforce_demo.py — the organ that enforces demo-rule."""\n# rule: demo-rule\n')

    # --- input 2: the generated audits index ----------------------------------------------
    _write(root / "docs" / "audits" / "README.md", (
        "# Audits index — generated navigation map of `docs/audits/`\n\n"
        "<!-- generated by gen_audit_index.py; do not edit by hand -->\n\n"
        "## 2026-08\n\n"
        "- [2026-08-01](2026-08-01-technical-demo.md) — A demo audit\n"
    ))

    # --- input 3: an audit that declares its consumer, and a row that consumes it ---------
    _write(root / "docs" / "audits" / "2026-08-01-technical-demo.md",
           "# A demo audit\n\nThis artifact is owned by [#42].\n")

    # --- input 4: tasks/, the SOURCE OF TRUTH, with a depends-on edge ----------------------
    _write(root / "tasks" / "42-demo-row.md", (
        '---\nid: "[#42]"\ntitle: "The demo row"\nstatus: open\ngenerates: BACKLOG.md\n---\n\n'
        "- [#42] [P2][M] **The demo row** — cites docs/audits/2026-08-01-technical-demo.md"
        " · depends-on: #43 · refs ADR-99\n"
    ))
    _write(root / "tasks" / "43-upstream-row.md", (
        '---\nid: "[#43]"\ntitle: "The upstream row"\nstatus: open\n---\n\n'
        "- [#43] [P3][S] **The upstream row** — nothing depends on nothing\n"
    ))
    _write(root / "BACKLOG.md", "# BACKLOG\n\n- [#42] The demo row\n")

    # --- input 5: the deploy manifest ------------------------------------------------------
    _write(root / "deploy" / "manifest-v9.9.9.yaml", (
        'methodology_version: "9.9.9"\n'
        "carriers:\n"
        "  - id: demo-carrier\n"
        "    order: 1\n"
        "    adr: [ADR-99]\n"
        "    target:\n"
        "      source_path: protocols/PLAYBOOK.md\n"
        "components:\n"
        "  - id: demo-component\n"
        "    carrier: demo-carrier\n"
        "    status: active\n"
        "    artifacts:\n"
        "      - path: protocols/PLAYBOOK.md\n"
        "        source: protocols/PLAYBOOK.md\n"
    ))
    return root


# --------------------------------------------------------------------------- THE REFUSAL
# Written first, RED first. Everything else in this file exists to keep it honest.


def test_why_refuses_a_planted_unknown_file(mini: Path):
    """A file nothing explains is a DEFECT, not a mystery — so `why` FAILs on it."""
    planted = _write(mini / "scripts" / "nothing_explains_me.py", "x = 1\n")
    graph = fpg.build(mini)
    with pytest.raises(fpg.UnknownFile) as excinfo:
        fpg.why(graph, planted.relative_to(mini).as_posix())
    assert excinfo.value.exists is True
    assert "nothing_explains_me.py" in str(excinfo.value)


def test_why_refuses_a_path_that_does_not_exist(mini: Path):
    """The other refusal flavour, distinguished rather than collapsed into the first."""
    graph = fpg.build(mini)
    with pytest.raises(fpg.UnknownFile) as excinfo:
        fpg.why(graph, "scripts/no_such_file_at_all.py")
    assert excinfo.value.exists is False


def test_cli_exits_nonzero_on_a_planted_unknown(mini: Path):
    """The refusal survives the CLI boundary — an exit code, not just an exception."""
    _write(mini / "scripts" / "nothing_explains_me.py", "x = 1\n")
    proc = subprocess.run(
        [sys.executable, str(_P), "why", "scripts/nothing_explains_me.py",
         "--repo-root", str(mini)],
        capture_output=True, text=True,
    )
    assert proc.returncode == 1, proc.stdout + proc.stderr
    assert "nothing explains" in (proc.stdout + proc.stderr).lower()


def test_cli_exits_zero_on_a_governed_file(mini: Path):
    proc = subprocess.run(
        [sys.executable, str(_P), "why", "protocols/PLAYBOOK.md", "--repo-root", str(mini)],
        capture_output=True, text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "purpose" in proc.stdout.lower()
    assert "consumers" in proc.stdout.lower()
    assert "edges" in proc.stdout.lower()


def test_render_truncates_but_never_truncates_the_count(mini: Path):
    """A 787-edge answer is a scroll, not an answer — so rows truncate. The COUNT does not:
    it is the evidence, and a truncated count would be a lie rather than a summary."""
    graph = fpg.build(mini)
    answer = fpg.why(graph, "docs/audits/README.md")
    answer.edges = answer.edges * 30  # 30 rows from one real edge — shape, not a live count
    text = fpg.render(answer, limit=5)
    assert f"edges ({len(answer.edges)})" in text
    assert "25 more not shown" in text
    assert "25 more not shown" not in fpg.render(answer, limit=0)


# --------------------------------------------------------------------------- the five inputs
# One test per input, each asserting the EDGE TYPE that input contributes.


def test_input1_doc_code_edge_contributes_declares_and_enforces(mini: Path):
    graph = fpg.build(mini)
    answer = fpg.why(graph, "scripts/enforce_demo.py")
    kinds = {edge.kind for edge, _ in answer.edges}
    assert fpg.EDGE_ENFORCES in kinds
    targets = {node.key for _, node in answer.edges}
    assert "rule:demo-rule" in targets

    rule_answer = fpg.why(graph, "protocols/PLAYBOOK.md")
    consumer_kinds = {edge.kind for edge, _ in rule_answer.consumers}
    assert fpg.EDGE_DECLARED_IN in consumer_kinds


def test_input2_audits_index_contributes_an_indexes_edge(mini: Path):
    graph = fpg.build(mini)
    answer = fpg.why(graph, "docs/audits/2026-08-01-technical-demo.md")
    consumers = {(edge.kind, node.key) for edge, node in answer.consumers}
    assert (fpg.EDGE_INDEXES, "file:docs/audits/README.md") in consumers


def test_input3_consumer_at_landing_contributes_both_directions(mini: Path):
    graph = fpg.build(mini)
    answer = fpg.why(graph, "docs/audits/2026-08-01-technical-demo.md")
    # declaration half: the artifact names its governance consumer
    assert (fpg.EDGE_CITES, "task:42") in {(e.kind, n.key) for e, n in answer.edges}
    # consumption half: a governance surface names the artifact back
    assert (fpg.EDGE_CONSUMED_BY, "task:42") in {(e.kind, n.key) for e, n in answer.consumers}


def test_input4_tasks_depends_on_is_read_from_tasks_not_backlog(mini: Path):
    graph = fpg.build(mini)
    answer = fpg.why(graph, "tasks/42-demo-row.md")
    assert (fpg.EDGE_DEPENDS_ON, "task:43") in {(e.kind, n.key) for e, n in answer.edges}


def test_input5_manifest_contributes_carrier_and_component_edges(mini: Path):
    graph = fpg.build(mini)
    answer = fpg.why(graph, "protocols/PLAYBOOK.md")
    consumers = {(e.kind, n.key) for e, n in answer.consumers}
    assert (fpg.EDGE_SHIPS, "component:demo-component") in consumers
    assert (fpg.EDGE_CARRIER_SOURCE, "carrier:demo-carrier") in consumers


def test_generated_surface_consumes_its_source_rows(mini: Path):
    """`generates: BACKLOG.md` inverts: the generated view CONSUMES the row it derives from."""
    graph = fpg.build(mini)
    answer = fpg.why(graph, "BACKLOG.md")
    assert (fpg.EDGE_GENERATED_FROM, "task:42") in {(e.kind, n.key) for e, n in answer.edges}


# --------------------------------------------------------------------------- direction invariant


def test_every_edge_is_consumer_to_consumed(mini: Path):
    """The single stated direction convention, asserted rather than described.

    Every edge kind the builder emits is registered in `EDGE_KINDS` with its rendering label.
    An unregistered kind would render as a bare string in the CLI and silently break the
    convention this module's whole readability rests on.
    """
    graph = fpg.build(mini)
    edges = graph.all_edges()
    assert edges, "vacuous: the fixture graph carries no edge to check"
    for edge in edges:
        assert edge.kind in fpg.EDGE_KINDS, f"unregistered edge kind: {edge.kind}"


def test_multi_target_depends_on_reads_every_id_in_the_clause(tmp_path: Path):
    """The `_parse_deps` trap, asserted the other way round.

    `validate_backlog._parse_deps` uses `search()`, so it reads only the FIRST `depends-on`
    clause. This module uses `finditer()` and therefore sees a SECOND clause that helper does
    not. The divergence is deliberate and measured; this test pins it so it cannot regress
    into an accidental match.
    """
    root = tmp_path / "repo"
    _write(root / "tasks" / "1-a.md", (
        '---\nid: "[#1]"\ntitle: "a"\nstatus: open\n---\n\n'
        "- [#1] [P2][M] **a** · depends-on: #2, #3 · refs x · depends-on: #4\n"
    ))
    for i in (2, 3, 4):
        _write(root / "tasks" / f"{i}-x.md",
               f'---\nid: "[#{i}]"\ntitle: "x"\nstatus: open\n---\n\n- [#{i}] [P3][S] **x**\n')
    graph = fpg.build(root)
    answer = fpg.why(graph, "tasks/1-a.md")
    deps = {n.key for e, n in answer.edges if e.kind == fpg.EDGE_DEPENDS_ON}
    assert deps == {"task:2", "task:3", "task:4"}


def test_frontmatter_depends_on_is_read_too(tmp_path: Path):
    """`tasks/112-*.md` carries its dep in the FRONTMATTER as well as the row."""
    root = tmp_path / "repo"
    _write(root / "tasks" / "1-a.md",
           '---\nid: "[#1]"\ntitle: "a"\nstatus: open\ndepends-on: "#2"\n---\n\n'
           "- [#1] [P2][M] **a** — no clause in the row at all\n")
    _write(root / "tasks" / "2-b.md",
           '---\nid: "[#2]"\ntitle: "b"\nstatus: open\n---\n\n- [#2] [P3][S] **b**\n')
    graph = fpg.build(root)
    answer = fpg.why(graph, "tasks/1-a.md")
    assert (fpg.EDGE_DEPENDS_ON, "task:2") in {(e.kind, n.key) for e, n in answer.edges}


# --------------------------------------------------------------------------- purpose


def test_purpose_comes_from_the_module_docstring_for_python(mini: Path):
    graph = fpg.build(mini)
    assert "enforces demo-rule" in fpg.why(graph, "scripts/enforce_demo.py").purpose


def test_purpose_comes_from_the_h1_for_markdown(mini: Path):
    graph = fpg.build(mini)
    assert fpg.why(graph, "protocols/PLAYBOOK.md").purpose.startswith("PLAYBOOK")


def test_purpose_comes_from_the_frontmatter_title_for_a_task(mini: Path):
    graph = fpg.build(mini)
    assert fpg.why(graph, "tasks/42-demo-row.md").purpose == "The demo row"


def test_purpose_is_stated_as_absent_rather_than_invented(tmp_path: Path):
    """A governed file with no derivable purpose says so. It does NOT fail — the refusal is
    reserved for a file nothing EXPLAINS, which is a different fact from a file that states
    no purpose of its own."""
    root = tmp_path / "repo"
    _write(root / "tasks" / "1-a.md",
           '---\nid: "[#1]"\nstatus: open\n---\n\n- [#1] [P2][M] a\n')
    graph = fpg.build(root)
    assert fpg.why(graph, "tasks/1-a.md").purpose == fpg.NO_STATED_PURPOSE


# --------------------------------------------------------------------------- graph depth


def test_transitive_consumers_reach_past_depth_one(mini: Path):
    """The reason this is a graph and not three adjacency lists.

    `scripts/enforce_demo.py --enforces-> rule:demo-rule --declared-in-> PLAYBOOK.md`, so the
    enforcing organ is a TRANSITIVE consumer of the declaration doc, two hops out.
    """
    graph = fpg.build(mini)
    reachable = graph.transitive_consumers("file:protocols/PLAYBOOK.md")
    assert "file:scripts/enforce_demo.py" in reachable
    assert "file:protocols/PLAYBOOK.md" not in reachable  # never itself


def test_graph_is_backed_by_rustworkx(mini: Path):
    """Library-first, asserted. R-A: *if a consumer is ever named, the library is rustworkx*."""
    import rustworkx

    graph = fpg.build(mini)
    assert isinstance(graph.graph, rustworkx.PyDiGraph)


# --------------------------------------------------------------------------- the live repo
# SHAPE and INVARIANTS only. No live count is pinned — that would encode today's moment.


@pytest.mark.live_repo
def test_live_repo_builds_and_carries_all_five_inputs():
    graph = fpg.build(_REPO)
    # Guard the guard: an empty INPUTS would make the set-equality below pass vacuously, and
    # it DID during this lane's RED phase against the stub. Assert the roster is non-empty
    # before comparing against it.
    assert len(fpg.INPUTS) == 5, fpg.INPUTS
    contributed = {edge.source for edge in graph.all_edges()}
    assert contributed == set(fpg.INPUTS), (
        f"missing input contributions: {set(fpg.INPUTS) - contributed}")
    assert graph.graph.num_nodes() > 0 and graph.graph.num_edges() > 0


@pytest.mark.live_repo
@pytest.mark.parametrize("path", [
    "docs/audits/README.md",        # a generated surface
    "protocols/PLAYBOOK.md",        # a hand-authored canonical doc
    "scripts/block_ff_push.py",     # a script
])
def test_live_repo_why_answers_the_three_ex_ante_files(path):
    """The lane's ex-ante, as a test: three governed files of genuinely different kinds."""
    graph = fpg.build(_REPO)
    answer = fpg.why(graph, path)
    assert answer.purpose and answer.purpose != fpg.NO_STATED_PURPOSE
    assert answer.consumers or answer.edges, f"{path} is a node with no incident edge"


@pytest.mark.live_repo
def test_live_repo_refuses_a_path_no_input_explains():
    """The refusal, proven against the LIVE graph rather than only the fixture."""
    graph = fpg.build(_REPO)
    with pytest.raises(fpg.UnknownFile):
        fpg.why(graph, "scripts/this_file_is_not_governed_by_anything.py")
