"""Coverage for scripts/gen_audit_index.py (Block-3.3 audits navigation index)."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path


import gen_audit_index as gai  # noqa: E402


def _audit(d: Path, name: str, title: str | None = "T") -> None:
    body = (f"# {title}\n\nbody\n" if title is not None else "no heading here\n")
    (d / name).write_text(body, encoding="utf-8")


def test_collect_parses_date_slug_title_and_sorts_newest_first(tmp_path):
    _audit(tmp_path, "2026-01-02-alpha.md", "Alpha audit")
    _audit(tmp_path, "2026-07-05-zulu.md", "Zulu audit")
    rows = gai.collect_audits(tmp_path)
    assert [r[0] for r in rows] == ["2026-07-05", "2026-01-02"]  # newest first
    assert rows[0][1] == "zulu" and rows[0][3] == "Zulu audit"


def test_collect_excludes_the_index_readme(tmp_path):
    _audit(tmp_path, "2026-01-01-x.md")
    _audit(tmp_path, "README.md", "The index itself")
    names = {r[2] for r in gai.collect_audits(tmp_path)}
    assert "README.md" not in names  # an index never indexes itself


def test_collect_undated_file_kept_not_dropped(tmp_path):
    _audit(tmp_path, "not-a-dated-name.md", "Legacy")
    rows = gai.collect_audits(tmp_path)
    assert rows == [("", "not-a-dated-name", "not-a-dated-name.md", "Legacy")]


def test_title_placeholder_when_no_heading(tmp_path):
    _audit(tmp_path, "2026-02-02-x.md", title=None)  # no `# ` heading
    rows = gai.collect_audits(tmp_path)
    assert rows[0][3] == "(no # title)"


def test_render_has_note_count_and_month_headers(tmp_path):
    _audit(tmp_path, "2026-07-05-a.md", "Ay")
    _audit(tmp_path, "2026-06-01-b.md", "Bee")
    out = gai.render_index(tmp_path)
    assert gai._GENERATED_NOTE in out
    assert "**2 audit documents.**" in out
    assert "## 2026-07" in out and "## 2026-06" in out
    assert "- [2026-07-05](2026-07-05-a.md) — Ay" in out
    # month order: 2026-07 section appears before 2026-06 (reverse-chronological)
    assert out.index("## 2026-07") < out.index("## 2026-06")
    assert out.endswith("\n")


def test_render_is_deterministic(tmp_path):
    _audit(tmp_path, "2026-05-05-x.md")
    assert gai.render_index(tmp_path) == gai.render_index(tmp_path)


def test_pipe_in_title_is_table_safe(tmp_path):
    _audit(tmp_path, "2026-03-03-x.md", "A | B title")
    assert "A / B title" in gai.render_index(tmp_path)


# --- check/write semantics via monkeypatched module targets ------------------


def _wire(tmp_path, monkeypatch):
    target = tmp_path / "README.md"
    monkeypatch.setattr(gai, "_AUDITS_DIR", tmp_path)
    monkeypatch.setattr(gai, "_TARGET", target)
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)
    return target


def test_check_missing_is_2(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md")
    assert gai.main(["--check"]) == 2


def test_write_then_check_roundtrips(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md", "Ex")
    assert gai.main(["--write"]) == 0
    assert gai.main(["--check"]) == 0


def test_check_detects_drift(tmp_path, monkeypatch, capsys):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md")
    gai.main(["--write"])
    _audit(tmp_path, "2026-08-08-new.md", "New audit")  # a new file drifts the index
    assert gai.main(["--check"]) == 1
    assert "stale vs docs/audits/" in capsys.readouterr().err


def test_live_index_is_fresh():
    # the shipped docs/audits/README.md matches disk (the generator's own green)
    assert gai.main(["--check"]) == 0


# --- tracked-files-only: the twin of the d5b19a2d F1 fix in generate_organ_index -----
# The identical defect: collect_audits globs the working tree, so an UNTRACKED audit file
# rendered a row and the generated bytes stopped being a function of committed state.
# W5 found and fixed this shape in generate_organ_index.py (terra finding F1, commit
# d5b19a2d); these are that commit's tests, pointed at the twin.


def _git(repo: Path, *args: str) -> None:
    r = subprocess.run(["git", "-C", str(repo), *args],
                       capture_output=True, text=True, encoding="utf-8")
    assert r.returncode == 0, f"git {' '.join(args)}: {r.stderr}"


def _repo_with_audits(tmp_path: Path) -> tuple[Path, Path]:
    repo = tmp_path / "repo"
    audits = repo / "docs" / "audits"
    audits.mkdir(parents=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@t")
    _git(repo, "config", "user.name", "t")
    _git(repo, "config", "commit.gpgsign", "false")
    return repo, audits


def test_an_untracked_audit_file_does_not_change_the_generated_bytes(tmp_path, monkeypatch):
    """A REAL git repo, because the defect only exists where a tracked set exists."""
    repo, audits = _repo_with_audits(tmp_path)
    _audit(audits, "2026-01-01-technical-committed.md", "Committed audit")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "seed")
    monkeypatch.setattr(gai, "_REPO_ROOT", repo)
    monkeypatch.setattr(gai, "_AUDITS_DIR", audits)

    before = gai.render_index()
    assert "Committed audit" in before

    _audit(audits, "2026-02-02-technical-scratch.md", "Untracked scratch")
    assert gai.render_index() == before, "an untracked file moved the generated bytes"
    assert "Untracked scratch" not in gai.render_index()

    _git(repo, "add", "-A")                       # now git tracks it
    assert "Untracked scratch" in gai.render_index()


def test_tracked_files_returns_none_outside_a_git_work_tree(tmp_path):
    """None means 'cannot tell' -> filtering DISABLED, never an emptied index."""
    assert gai.tracked_files(tmp_path) is None


def test_filtering_is_disabled_outside_a_repo_so_synthetic_trees_still_render(tmp_path):
    # The honest limit, pinned: every other test in this file uses a non-repo tmp_path and
    # would silently render an EMPTY index if None had been treated as "nothing is tracked".
    _audit(tmp_path, "2026-01-01-x.md", "Ex")
    assert "Ex" in gai.render_index(tmp_path)


def test_collect_honors_an_explicit_tracked_set(tmp_path, monkeypatch):
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)   # tracked names are root-relative
    _audit(tmp_path, "2026-01-01-a.md", "Ay")
    _audit(tmp_path, "2026-01-02-b.md", "Bee")
    rows = gai.collect_audits(tmp_path, tracked=frozenset({"2026-01-01-a.md"}))
    assert [r[2] for r in rows] == ["2026-01-01-a.md"]


def test_a_path_outside_the_repo_root_is_never_silently_dropped(tmp_path, monkeypatch):
    # `_is_tracked` cannot express a path outside the root as a tracked name, and the
    # choice there is INCLUDE, not exclude: dropping a file the rule cannot judge is the
    # silent-shortening failure the tracked-files fix exists to prevent, not a fix for it.
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path / "elsewhere")
    _audit(tmp_path, "2026-01-01-a.md", "Ay")
    rows = gai.collect_audits(tmp_path, tracked=frozenset())   # tracks nothing at all
    assert [r[2] for r in rows] == ["2026-01-01-a.md"]


def test_live_index_excludes_nothing_because_every_audit_is_tracked():
    # The result to want, measured rather than assumed: the shipped index is byte-unchanged
    # by this fix (d5b19a2d recorded the same outcome for its twin).
    assert gai.main(["--check"]) == 0
    assert sys.executable  # keep the import honest under ruff
