"""Tests for scripts/codemap/ — ast_walker, mermaid_emit, generator, check, cli."""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FIXTURES = Path(__file__).parent / "fixtures"
SIMPLE_REPO = FIXTURES / "codemap-simple-repo"
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"

sys.path.insert(0, str(SCRIPTS_DIR))

from codemap.ast_walker import analyze_repo  # noqa: E402
from codemap.mermaid_emit import emit_mermaid  # noqa: E402
from codemap.generator import generate_codemap  # noqa: E402
from codemap.check import check_codemap  # noqa: E402


# ---------------------------------------------------------------------------
# Step 1 — ast_walker
# ---------------------------------------------------------------------------


def test_ast_walker_simple_repo():
    result = analyze_repo(SIMPLE_REPO)
    assert result["packages"] == ["pkg_a", "pkg_b"]
    assert result["edges"] == [("pkg_a", "pkg_b")]


def test_ast_walker_no_src_dir(tmp_path, capsys):
    result = analyze_repo(tmp_path)
    assert result == {"packages": [], "edges": []}
    captured = capsys.readouterr()
    assert "warning" in captured.err.lower()


def test_ast_walker_skips_relative(tmp_path):
    src = tmp_path / "src"
    pkg_a = src / "pkg_a"
    pkg_b = src / "pkg_b"
    for d in [pkg_a, pkg_b]:
        d.mkdir(parents=True)
        (d / "__init__.py").write_text("")
    (pkg_a / "mod.py").write_text("from . import something\nfrom .sub import x\n")
    result = analyze_repo(tmp_path)
    assert result["edges"] == []


def test_ast_walker_deterministic():
    r1 = analyze_repo(SIMPLE_REPO)
    r2 = analyze_repo(SIMPLE_REPO)
    assert r1 == r2


# ---------------------------------------------------------------------------
# Step 2 — mermaid_emit
# ---------------------------------------------------------------------------


def test_emit_includes_mermaid_fence():
    out = emit_mermaid(["pkg_a"], [])
    assert out.startswith("```mermaid\n")
    assert out.rstrip().endswith("-->")  # ends with do-not-edit comment
    # closing fence present
    assert "\n```\n" in out


def test_mermaid_emit_simple():
    out = emit_mermaid(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")])
    assert out.startswith("```mermaid\n")
    assert "flowchart TD" in out
    assert "pkg_a[pkg_a]" in out
    assert "pkg_b[pkg_b]" in out
    assert "pkg_a --> pkg_b" in out
    assert "classDef foundation" in out
    assert "<!-- generated by codemap tool; do not edit by hand -->" in out


def test_mermaid_emit_orphan_class():
    out = emit_mermaid(["pkg_a", "pkg_b", "pkg_c"], [("pkg_a", "pkg_b")])
    assert "pkg_c[pkg_c]:::orphan" in out


def test_mermaid_emit_cycle_class():
    packages = ["pkg_a", "pkg_b"]
    edges = [("pkg_a", "pkg_b"), ("pkg_b", "pkg_a")]
    out = emit_mermaid(packages, edges)
    assert "linkStyle" in out
    assert "stroke:#e03131" in out


def test_mermaid_emit_layers():
    layers = {"pkg_a": "core", "pkg_b": "foundation"}
    out = emit_mermaid(["pkg_a", "pkg_b"], [("pkg_a", "pkg_b")], layers=layers)
    assert "pkg_a[pkg_a]:::core" in out
    assert "pkg_b[pkg_b]:::foundation" in out


def test_mermaid_emit_click_directives():
    out = emit_mermaid(["pkg_a", "pkg_b"], [], click_directives=True)
    assert 'click pkg_a href "src/pkg_a/"' in out
    assert 'click pkg_b href "src/pkg_b/"' in out


def test_mermaid_emit_deterministic():
    packages = ["pkg_b", "pkg_a"]
    edges = [("pkg_b", "pkg_a"), ("pkg_a", "pkg_b")]
    r1 = emit_mermaid(packages, edges)
    r2 = emit_mermaid(packages, edges)
    assert r1 == r2


# ---------------------------------------------------------------------------
# Step 3 — generator
# ---------------------------------------------------------------------------

WITH_TACH = FIXTURES / "codemap-with-tach"
WITH_ORPHAN = FIXTURES / "codemap-with-orphan"
WITH_CYCLE = FIXTURES / "codemap-with-cycle"


def test_generator_full_flow():
    mermaid, warnings = generate_codemap(SIMPLE_REPO)
    assert mermaid.startswith("```mermaid\n")
    assert "flowchart TD" in mermaid
    assert "pkg_a" in mermaid
    assert "pkg_b" in mermaid
    assert "pkg_a --> pkg_b" in mermaid
    assert warnings == []


def test_generator_with_tach():
    mermaid, warnings = generate_codemap(WITH_TACH)
    assert "pkg_a[pkg_a]:::core" in mermaid
    assert "pkg_b[pkg_b]:::foundation" in mermaid


def test_generator_orphan_warning():
    mermaid, warnings = generate_codemap(WITH_ORPHAN)
    assert any("orphan" in w for w in warnings)
    assert "pkg_orphan[pkg_orphan]:::orphan" in mermaid


def test_generator_cycle_warning():
    mermaid, warnings = generate_codemap(WITH_CYCLE)
    assert any("circular" in w for w in warnings)
    assert "linkStyle" in mermaid


def test_generator_no_tach():
    mermaid, warnings = generate_codemap(SIMPLE_REPO)
    # no tach.toml in simple-repo → no layer classes, no tach warning
    assert not any("tach" in w.lower() for w in warnings)
    assert "flowchart TD" in mermaid


# ---------------------------------------------------------------------------
# Step 4 — check
# ---------------------------------------------------------------------------

ARCH_CLEAN = FIXTURES / "codemap-arch-clean"
ARCH_DRIFT = FIXTURES / "codemap-arch-drift"
ARCH_NOMARKERS = FIXTURES / "codemap-arch-nomarkers"


def test_check_clean():
    code, out = check_codemap(ARCH_CLEAN)
    assert code == 0
    assert out == ""


def test_check_drift():
    code, out = check_codemap(ARCH_DRIFT)
    assert code == 1
    assert "---" in out or "+++" in out  # unified diff present


def test_check_no_architecture_md(tmp_path):
    code, out = check_codemap(tmp_path)
    assert code == 2
    assert "ARCHITECTURE.md" in out


def test_check_no_markers():
    code, out = check_codemap(ARCH_NOMARKERS)
    assert code == 3
    assert "CODEMAP" in out


# ---------------------------------------------------------------------------
# Step 5 — CLI integration tests
# ---------------------------------------------------------------------------

CLI_MODULE = ["python", "-m", "codemap.cli"]
_ENV = {**os.environ, "PYTHONPATH": str(SCRIPTS_DIR)}


def _run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "codemap.cli", *args],
        capture_output=True,
        text=True,
        env=_ENV,
    )


def test_cli_generate_stdout():
    r = _run_cli("generate", str(SIMPLE_REPO))
    assert r.returncode == 0
    assert "flowchart TD" in r.stdout
    assert "pkg_a" in r.stdout


def test_cli_generate_write(tmp_path):
    # Copy arch-clean fixture to a tmp location so --write can mutate it
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    r = _run_cli("generate", str(tmp_path / "repo"), "--write")
    assert r.returncode == 0
    content = (tmp_path / "repo" / "ARCHITECTURE.md").read_text()
    assert "<!-- CODEMAP:START -->" in content
    assert "<!-- CODEMAP:END -->" in content
    assert "```mermaid" in content
    assert "flowchart TD" in content
    assert "<!-- generated by codemap tool; do not edit by hand -->" in content


def test_cli_generate_write_produces_renderable_block(tmp_path):
    shutil.copytree(str(ARCH_CLEAN), str(tmp_path / "repo"))
    _run_cli("generate", str(tmp_path / "repo"), "--write")
    content = (tmp_path / "repo" / "ARCHITECTURE.md").read_text()
    start = content.index("<!-- CODEMAP:START -->") + len("<!-- CODEMAP:START -->")
    end = content.index("<!-- CODEMAP:END -->")
    block = content[start:end]
    assert "```mermaid" in block
    assert "```\n" in block  # closing fence
    assert "flowchart TD" in block
    assert "<!-- generated by codemap tool; do not edit by hand -->" in block


def test_cli_check_clean():
    r = _run_cli("check", str(ARCH_CLEAN))
    assert r.returncode == 0


def test_cli_check_drift():
    r = _run_cli("check", str(ARCH_DRIFT))
    assert r.returncode == 1


def test_cli_help():
    r = _run_cli("--help")
    assert r.returncode == 0
    assert "generate" in r.stdout
    assert "check" in r.stdout
