"""Coverage for scripts/gen_audit_index.py (Block-3.3 audits navigation index)."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest


import gen_audit_index as gai  # noqa: E402


def _audit(d: Path, name: str, title: str | None = "T") -> None:
    body = (f"# {title}\n\nbody\n" if title is not None else "no heading here\n")
    (d / name).write_text(body, encoding="utf-8")


def test_collect_parses_date_slug_title_and_sorts_newest_first(tmp_path):
    _audit(tmp_path, "2026-01-02-alpha.md", "Alpha audit")
    _audit(tmp_path, "2026-07-05-zulu.md", "Zulu audit")
    rows = gai.collect_audits(tmp_path)
    assert [r[0] for r in rows] == ["2026-07-05", "2026-01-02"]  # newest first
    assert rows[0][1] == "zulu" and rows[0][3] == "Zulu audit"


def test_collect_excludes_the_index_readme(tmp_path):
    _audit(tmp_path, "2026-01-01-x.md")
    _audit(tmp_path, "README.md", "The index itself")
    names = {r[2] for r in gai.collect_audits(tmp_path)}
    assert "README.md" not in names  # an index never indexes itself


def test_collect_undated_file_kept_not_dropped(tmp_path):
    _audit(tmp_path, "not-a-dated-name.md", "Legacy")
    rows = gai.collect_audits(tmp_path)
    assert rows == [("", "not-a-dated-name", "not-a-dated-name.md", "Legacy")]


def test_title_placeholder_when_no_heading(tmp_path):
    _audit(tmp_path, "2026-02-02-x.md", title=None)  # no `# ` heading
    rows = gai.collect_audits(tmp_path)
    assert rows[0][3] == "(no # title)"


def test_render_has_note_count_and_month_headers(tmp_path):
    _audit(tmp_path, "2026-07-05-a.md", "Ay")
    _audit(tmp_path, "2026-06-01-b.md", "Bee")
    out = gai.render_index(tmp_path)
    assert gai._GENERATED_NOTE in out
    assert "**2 audit documents.**" in out
    assert "## 2026-07" in out and "## 2026-06" in out
    assert "- [2026-07-05](2026-07-05-a.md) — Ay" in out
    # month order: 2026-07 section appears before 2026-06 (reverse-chronological)
    assert out.index("## 2026-07") < out.index("## 2026-06")
    assert out.endswith("\n")


def test_render_is_deterministic(tmp_path):
    _audit(tmp_path, "2026-05-05-x.md")
    assert gai.render_index(tmp_path) == gai.render_index(tmp_path)


def test_pipe_in_title_is_table_safe(tmp_path):
    _audit(tmp_path, "2026-03-03-x.md", "A | B title")
    assert "A / B title" in gai.render_index(tmp_path)


# --- check/write semantics via monkeypatched module targets ------------------


def _wire(tmp_path, monkeypatch):
    target = tmp_path / "README.md"
    monkeypatch.setattr(gai, "_AUDITS_DIR", tmp_path)
    monkeypatch.setattr(gai, "_TARGET", target)
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)
    # The TITLE BASELINE moves with the corpus, or the seam detaches. Left pointing at the LIVE
    # baseline, `stale_baseline_entries` reports all twenty real names as drainable against a
    # synthetic tree that contains none of them -- a check firing on the fixture's absence
    # rather than on anything under test. An EMPTY baseline is the strict setting: in a
    # synthetic tree every title-less file is unbaselined, which is what a fixture wants.
    baseline = tmp_path / "audit-title-baseline.json"
    baseline.write_text('{"title_less": []}', encoding="utf-8")
    monkeypatch.setattr(gai, "_TITLE_BASELINE_PATH", baseline)
    return target


def test_check_missing_is_2(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md")
    assert gai.main(["--check"]) == 2


def test_write_then_check_roundtrips(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md", "Ex")
    assert gai.main(["--write"]) == 0
    assert gai.main(["--check"]) == 0


def test_check_detects_drift(tmp_path, monkeypatch, capsys):
    _wire(tmp_path, monkeypatch)
    _audit(tmp_path, "2026-01-01-x.md")
    gai.main(["--write"])
    _audit(tmp_path, "2026-08-08-new.md", "New audit")  # a new file drifts the index
    assert gai.main(["--check"]) == 1
    assert "stale vs docs/audits/" in capsys.readouterr().err


def test_live_index_is_fresh():
    # the shipped docs/audits/README.md matches disk (the generator's own green)
    assert gai.main(["--check"]) == 0


# --- tracked-files-only: the twin of the d5b19a2d F1 fix in generate_organ_index -----
# The identical defect: collect_audits globs the working tree, so an UNTRACKED audit file
# rendered a row and the generated bytes stopped being a function of committed state.
# W5 found and fixed this shape in generate_organ_index.py (terra finding F1, commit
# d5b19a2d); these are that commit's tests, pointed at the twin.


def _git(repo: Path, *args: str) -> None:
    r = subprocess.run(["git", "-C", str(repo), *args],
                       capture_output=True, text=True, encoding="utf-8")
    assert r.returncode == 0, f"git {' '.join(args)}: {r.stderr}"


def _repo_with_audits(tmp_path: Path) -> tuple[Path, Path]:
    repo = tmp_path / "repo"
    audits = repo / "docs" / "audits"
    audits.mkdir(parents=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@t")
    _git(repo, "config", "user.name", "t")
    _git(repo, "config", "commit.gpgsign", "false")
    return repo, audits


def test_an_untracked_audit_file_does_not_change_the_generated_bytes(tmp_path, monkeypatch):
    """A REAL git repo, because the defect only exists where a tracked set exists."""
    repo, audits = _repo_with_audits(tmp_path)
    _audit(audits, "2026-01-01-technical-committed.md", "Committed audit")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "seed")
    monkeypatch.setattr(gai, "_REPO_ROOT", repo)
    monkeypatch.setattr(gai, "_AUDITS_DIR", audits)

    before = gai.render_index()
    assert "Committed audit" in before

    _audit(audits, "2026-02-02-technical-scratch.md", "Untracked scratch")
    assert gai.render_index() == before, "an untracked file moved the generated bytes"
    assert "Untracked scratch" not in gai.render_index()

    _git(repo, "add", "-A")                       # now git tracks it
    assert "Untracked scratch" in gai.render_index()


def test_tracked_files_returns_none_outside_a_git_work_tree(tmp_path):
    """None means 'cannot tell' -> filtering DISABLED, never an emptied index."""
    assert gai.tracked_files(tmp_path) is None


def test_filtering_is_disabled_outside_a_repo_so_synthetic_trees_still_render(tmp_path):
    # The honest limit, pinned: every other test in this file uses a non-repo tmp_path and
    # would silently render an EMPTY index if None had been treated as "nothing is tracked".
    _audit(tmp_path, "2026-01-01-x.md", "Ex")
    assert "Ex" in gai.render_index(tmp_path)


def test_collect_honors_an_explicit_tracked_set(tmp_path, monkeypatch):
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)   # tracked names are root-relative
    _audit(tmp_path, "2026-01-01-a.md", "Ay")
    _audit(tmp_path, "2026-01-02-b.md", "Bee")
    rows = gai.collect_audits(tmp_path, tracked=frozenset({"2026-01-01-a.md"}))
    assert [r[2] for r in rows] == ["2026-01-01-a.md"]


def test_a_path_outside_the_repo_root_is_never_silently_dropped(tmp_path, monkeypatch):
    # `_is_tracked` cannot express a path outside the root as a tracked name, and the
    # choice there is INCLUDE, not exclude: dropping a file the rule cannot judge is the
    # silent-shortening failure the tracked-files fix exists to prevent, not a fix for it.
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path / "elsewhere")
    _audit(tmp_path, "2026-01-01-a.md", "Ay")
    rows = gai.collect_audits(tmp_path, tracked=frozenset())   # tracks nothing at all
    assert [r[2] for r in rows] == ["2026-01-01-a.md"]


def test_live_index_excludes_nothing_because_every_audit_is_tracked():
    # The result to want, measured rather than assumed: the shipped index is byte-unchanged
    # by this fix (d5b19a2d recorded the same outcome for its twin).
    assert gai.main(["--check"]) == 0
    assert sys.executable  # keep the import honest under ruff


# --- terra review 2026-08-12: the two findings, each pinned by the case that produced it


def _can_symlink(tmp_path: Path) -> bool:
    try:
        (tmp_path / "_t").write_text("x", encoding="utf-8")
        (tmp_path / "_l").symlink_to(tmp_path / "_t")
        return True
    except (OSError, NotImplementedError):
        return False          # Windows without developer mode / privilege


def test_an_untracked_symlink_does_not_change_the_generated_bytes(tmp_path, monkeypatch):
    """Terra finding 1 (HIGH), reproduced then pinned.

    Resolving the CANDIDATE followed the link out of the repo, hit the out-of-root
    branch, and INCLUDED the file — the filter's one open door. The name is derived
    lexically now, so an untracked symlink is just an untracked path.
    """
    if not _can_symlink(tmp_path):
        pytest.skip("symlink creation not permitted in this environment")
    repo, audits = _repo_with_audits(tmp_path)
    _audit(audits, "2026-01-01-technical-committed.md", "Committed audit")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "seed")
    monkeypatch.setattr(gai, "_REPO_ROOT", repo)
    monkeypatch.setattr(gai, "_AUDITS_DIR", audits)
    before = gai.render_index()

    outside = tmp_path / "outside"
    outside.mkdir()
    target = outside / "scratch.md"
    target.write_text("# Untracked scratch via symlink\n", encoding="utf-8")
    (audits / "2026-02-02-technical-scratch.md").symlink_to(target)

    assert gai.render_index() == before, "an untracked SYMLINK moved the generated bytes"
    assert "Untracked scratch" not in gai.render_index()


def test_tracked_files_fails_open_when_git_times_out(tmp_path, monkeypatch):
    """Terra finding 2 (MEDIUM): every failure mode lands on the same fail-open answer.

    Unbounded, a stalled git would HANG the pre-commit gate rather than fail it.
    """
    def _timeout(*a, **kw):
        assert kw.get("timeout"), "the call must be bounded, or this test proves nothing"
        raise subprocess.TimeoutExpired(cmd="git ls-files", timeout=kw["timeout"])

    monkeypatch.setattr(gai.subprocess, "run", _timeout)
    assert gai.tracked_files(tmp_path) is None


# --- the TITLE gate: a title-less artifact is loud, against a grandfathered baseline --------
#
# THE DEFECT, measured 2026-09-01: `_title_of` returns the placeholder `(no # title)` when a
# file carries no `# ` heading, and NOTHING reads that placeholder. 20 of 837 indexed audits
# render it — nine of them harvested cloud artifacts whose persist shape puts the PROVENANCE
# blockquote FIRST and never emits an H1 at all, so the corpus's largest doc area has twenty
# rows a reader cannot navigate by. The index was doing exactly what it was told and telling
# nobody.
#
# ARMED AS A RATCHET, NOT A DAY-ONE RED — `check_adr_status_grammar`'s pattern. The 20 live
# instances are recorded in a committed baseline and grandfathered; the twenty-FIRST is a
# refusal. A day-one FAIL would have to be bypassed on its first commit, which trains the
# bypass rather than the fix.

def test_a_title_less_audit_is_detected_at_all(tmp_path):
    (tmp_path / "2026-01-01-technical-titled.md").write_text(
        "# A real title\n\nbody\n", encoding="utf-8")
    (tmp_path / "2026-01-02-technical-headless.md").write_text(
        "> **PROVENANCE — harvested.**\n\nbody with no heading\n", encoding="utf-8")
    missing = gai.title_less(audits_dir=tmp_path, tracked=None)
    assert missing == ("2026-01-02-technical-headless.md",)


def test_a_heading_below_the_provenance_block_still_counts_as_a_title(tmp_path):
    """The rule is H1-PRESENT, not H1-FIRST — stated so the two are not conflated.

    `_title_of` searches the whole file, so an artifact whose provenance blockquote precedes
    its `# ` heading is already indexed correctly. The ORDERING preference belongs to whoever
    writes the persist template; the GATE's business is the heading's existence, and pinning
    ordering here would refuse files the index renders perfectly.
    """
    (tmp_path / "2026-01-03-technical-late-title.md").write_text(
        "> **PROVENANCE — harvested.**\n\n# The title, after the provenance\n\nbody\n",
        encoding="utf-8")
    assert gai.title_less(audits_dir=tmp_path, tracked=None) == ()


def test_the_baseline_grandfathers_exactly_the_recorded_names(tmp_path):
    (tmp_path / "2026-01-02-technical-headless.md").write_text("no heading\n", encoding="utf-8")
    baseline = frozenset({"2026-01-02-technical-headless.md"})
    assert gai.unbaselined_title_less(
        audits_dir=tmp_path, tracked=None, baseline=baseline) == ()
    assert gai.unbaselined_title_less(
        audits_dir=tmp_path, tracked=None, baseline=frozenset()) == (
            "2026-01-02-technical-headless.md",)


def test_a_baselined_name_that_GAINED_a_title_is_reported_as_drainable(tmp_path):
    """The ratchet's other direction. A baseline that only ever grows is a debt register
    nobody pays down; a fixed artifact still sitting in it hides the next real one."""
    (tmp_path / "2026-01-02-technical-headless.md").write_text(
        "# Now it has one\n", encoding="utf-8")
    stale = gai.stale_baseline_entries(
        audits_dir=tmp_path, tracked=None,
        baseline=frozenset({"2026-01-02-technical-headless.md"}))
    assert stale == ("2026-01-02-technical-headless.md",)


def test_check_exits_1_and_names_the_required_shape_on_a_new_title_less_audit(
        tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(gai, "_AUDITS_DIR", tmp_path)
    monkeypatch.setattr(gai, "_TARGET", tmp_path / "README.md")
    monkeypatch.setattr(gai, "_TITLE_BASELINE_PATH", tmp_path / "baseline.json")
    # `_cmd_check` renders its message with `_TARGET.relative_to(_REPO_ROOT)`, so the root has
    # to move with the target. Patching one and not the other is the seam-detaches-silently
    # class the audit_checks registry docstring warns about, in miniature.
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)
    (tmp_path / "baseline.json").write_text('{"title_less": []}', encoding="utf-8")
    (tmp_path / "2026-01-02-technical-headless.md").write_text("no heading\n", encoding="utf-8")
    (tmp_path / "README.md").write_text(gai.render_index(tmp_path, None), encoding="utf-8")
    assert gai.main(["--check"]) == 1
    err = capsys.readouterr().err
    assert "2026-01-02-technical-headless.md" in err
    assert "# " in err                      # the required shape is named, not just the miss


def test_the_live_baseline_matches_the_live_corpus():
    """The committed baseline is the measurement, so it has to agree with the tree."""
    assert gai.unbaselined_title_less() == ()
    assert gai.stale_baseline_entries() == ()


def test_check_titles_is_reachable_without_the_index(tmp_path, monkeypatch, capsys):
    """`--check-titles` reads FILES, never the generated index — which is what lets it be
    armed on `docs/audits/**` without re-creating the `[#590]` merge-conflict problem.

    `[#590]` narrowed `audit-index-freshness` to the index and its generator BECAUSE requiring
    every lane to regenerate a shared file put it in 6 of the last 7 conflicted merges. The
    title check has no such coupling: it writes nothing and touches no shared artifact, so it
    can fire on the commit that ADDS an audit while the index stays where [#590] put it.
    """
    monkeypatch.setattr(gai, "_AUDITS_DIR", tmp_path)
    monkeypatch.setattr(gai, "_REPO_ROOT", tmp_path)
    monkeypatch.setattr(gai, "_TITLE_BASELINE_PATH", tmp_path / "baseline.json")
    (tmp_path / "baseline.json").write_text('{"title_less": []}', encoding="utf-8")
    (tmp_path / "2026-01-02-technical-headless.md").write_text("no heading\n", encoding="utf-8")
    # NO README.md is written: the point is that this mode does not need one.
    assert gai.main(["--check-titles"]) == 1
    assert "2026-01-02-technical-headless.md" in capsys.readouterr().err


def test_check_titles_is_green_on_the_live_corpus():
    assert gai.main(["--check-titles"]) == 0


def test_the_title_hook_is_armed_on_the_audits_tree_not_just_the_index():
    """The mechanism's binding point, asserted against the config rather than assumed.

    Written after the claim "the gate binds at the commit that ADDS an artifact" was found to
    be FALSE: `audit-index-freshness` is scoped to the index and its generator, so it fires on
    neither the artifact nor its author. A gate's coverage is a property of its `files:`
    pattern, and a coverage claim nothing checks is the class this repo keeps re-learning.
    """
    cfg = (Path(gai.__file__).resolve().parent.parent / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    block = cfg.split("id: audit-title-gate", 1)
    assert len(block) == 2, "no audit-title-gate hook is declared"
    body = block[1].split("- id:", 1)[0]
    assert "--check-titles" in body
    assert "docs/audits/" in body
