"""Generate a nested anchor-link TOC from a markdown file's headers.

Mirrors the codemap generator: parse the document, emit a block that gets
written between <!-- TOC:START --> / <!-- TOC:END --> markers and is
freshness-checked the same way the codemap is (ADR-51).
"""
from __future__ import annotations

import re
from pathlib import Path

_DO_NOT_EDIT = "<!-- generated by toc tool; do not edit by hand -->"

# Trailing classification tag like " [CORE]" — stripped from the visible link
# text but retained in the anchor (GitHub slugs the *full* header text, so
# `## Purpose [CORE]` resolves to `#purpose-core`).
_TAG_RE = re.compile(r"\s*\[[^\]]+\]\s*$")
# ## or ### headers only (h1 is the doc title; h4+ is too granular for a TOC).
_HEADER_RE = re.compile(r"^(#{2,3})\s+(.*?)\s*$")


def _slugify(text: str) -> str:
    """GitHub-compatible anchor slug (mirrors github-slugger).

    Lowercase; drop everything except word chars, spaces and hyphens;
    spaces -> hyphens. Consecutive hyphens are NOT collapsed (matches GitHub:
    e.g. "A & B" -> "a--b" because the removed '&' leaves two spaces).
    """
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    return slug


def _display(text: str) -> str:
    """Header text with a trailing [TAG] removed, for clean TOC link text."""
    return _TAG_RE.sub("", text).strip()


def parse_headers(content: str) -> list[tuple[int, str]]:
    """Return [(level, raw_header_text), ...] for ## / ### headers.

    Lines inside ``` fenced code blocks are skipped so fence content (mermaid,
    sample markdown, etc.) is never mistaken for a heading.
    """
    headers: list[tuple[int, str]] = []
    in_fence = False
    for line in content.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = _HEADER_RE.match(line)
        if m:
            headers.append((len(m.group(1)), m.group(2)))
    return headers


def generate_toc(md_file: Path) -> str:
    """Return the TOC block body: a nested bullet list + the do-not-edit comment.

    The returned string ends with a newline; the CLI/check prepend a leading
    newline so the END marker lands on its own line (mirrors codemap).
    """
    content = md_file.read_text(encoding="utf-8")
    headers = parse_headers(content)

    seen: dict[str, int] = {}
    lines: list[str] = []
    for level, raw in headers:
        anchor = _slugify(raw)
        # GitHub disambiguates duplicate anchors with -1, -2, ...
        count = seen.get(anchor, 0)
        seen[anchor] = count + 1
        if count:
            anchor = f"{anchor}-{count}"
        indent = "  " * (level - 2)
        lines.append(f"{indent}- [{_display(raw)}](#{anchor})")

    body = "\n".join(lines)
    return f"{body}\n{_DO_NOT_EDIT}\n"
