"""Generate a nested anchor-link TOC from a markdown file's headers.

Mirrors the codemap generator: parse the document, emit a block that gets
written between <!-- TOC:START --> / <!-- TOC:END --> markers and is
freshness-checked the same way the codemap is (ADR-51).
"""
from __future__ import annotations

import re
from pathlib import Path

from markdown_it import MarkdownIt

_DO_NOT_EDIT = "<!-- generated by toc tool; do not edit by hand -->"

_MD = MarkdownIt("commonmark")
# Split exactly where markdown_it does (`\r\n | \r | \n`), so our line indices and its token
# `map` indices cannot desync. Neither stdlib option is safe here: `split("\n")` misses a lone
# `\r`, and `splitlines()` also breaks on \x0b \x0c    , which CommonMark does not
# treat as line boundaries — either would slide every index after the offending character.
_EOL_RE = re.compile(r"\r\n|\r|\n")

# Trailing classification tag like " [CORE]" — stripped from the visible link
# text but retained in the anchor (GitHub slugs the *full* header text, so
# `## Purpose [CORE]` resolves to `#purpose-core`).
_TAG_RE = re.compile(r"\s*\[[^\]]+\]\s*$")
# ## or ### headers only (h1 is the doc title; h4+ is too granular for a TOC).
_HEADER_RE = re.compile(r"^(#{2,3})\s+(.*?)\s*$")


def _slugify(text: str) -> str:
    """GitHub-compatible anchor slug (mirrors github-slugger).

    Lowercase; drop everything except word chars, spaces and hyphens;
    spaces -> hyphens. Consecutive hyphens are NOT collapsed (matches GitHub:
    e.g. "A & B" -> "a--b" because the removed '&' leaves two spaces).
    """
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    return slug


def _display(text: str) -> str:
    """Header text with a trailing [TAG] removed, for clean TOC link text."""
    return _TAG_RE.sub("", text).strip()


def _code_line_indices(content: str) -> set[int]:
    """0-based source lines inside a CommonMark code block (fenced or indented).

    `code_block` (indented code) is included for completeness; it is a no-op for the caller,
    since a 4-space-indented line can never match the column-anchored `_HEADER_RE` anyway.
    """
    idx: set[int] = set()
    for tok in _MD.parse(content):
        if tok.type in ("fence", "code_block") and tok.map:
            idx.update(range(tok.map[0], tok.map[1]))
    return idx


def parse_headers(content: str) -> list[tuple[int, str]]:
    """Return [(level, raw_header_text), ...] for ## / ### headers.

    WHICH LINES ARE HEADINGS is decided by CommonMark (markdown_it), so fenced content —
    mermaid, sample markdown, transcript blocks — is excluded by construction. The former
    `line.lstrip().startswith("```")` toggle diverged from CommonMark in BOTH directions:

      false NEGATIVE  a closing fence may not carry an info string, so ```` ```markdown ````
                      after an open fence is CONTENT. The toggle counted it, ended up stuck
                      "inside a fence", and silently dropped every heading in the rest of the
                      document. This is the dominant cause on the live corpus — 9 of 1577
                      files diverge, one of them 5 headings found against CommonMark's 13.
      false POSITIVE  `~~~` is a legal fence the toggle does not know, so sample markdown
                      inside one was harvested as real headings; likewise a 3-backtick line
                      legally nested inside a 4-backtick fence closed it early.

    ONLY THE FENCE DECISION MOVES. markdown_it is used to locate CODE RANGES, and `_HEADER_RE`
    then runs over every line outside them exactly as before — so level, text, tag handling and
    the column-0 anchor are all untouched, and the change can only RECOVER headers the toggle
    swallowed, never drop one it found.

    An earlier revision gated on markdown_it `heading_open` tokens instead, which was a wider
    contract change than intended and was refuted in review: a `## Foo` line inside an HTML
    block or an unterminated HTML comment is NOT a CommonMark heading, so the token gate would
    have DROPPED entries the raw-line parser returned — shrinking a generated TOC and shifting
    duplicate-anchor numbering. Locating code ranges avoids that entirely.
    """
    lines = _EOL_RE.split(content)
    code = _code_line_indices(content)
    headers: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        if i in code:
            continue
        m = _HEADER_RE.match(line)
        if m:
            headers.append((len(m.group(1)), m.group(2)))
    return headers


def generate_toc(md_file: Path) -> str:
    """Return the TOC block body: a nested bullet list + the do-not-edit comment.

    The returned string ends with a newline; the CLI/check prepend a leading
    newline so the END marker lands on its own line (mirrors codemap).
    """
    content = md_file.read_text(encoding="utf-8")
    headers = parse_headers(content)

    seen: dict[str, int] = {}
    lines: list[str] = []
    for level, raw in headers:
        anchor = _slugify(raw)
        # GitHub disambiguates duplicate anchors with -1, -2, ...
        count = seen.get(anchor, 0)
        seen[anchor] = count + 1
        if count:
            anchor = f"{anchor}-{count}"
        indent = "  " * (level - 2)
        lines.append(f"{indent}- [{_display(raw)}](#{anchor})")

    body = "\n".join(lines)
    return f"{body}\n{_DO_NOT_EDIT}\n"
