"""Compact-text codemap generation from package/edge data.

Canonical output form per ADR-51 amendment 2026-07-05 (LLM-first canonical
docs): a module/layer table plus a dependency list — the same facts the
Mermaid form carried (modules, tach.toml layers, import edges, orphan and
cycle classification, per-module source paths) with no render-layer syntax.
``mermaid_emit`` is retained separately for the human-facing visualization
surface and is no longer wired into the generator.
"""
from __future__ import annotations

from .mermaid_emit import _find_cycles


def emit_text(
    packages: list[str],
    edges: list[tuple[str, str]],
    layers: dict[str, str] | None = None,
    source_root: str = "src",
) -> str:
    """Return the complete markdown content for insertion between CODEMAP markers.

    Output is a plain markdown module/layer table followed by a dependency
    list and a "do not edit" comment — no fenced block, no Mermaid.

    Packages are sorted alphabetically; edges sorted by (from, to).
    Orphan packages (no in/out edges) are flagged ``orphan``.
    Edges participating in an import cycle are flagged ``[cycle]``.
    """
    packages = sorted(packages)
    edges = sorted(edges)
    layers = layers or {}

    connected = set()
    for src, dst in edges:
        connected.add(src)
        connected.add(dst)
    orphans = {p for p in packages if p not in connected}

    cycle_edges = _find_cycles(packages, edges)

    lines: list[str] = [
        f"Modules (source root: `{source_root}/`; layer from tach.toml, `-` = unassigned):",
        "",
        "| module | layer | path | flags |",
        "|---|---|---|---|",
    ]
    if packages:
        for pkg in packages:
            layer = layers.get(pkg, "-") or "-"
            flags = "orphan" if pkg in orphans else "-"
            lines.append(f"| {pkg} | {layer} | {source_root}/{pkg}/ | {flags} |")
    else:
        lines.append("| (none) | - | - | - |")

    lines.append("")
    lines.append("Dependencies (`from -> to`; `[cycle]` marks an edge on an import cycle):")
    if edges:
        for src, dst in edges:
            suffix = " [cycle]" if (src, dst) in cycle_edges else ""
            lines.append(f"- {src} -> {dst}{suffix}")
    else:
        lines.append("- (none)")

    return "\n".join(lines) + "\n<!-- generated by codemap tool; do not edit by hand -->\n"
