#!/usr/bin/env python
"""RF-2 SessionStart self-arm — arm this checkout's git-side gates (idempotent, fail-soft).

Two things are armed, and they are unrelated except in failing the same way — declared in a
tracked config file, inert until a per-checkout local setting exists:
  1. the pre-commit-managed git hooks (pre-commit / commit-msg / pre-push), RF-2; and
  2. `merge.ours.driver`, without which the `.gitattributes` `merge=ours` pin on
     `docs/audits/README.md` silently does nothing ([#590]).


Makes the hub apply configured->armed->proven to ITSELF (Fable architecture review 2026-07-04
§4): a fresh clone's first session installs all three hook types (pre-commit / commit-msg /
pre-push), closing the configured-but-unarmed window a fresh clone opens (the direct-to-main
533109f RF-2 cites, six days after block-ff-push shipped). The armed state is asserted — and a
gap surfaced loud — by audit.py::check_hooks_armed.

Two robustness properties the naive `pre_commit install` lacks:
  - Quiet + idempotent: if the three hooks are already present and pre-commit-managed at the
    RESOLVED hooks dir (`git rev-parse --git-path hooks`, which honors core.hooksPath), it
    no-ops without reinstalling — so a warm session prints nothing.
  - core.hooksPath-tolerant: pre-commit REFUSES to install when core.hooksPath is set (even to
    the default .git/hooks). This checkout has it set; a fresh clone does not. On refusal this
    reports the state and exits 0 — the check_hooks_armed gate still verifies the resolved dir.

Never blocks the session (always exits 0). Hub self-arm only; consumer arming travels via the
floor carrier's own SessionStart (unchanged). Not a codemap node (a flat module).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

HOOK_TYPES = ("pre-commit", "commit-msg", "pre-push")
_SIGNATURE = "File generated by pre-commit"

# [#590] — the second thing this checkout must ARM, and it fails in the same shape as an
# uninstalled hook: `.gitattributes` declares `docs/audits/README.md merge=ours`, but `ours`
# is NOT a built-in merge driver. Git resolves it through this config key, and without the
# key the attribute silently does nothing and the merge conflicts exactly as before
# (verified empirically 2026-08-26: attribute-without-driver CONFLICTs, attribute+driver is
# clean). Configured-but-unarmed, which is the window RF-2 exists to close.
#
# `true` is the coreutils/git-builtin no-op that exits 0 without writing the worktree file,
# which is precisely "keep ours" — the value git's own gitattributes(5) documentation gives
# for this driver. Set at --local scope: a linked worktree shares the primary checkout's
# config file, so arming once arms every lane.
_MERGE_DRIVER_KEY = "merge.ours.driver"
_MERGE_DRIVER_VALUE = "true"
# The shim's baked interpreter line, e.g. INSTALL_PYTHON='C:\...\python.exe'
_INSTALL_PYTHON_RE = re.compile(r"^INSTALL_PYTHON='?([^'\r\n]+?)'?\s*$", re.MULTILINE)


def _hooks_dir(root: Path) -> Path | None:
    """The active hooks dir per git (honors core.hooksPath), or None if unresolvable."""
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=root, capture_output=True, text=True, timeout=10,
        )
    except Exception:
        return None
    if r.returncode != 0:
        return None
    return (root / r.stdout.strip()).resolve()


def _stale_interpreter(text: str) -> bool:
    """True when the shim's baked INSTALL_PYTHON is not THIS interpreter.

    ADR-106 / terra review P1 (2026-07-27): pre-commit bakes the installing
    interpreter into the generated shim, so shims installed pre-uv keep invoking
    the former system python forever — `_armed` saw the signature and never
    reinstalled. A mismatched binding now counts as unarmed, and the reinstall
    rebinds the shim to the invoking (uv-run venv) interpreter. No
    INSTALL_PYTHON line (unknown template) is treated as fine — fail-soft."""
    m = _INSTALL_PYTHON_RE.search(text)
    if not m:
        return False
    return (os.path.normcase(os.path.normpath(m.group(1)))
            != os.path.normcase(os.path.normpath(sys.executable)))


def _armed(hooks: Path) -> bool:
    """True iff all three hook types exist, carry the pre-commit signature, and are
    bound to the CURRENT interpreter (see _stale_interpreter)."""
    for name in HOOK_TYPES:
        h = hooks / name
        if not h.exists():
            return False
        text = h.read_text(encoding="utf-8", errors="replace")
        if _SIGNATURE not in text or _stale_interpreter(text):
            return False
    return True


def merge_driver_armed(root: Path) -> bool:
    """True iff `merge.ours.driver` resolves for `root` ([#590]).

    Read with `git config --get`, which walks the same precedence git itself uses when it
    resolves the attribute, so this answers the question that matters — *would a merge
    honour `merge=ours` here* — rather than *is the key in this one file*. Any git failure
    reads as UNARMED: the caller's response is an idempotent re-arm, so a false negative
    costs one no-op write while a false positive would leave the gate silently disabled.
    """
    try:
        r = subprocess.run(
            ["git", "config", "--get", _MERGE_DRIVER_KEY],
            cwd=root, capture_output=True, text=True, timeout=10,
        )
    except Exception:
        return False
    return r.returncode == 0 and r.stdout.strip() == _MERGE_DRIVER_VALUE


def arm_merge_driver(root: Path) -> bool:
    """Idempotently arm the `ours` merge driver. Returns True if it wrote. Never raises.

    Fail-soft like everything else here: a checkout where this cannot be set still commits
    and still merges — it merges WITH CONFLICTS on the audits index, which is the state that
    existed before [#590], and `check_hooks_armed` is what makes that visible rather than
    silent.
    """
    if merge_driver_armed(root):
        return False
    try:
        subprocess.run(
            ["git", "config", "--local", _MERGE_DRIVER_KEY, _MERGE_DRIVER_VALUE],
            cwd=root, capture_output=True, text=True, timeout=10, check=True,
        )
    except Exception as exc:  # never block the session
        print(f"[self-arm] {_MERGE_DRIVER_KEY} not set (fail-soft): {exc!r}")
        return False
    print(f"[self-arm] {_MERGE_DRIVER_KEY}={_MERGE_DRIVER_VALUE} "
          f"(the .gitattributes merge=ours pin for docs/audits/README.md, [#590])")
    return True


def main(root: Path | None = None) -> int:
    root = Path(root) if root is not None else Path(__file__).resolve().parent.parent
    if not (root / ".pre-commit-config.yaml").exists():
        return 0  # nothing to arm
    # Arm the merge driver FIRST and unconditionally: it is independent of the hook state, so
    # gating it behind the `_armed` early return below would leave it unset on every warm
    # session — i.e. on almost every session.
    arm_merge_driver(root)
    hooks = _hooks_dir(root)
    if hooks is not None and _armed(hooks):
        return 0  # already armed — quiet no-op (the common warm-session case)
    try:
        r = subprocess.run(
            [sys.executable, "-m", "pre_commit", "install",
             "-t", "pre-commit", "-t", "commit-msg", "-t", "pre-push"],
            cwd=root, capture_output=True, text=True, timeout=60,
        )
    except Exception as exc:  # never block the session
        print(f"[self-arm] pre-commit install skipped (fail-soft): {exc!r}")
        return 0
    if r.returncode == 0:
        print("[self-arm] git hooks installed (pre-commit / commit-msg / pre-push)")
    else:
        # e.g. core.hooksPath set -> pre-commit refuses; check_hooks_armed still verifies the
        # resolved hooks dir, so this is a fail-soft note, never a block.
        note = (r.stderr or r.stdout or "").strip().splitlines()
        print(f"[self-arm] pre-commit install did not run (fail-soft): "
              f"{note[0] if note else 'unknown reason'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
