#!/usr/bin/env python
"""RF-2 SessionStart self-arm — install the pre-commit-managed git hooks (idempotent, fail-soft).

Makes the hub apply configured->armed->proven to ITSELF (Fable architecture review 2026-07-04
§4): a fresh clone's first session installs all three hook types (pre-commit / commit-msg /
pre-push), closing the configured-but-unarmed window a fresh clone opens (the direct-to-main
533109f RF-2 cites, six days after block-ff-push shipped). The armed state is asserted — and a
gap surfaced loud — by audit.py::check_hooks_armed.

Two robustness properties the naive `pre_commit install` lacks:
  - Quiet + idempotent: if the three hooks are already present and pre-commit-managed at the
    RESOLVED hooks dir (`git rev-parse --git-path hooks`, which honors core.hooksPath), it
    no-ops without reinstalling — so a warm session prints nothing.
  - core.hooksPath-tolerant: pre-commit REFUSES to install when core.hooksPath is set (even to
    the default .git/hooks). This checkout has it set; a fresh clone does not. On refusal this
    reports the state and exits 0 — the check_hooks_armed gate still verifies the resolved dir.

Never blocks the session (always exits 0). Hub self-arm only; consumer arming travels via the
floor carrier's own SessionStart (unchanged). Not a codemap node (a flat module).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

HOOK_TYPES = ("pre-commit", "commit-msg", "pre-push")
_SIGNATURE = "File generated by pre-commit"
# The shim's baked interpreter line, e.g. INSTALL_PYTHON='C:\...\python.exe'
_INSTALL_PYTHON_RE = re.compile(r"^INSTALL_PYTHON='?([^'\r\n]+?)'?\s*$", re.MULTILINE)


def _hooks_dir(root: Path) -> Path | None:
    """The active hooks dir per git (honors core.hooksPath), or None if unresolvable."""
    try:
        r = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=root, capture_output=True, text=True, timeout=10,
        )
    except Exception:
        return None
    if r.returncode != 0:
        return None
    return (root / r.stdout.strip()).resolve()


def _stale_interpreter(text: str) -> bool:
    """True when the shim's baked INSTALL_PYTHON is not THIS interpreter.

    ADR-106 / terra review P1 (2026-07-27): pre-commit bakes the installing
    interpreter into the generated shim, so shims installed pre-uv keep invoking
    the former system python forever — `_armed` saw the signature and never
    reinstalled. A mismatched binding now counts as unarmed, and the reinstall
    rebinds the shim to the invoking (uv-run venv) interpreter. No
    INSTALL_PYTHON line (unknown template) is treated as fine — fail-soft."""
    m = _INSTALL_PYTHON_RE.search(text)
    if not m:
        return False
    return (os.path.normcase(os.path.normpath(m.group(1)))
            != os.path.normcase(os.path.normpath(sys.executable)))


def _armed(hooks: Path) -> bool:
    """True iff all three hook types exist, carry the pre-commit signature, and are
    bound to the CURRENT interpreter (see _stale_interpreter)."""
    for name in HOOK_TYPES:
        h = hooks / name
        if not h.exists():
            return False
        text = h.read_text(encoding="utf-8", errors="replace")
        if _SIGNATURE not in text or _stale_interpreter(text):
            return False
    return True


def main(root: Path | None = None) -> int:
    root = Path(root) if root is not None else Path(__file__).resolve().parent.parent
    if not (root / ".pre-commit-config.yaml").exists():
        return 0  # nothing to arm
    hooks = _hooks_dir(root)
    if hooks is not None and _armed(hooks):
        return 0  # already armed — quiet no-op (the common warm-session case)
    try:
        r = subprocess.run(
            [sys.executable, "-m", "pre_commit", "install",
             "-t", "pre-commit", "-t", "commit-msg", "-t", "pre-push"],
            cwd=root, capture_output=True, text=True, timeout=60,
        )
    except Exception as exc:  # never block the session
        print(f"[self-arm] pre-commit install skipped (fail-soft): {exc!r}")
        return 0
    if r.returncode == 0:
        print("[self-arm] git hooks installed (pre-commit / commit-msg / pre-push)")
    else:
        # e.g. core.hooksPath set -> pre-commit refuses; check_hooks_armed still verifies the
        # resolved hooks dir, so this is a fail-soft note, never a block.
        note = (r.stderr or r.stdout or "").strip().splitlines()
        print(f"[self-arm] pre-commit install did not run (fail-soft): "
              f"{note[0] if note else 'unknown reason'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
