#!/usr/bin/env python
"""consumer_at_landing.py — the subtraction mechanism for `docs/audits/` (`[#595]`, intake #54).

THE FINDING, in the diagnostic's own words
(`docs/audits/2026-08-26-technical-hub-diagnostic.md` §3.1 and §7 Q3): *"290 audit files (40%
of the tree) have no human or governance consumer, and 49 are cited by nothing at all."* And
the reason it stayed invisible: *"The fleet instruments LANDING and never CONSUMPTION, so
accumulation is invisible by construction."*

THIS MODULE INSTRUMENTS BOTH ENDS.

  * **At landing** — an artifact that lands declares its consumer: it carries at least one
    governance citation (a `[#id]` row, an `ADR-<n>`, a `STANDING_RULINGS` section, an
    `intake #<n>`), or an explicit `no-consumer: <reason>`. Measured before arming: **99 of
    the 109 artifacts landed since 2026-08-20 already pass** — the predicate admits honest
    work and catches the accumulating class (probe reports and research memos), which is the
    class the diagnostic named.
  * **As consumption** — whether any governance surface actually cites it, measured the way
    the diagnostic measured it, against a committed identity baseline.

IDENTIFIER-KEYED, NEVER FILENAME-KEYED. This is the row's explicit requirement and the
diagnostic's own lesson: *"three of the four false-positive buckets were false because the
corpus cites by IDENTIFIER (`ADR-<n>`, `intake #<n>`, `wf-<id>`) rather than by path… Any
future reaper that keys on filenames alone would have proposed deleting 14 live documents and
420 live handoff files."* An audit's identifier set is therefore its filename, its bare stem,
AND any trailing commission id (`-wf-<hex>`) — the `docs/archive/README.md` convention, which
the diagnostic verified re-measures four "orphans" to zero.

THE GOVERNANCE POOL IS THE DIAGNOSTIC'S, COPIED RATHER THAN RE-DECIDED. Included: `tasks/`,
`docs/decisions/`, `docs/intake/`, `protocols/`, and the root canonical docs. **Deliberately
excluded, and this is the crux the diagnostic states in terms:** `JOURNAL.md`,
`docs/handoffs/**`, `ecosystem/`, `scripts/`, `tests/`, `.claude/`, `templates/`, `deploy/` —
*"A mention in a session log or a machine baseline is a record that the file existed, not
evidence that anything consumes it."* That exclusion is the whole finding: 241 audits appear
in `ecosystem/audit-funnel-baseline.json` and nowhere else outside their own tree.

THE DATE CUTOFF IS THE ROW'S "new landings only". The declaration leg binds artifacts dated on
or after `ARM_DATE`; the 290 historical orphans are grandfathered, and the grandfathered count
is printed on every run rather than dropped. The consumption leg has no cutoff — it is a
ratchet against a named baseline, which is how the row's *"does not grow window-over-window"*
is made checkable.

THE RATCHET IS KEYED ON IDENTITY, NOT A COUNT — the `funnel_coverage` precedent, adopted for
the reason that module records: *"A bare integer baseline is satisfied by dispositioning one
old artifact while adding one new undispositioned one — net zero, debt unchanged, gate
silent."* Here the same swap surfaces by name.

`info` RATHER THAN A PASS WHEN CITATIONS CANNOT BE RESOLVED — the row's third leg. If the
governance pool is absent or unreadable, `pool_resolved` is False and the ratchet reports a
WARN saying so instead of reporting zero unconsumed artifacts. A pool that could not be read
produces the same number as a pool in which everything is cited, and those two are not the
same fact.

LIBRARY-FIRST: the audit-name pattern is imported from `funnel_coverage`, not re-derived. That
regex carries five rounds of measured boundary hardening — the both-sided lookaround that stops
`2026-08-01-technical-a.md.bak` and `typo2026-08-01-technical-a.md` binding to the real
artifact. A second copy would be a second chance to get that wrong.

HONEST LIMITS:
  * The landing leg checks that an artifact NAMES a governance surface, not that the surface
    named is real or that it agrees. `[#99999]` passes. It converts an unfalsifiable habit
    into a checkable one; it does not make the citation true.
  * Consumption is a substring match over the pool, as the diagnostic's was. A row that names
    an artifact only to say it is obsolete counts as a citer.
  * `no-consumer:` is honoured on the reason's LENGTH, which distinguishes a recorded reason
    from a token and nothing more — the same weakness `funnel_coverage` records for REJECTED.
  * The corpus is RECURSIVE under `docs/audits/` and keyed on BASENAME, because a basename is
    what a governance surface cites. Two artifacts sharing a basename at different depths
    would collide; none does today and the dated-name grammar makes it unlikely, but that is a
    property of the keying rather than a proof.

Read-only (Layer 2): the baseline is regenerated by an explicit `--write-baseline`, never as a
side effect of measuring.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import logging
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:  # importable both as a module and as a script
    sys.path.insert(0, str(_SCRIPTS))

from funnel_coverage import _AUDIT_NAME_RE  # noqa: E402  — see LIBRARY-FIRST above
import canonical_docs  # noqa: E402  — CANONICAL_RETIRED_LOCATIONS, see POOL_ROOT_FILES below

logging.basicConfig(format="%(name)s: %(message)s", level=logging.INFO)
logger = logging.getLogger("consumer-at-landing")

CHECK_NAME = "consumer_at_landing"
AUDITS_RELPATH = "docs/audits"
BASELINE_RELPATH = "ecosystem/audit-consumer-baseline.json"

#: Bumped when the predicate changes. A baseline stamped with a DIFFERENT id is not
#: commensurable with a live measurement, and the ratchet refuses to compare them rather than
#: letting a predicate revision silently rebase the debt (`silent_rule_ratchet` discipline).
#:
#: v1 -> v2 (2026-08-27, terra finding 2): the corpus became RECURSIVE. v1 globbed `*.md` at
#: one level, so an artifact under `docs/audits/<date>-...-launch-contracts/` sat outside BOTH
#: legs -- it could land with no consumer declaration and grow the unconsumed set while the
#: check passed. The bump is this module's own rule applied to itself: a re-measurement nobody
#: reviewed is indistinguishable from a drain, so a corpus change forces a deliberate
#: re-measure-and-re-stamp rather than silently rebasing hundreds of names.
DETECTOR_ID = "consumer-at-landing/v2"

#: New landings only. The row: *"the 290 historical orphans are exempt by date cutoff."*
ARM_DATE = _dt.date(2026, 8, 27)

#: Generated and cites everything by construction — the same exclusion `funnel_coverage`
#: makes, on the 2026-08-17 ledger's own stated precedent.
CORPUS_EXCLUDE: frozenset[str] = frozenset({"README.md"})

#: The governance pool, verbatim from the diagnostic §3: *"any `tasks/` row, any ADR, any
#: `STANDING_RULINGS.md` section, or any protocol document"*, plus the root canonical docs,
#: which it included because *"they are decision-bearing surfaces and excluding them would
#: overstate the orphan count."*
POOL_DIRS: tuple[str, ...] = ("tasks", "docs/decisions", "docs/intake", "protocols")
#: `VISION.md` reads via the registry, not a literal -- [#614] lane-e-5 (2026-09-01) found
#: the literal silently dropped the file from this pool when it relocated to
#: `docs/archive/VISION.md` (`repo_path / "VISION.md"` no longer resolved to a real file).
POOL_ROOT_FILES: tuple[str, ...] = (
    "BACKLOG.md", "ARCHITECTURE.md", "CLAUDE.md", "LESSONS.md",
    canonical_docs.CANONICAL_RETIRED_LOCATIONS[canonical_docs.VISION], "CONTRIBUTING.md")

#: A governance citation, in the four forms the row names (row / ADR / register / intake).
#: `ADR-\d` carries a digit-boundary guard for the same reason the diagnostic's did.
_CITATION_RES: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("a backlog row", re.compile(r"\[#\d+\]")),
    ("an ADR", re.compile(r"\bADR-\d+(?![0-9])")),
    ("the standing-rulings register", re.compile(r"STANDING_RULINGS")),
    ("an intake", re.compile(r"\bintake\s+#\d+", re.I)),
)

#: The explicit escape. `<reason>` runs to end of line.
_NO_CONSUMER_RE = re.compile(r"^\W{0,4}no[- ]consumer\W{0,4}:\s*(?P<reason>.+)$", re.I | re.M)

#: A reason shorter than this is a token, not a reason — the same substance floor
#: `funnel_coverage._REJECTED_MIN_LOCATOR` applies to a REJECTED locator, and the same honest
#: weakness: it separates a recorded reason from a one-word dodge, and nothing more.
NO_CONSUMER_REASON_FLOOR = 24

#: A trailing commission id (`…-wf-50111a08.md`). `docs/archive/README.md` documents the
#: convention precisely so the file resolves back to its source, and the diagnostic verified
#: all four such memos resolve by this token rather than by filename.
_COMMISSION_ID_RE = re.compile(r"-(wf-[0-9a-f]{6,})(?=\.md$)")

#: A dated artifact stem cited WITHOUT its `.md`. Both-sided boundary, for the reason
#: `_AUDIT_NAME_RE` carries one.
_STEM_RE = re.compile(r"(?<![A-Za-z0-9._-])(\d{4}-\d{2}-\d{2}-[A-Za-z0-9._-]+)(?![A-Za-z0-9._-])")

_DATED_NAME_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})-")


class ConsumerScanError(RuntimeError):
    """The corpus itself could not be read. Never raised for a coverage gap — a corpus that
    was not fully read yields no trustworthy number, so it is an error rather than a low one."""


@dataclass(frozen=True)
class Artifact:
    """One landed artifact and what it declares."""
    name: str
    landed: _dt.date | None
    citations: tuple[str, ...]
    no_consumer_reason: str | None

    @property
    def declares_consumer(self) -> bool:
        return bool(self.citations) or self.no_consumer_reason is not None


@dataclass
class Measurement:
    """The whole live picture. Pure data — no filesystem handles."""
    corpus: list[str] = field(default_factory=list)
    artifacts: dict[str, Artifact] = field(default_factory=dict)
    unconsumed: list[str] = field(default_factory=list)
    undatable: list[str] = field(default_factory=list)
    grandfathered: int = 0
    pool_files: int = 0
    pool_unreadable: list[str] = field(default_factory=list)
    pool_resolved: bool = False
    detector_id: str = DETECTOR_ID


def repo_root() -> Path:
    return _SCRIPTS.parent


def identifiers(name: str) -> set[str]:
    """Every token a governance surface might cite this artifact by.

    Filename, bare stem, and any trailing commission id. NOT filename alone — that is the
    keying the diagnostic proved wrong on three of its four false-positive buckets.
    """
    out = {name}
    if name.endswith(".md"):
        out.add(name[:-3])
    match = _COMMISSION_ID_RE.search(name)
    if match:
        out.add(match.group(1))
    return out


#: A launch-contracts directory carries the batch's date on the DIRECTORY, not on the files
#: inside it (PLAYBOOK Ch8, "Where the contract file lives"). Same shape
#: `check_substrate_declaration` reads.
_DATED_DIR_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})-")


def _fallback_date(rel_parents: tuple[str, ...]) -> _dt.date | None:
    """The landing date carried by a containing directory, nearest first.

    Found by dogfooding: making the corpus recursive (terra finding 2) pulled in five nested
    launch contracts whose FILENAMES carry no date, so every one reported "no resolvable
    landing date" -- five permanent WARNs for files whose date is plainly on the directory
    holding them. Reported-rather-than-assumed was the right posture; having nothing else to
    read was the defect.
    """
    for parent in rel_parents:
        match = _DATED_DIR_RE.match(parent)
        if match:
            try:
                return _dt.date.fromisoformat(match.group("date"))
            except ValueError:
                return None
    return None


def read_artifact(name: str, text: str,
                  rel_parents: tuple[str, ...] = ()) -> Artifact:
    """Parse one artifact's own declaration."""
    citations = tuple(label for label, pattern in _CITATION_RES if pattern.search(text))
    reason = None
    for match in _NO_CONSUMER_RE.finditer(text):
        candidate = match.group("reason").strip().rstrip("*`_ ").strip()
        if len(candidate) >= NO_CONSUMER_REASON_FLOOR:
            reason = candidate
            break
    landed = None
    date_match = _DATED_NAME_RE.match(name)
    if date_match:
        try:
            landed = _dt.date.fromisoformat(date_match.group("date"))
        except ValueError:
            landed = None
    if landed is None:
        landed = _fallback_date(rel_parents)
    return Artifact(name=name, landed=landed, citations=citations, no_consumer_reason=reason)


def _pool_paths(repo_path: Path) -> list[Path]:
    """Every governance-pool file that exists. Order is stable for reproducibility."""
    out: list[Path] = []
    for rel in POOL_DIRS:
        directory = repo_path / rel
        if directory.is_dir():
            out.extend(sorted(p for p in directory.rglob("*.md") if p.is_file()))
    for rel in POOL_ROOT_FILES:
        path = repo_path / rel
        if path.is_file():
            out.append(path)
    return out


def cited_identifiers(repo_path: Path) -> tuple[set[str], int]:
    """Every artifact identifier the governance pool names, files read, and files that failed.

    ONE PASS over the pool, extracting identifier TOKENS, rather than one search per artifact:
    the corpus is ~740 files and the pool ~500, so the per-artifact shape would be hundreds of
    thousands of scans on a pre-commit hook. This is linear in pool bytes.

    THE FAILED-READ LIST IS RETURNED, NOT SWALLOWED (terra finding 1). An earlier version
    skipped an unreadable pool file and still reported the pool RESOLVED, so a partial scan
    produced a clean verdict — a check that could not compute its ground truth reporting a
    non-failing status, which is the exact class `[#583]`/`[#596]` sweep for, reached inside
    the module that gates for it. A pool file that cannot be read now makes the pool
    UNRESOLVED and is named in the evidence.
    """
    tokens: set[str] = set()
    unreadable: list[str] = []
    paths = _pool_paths(repo_path)
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            unreadable.append(path.name)
            continue
        tokens.update(m.group(1) for m in _AUDIT_NAME_RE.finditer(text))
        tokens.update(m.group(1) for m in _STEM_RE.finditer(text))
        tokens.update(m.group(1) for m in re.finditer(r"\b(wf-[0-9a-f]{6,})\b", text))
    return tokens, len(paths), unreadable


def measure(repo_root_path: Path) -> Measurement:
    """Walk `docs/audits/`, parse each artifact's declaration, and resolve consumption.

    Raises `ConsumerScanError` only when the corpus itself is unreadable. A corpus with zero
    consumers is a MEASUREMENT, not an error — reporting it is the whole point.
    """
    root = Path(repo_root_path)
    audits_dir = root / AUDITS_RELPATH
    if not audits_dir.is_dir():
        raise ConsumerScanError(f"{AUDITS_RELPATH} is not a directory under {root}")
    try:
        # RECURSIVE (terra finding 2). A one-level glob left every artifact under
        # `docs/audits/<date>-...-launch-contracts/` outside BOTH legs, so a nested landing
        # could omit its declaration and grow the unconsumed set while the check passed.
        # `CORPUS_EXCLUDE` matches by BASENAME, so a generated index at any depth stays out.
        paths = sorted(p for p in audits_dir.rglob("*.md") if p.is_file())
    except OSError as exc:
        raise ConsumerScanError(f"could not list {AUDITS_RELPATH}: {exc!r}") from exc

    m = Measurement()
    for path in paths:
        if path.name in CORPUS_EXCLUDE:
            continue
        try:
            # STRICT decoding, and a decode failure RAISES — the lesson `funnel_coverage`
            # records: an unreadable byte anywhere in the corpus leaves a ratchet passing on a
            # read that partly failed.
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ConsumerScanError(f"could not read {path.name}: {exc!r}") from exc
        except UnicodeDecodeError as exc:
            raise ConsumerScanError(
                f"{path.name} is not valid UTF-8 ({exc}); the corpus was not fully read, so "
                f"no number from this run is trustworthy") from exc
        rel_parents = tuple(
            q.name for q in path.parents if q != audits_dir and audits_dir in q.parents)
        artifact = read_artifact(path.name, text, rel_parents)
        m.corpus.append(path.name)
        m.artifacts[path.name] = artifact
        if artifact.landed is None:
            m.undatable.append(path.name)
        elif artifact.landed < ARM_DATE:
            m.grandfathered += 1

    tokens, pool_files, pool_unreadable = cited_identifiers(root)
    m.pool_files = pool_files
    m.pool_unreadable = pool_unreadable
    m.pool_resolved = pool_files > 0 and not pool_unreadable
    m.unconsumed = sorted(n for n in m.corpus if not (identifiers(n) & tokens))
    return m


def undeclared(m: Measurement) -> list[Artifact]:
    """Artifacts landed on/after `ARM_DATE` that declare no consumer. Leg 1's verdict set."""
    return [a for a in (m.artifacts[n] for n in m.corpus)
            if a.landed is not None and a.landed >= ARM_DATE and not a.declares_consumer]


# --- the committed baseline ------------------------------------------------------------------

def render_baseline(m: Measurement, measured_at: str, measured_at_sha: str,
                    provenance: str) -> str:
    """Render the ratchet baseline as JSON.

    JSON rather than YAML, on `funnel_coverage`'s measured precedent: an `ecosystem/*.yaml`
    enumerating hundreds of audit FILENAMES is inside `silent_rule_detector`'s governed corpus,
    where a slug containing a normative token scores as rule accretion and FAILs an unrelated
    ratchet. `.json` is outside that scope and is the honest shape for a machine-generated,
    machine-read file carrying no doctrine.
    """
    payload = {
        "_": ("Committed baseline for the docs/audits consumer ratchet ([#595]). Regenerate: "
              "python scripts/consumer_at_landing.py --write-baseline. Contract, pool "
              "definition and honest limits: scripts/consumer_at_landing.py (module "
              "docstring)."),
        "detector_id": m.detector_id,
        "measured_at": measured_at,
        "measured_at_sha": measured_at_sha,
        "corpus": len(m.corpus),
        "pool_files": m.pool_files,
        "unconsumed": len(m.unconsumed),
        "provenance": provenance.strip(),
        "artifacts": list(m.unconsumed),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def load_baseline(repo_path: Path) -> dict | None:
    """The committed baseline, or None when absent/unreadable/malformed.

    None is a MEASUREMENT-REFUSING state, not a default: the caller reports an inert ratchet
    rather than treating a missing baseline as an empty one, which would make every
    pre-existing artifact read as a fresh regression. The integrity rules are
    `funnel_coverage.load_baseline`'s, for the reasons recorded there: the declared count has
    to agree with the list it counts (so a hand-appended name takes a deliberate edit to the
    number it contradicts), and duplicates are refused (the ratchet compares SETS, so a
    duplicated name satisfies the count check while disagreeing with the identity set).
    """
    path = Path(repo_path) / BASELINE_RELPATH
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or not isinstance(data.get("artifacts"), list):
        return None
    if not all(isinstance(a, str) for a in data["artifacts"]):
        return None
    if len(set(data["artifacts"])) != len(data["artifacts"]):
        return None
    declared = data.get("unconsumed")
    if not isinstance(declared, int) or isinstance(declared, bool):
        return None
    if declared != len(data["artifacts"]):
        return None
    return data


def ratchet_findings(m: Measurement, baseline: dict | None) -> list[tuple[str, str]]:
    """The verdict as `(status, evidence)` pairs. PURE — no filesystem, no git.

    Tuples rather than `Finding` objects so this module imports nothing from `audit`; the
    adapter maps them. ONE FINDING PER CONCERN, never a bundle: the `#147` register suppresses
    an ENTIRE Finding on a substring match, so a bundled Finding would let one dispositioned
    artifact wave through every regression sharing the line.
    """
    out: list[tuple[str, str]] = []

    # Leg 3 FIRST, because it bounds what every number below means.
    if not m.pool_resolved:
        detail = (f"{len(m.pool_unreadable)} governance-pool file(s) could not be read "
                  f"({', '.join(m.pool_unreadable[:5])})" if m.pool_unreadable
                  else f"the governance pool is empty ({', '.join(POOL_DIRS)})")
        return [("warn",
                 f"citations cannot be resolved: {detail} — reported rather than passed, "
                 f"because a partially-read pool produces the same zero as a fully-cited one")]

    for artifact in undeclared(m):
        out.append(("fail",
                    f"{artifact.name} landed on/after {ARM_DATE.isoformat()} and declares no "
                    f"consumer — cite the governance surface it serves (a [#id] row, an "
                    f"ADR-<n>, a STANDING_RULINGS section, or intake #<n>), or record "
                    f"`no-consumer: <reason>` saying why it has none"))

    for name in m.undatable:
        out.append(("warn",
                    f"{name} carries no resolvable landing date, so it cannot be placed "
                    f"against the {ARM_DATE.isoformat()} cutoff — reported rather than "
                    f"assumed grandfathered"))

    if baseline is None:
        out.append(("warn",
                    f"no readable {BASELINE_RELPATH} — the consumption ratchet is INERT "
                    f"(live unconsumed {len(m.unconsumed)} of {len(m.corpus)}); the gate is "
                    f"not measuring growth"))
        return out

    stamped = baseline.get("detector_id")
    if stamped != m.detector_id:
        out.append(("warn",
                    f"detector mismatch: baseline stamped {stamped!r} but this measurement "
                    f"was produced by {m.detector_id!r} — the two are not commensurable; "
                    f"re-measure and re-stamp rather than comparing them"))
        return out

    for name in sorted(set(m.unconsumed) - set(baseline["artifacts"])):
        out.append(("warn",
                    f"{name} is cited by no governance surface and is not in the arm-time "
                    f"baseline — the unconsumed set grew. Name it from the row, ADR, register "
                    f"entry or intake that consumes it, or record why it has no consumer"))
    return out


# --- CLI -------------------------------------------------------------------------------------

def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Consumer-at-landing gate for docs/audits/ — an artifact declares its "
                    "consumer, and the unconsumed set does not grow ([#595]).")
    parser.add_argument("--repo-root", type=Path, default=repo_root())
    parser.add_argument("--write-baseline", action="store_true",
                        help="regenerate the committed ratchet baseline")
    parser.add_argument("--measured-at", default="", help="ISO date stamped into the baseline")
    parser.add_argument("--sha", default="", help="commit sha stamped into the baseline")
    parser.add_argument("--provenance", default="arm-time measurement",
                        help="one line recording how this baseline was produced")
    args = parser.parse_args(argv)

    try:
        m = measure(args.repo_root)
    except ConsumerScanError as exc:
        logger.error("%s", exc)
        return 2

    if args.write_baseline:
        target = Path(args.repo_root) / BASELINE_RELPATH
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            render_baseline(m, args.measured_at, args.sha, args.provenance),
            encoding="utf-8", newline="\n")
        logger.info("wrote %s — %d unconsumed of %d, pool %d files",
                    target, len(m.unconsumed), len(m.corpus), m.pool_files)
        return 0

    findings = ratchet_findings(m, load_baseline(args.repo_root))
    for status, evidence in findings:
        (logger.error if status == "fail" else logger.warning)("%s", evidence)
    if not findings:
        logger.info("%d artifact(s), %d unconsumed at baseline, %d grandfathered, pool %d "
                    "files — no growth", len(m.corpus), len(m.unconsumed), m.grandfathered,
                    m.pool_files)
    return 1 if any(s == "fail" for s, _ in findings) else 0


if __name__ == "__main__":
    sys.exit(_main())
