"""funnel_coverage.py -- the detector behind the audit funnel-coverage leg (M3).

THE GAP. `protocols/PLAYBOOK.md` Ch8 makes the wave-close funnel table mandatory and ADR-111
governs what a finding may become, but ADR-111's own Consequences paragraph states the honest
limit verbatim: *"No organ checks that an audit's findings are triaged, and none is built
here."* So "no audit is wasted" was an instruction, and an instruction is a request. This
module is the half that makes it a claim a machine can refute.

WHAT IT MEASURES, precisely. For every artifact in `docs/audits/`, whether some **disposition
ledger** in that same directory carries a row naming it with a term from the ruled closed set
AND a non-empty evidence locator. It does NOT measure whether the disposition is correct, and
it cannot -- see HONEST LIMITS at the bottom.

THE VOCABULARY IS RULED, NOT INVENTED. Architect standing ruling of 2026-08-17
(`docs/audits/2026-08-17-technical-batch-7a-lane-a-contract.md:22-27`, committed `875509bd`;
quoted again at the head of `docs/audits/2026-08-17-technical-audit-disposition-ledger.md`):

    Every audit artifact carries exactly one disposition: ACTIONED (conclusion already live --
    cite the commit), FILED (a row owns it -- cite the id), REJECTED (a ruling declined it --
    cite it), SUPERSEDED (a later artifact replaced it -- cite it). An undisposed audit is a
    defect, not a document.

That ruling is ARTIFACT-level, which is this check's unit. ADR-111 §1's four outcomes and
PLAYBOOK Ch8's five classifications are FINDING-level -- a different unit, deliberately not
used here. No fifth vocabulary is introduced.

PENDING IS NOT COVERAGE, AND IT IS NOT ABSENCE EITHER. The same ruling admits PENDING for the
undecidable case (*"a wrong ACTIONED is worse than an honest PENDING"*). A PENDING artifact has
been looked at and its open question recorded; an absent one has not. Collapsing the two would
throw away the only distinction that says whether work was done, so they are counted and
reported separately and only the ABSENT set drives the ratchet.

THE LEDGER SHAPE IS THE ONE ALREADY ON DISK, not a schema this module asks for. A ledger is a
markdown table whose header carries a file-ish column, a `disposition` column and an
`evidence locator` column -- the exact columns the lane-a contract specified at `:87-92`. Any
artifact may carry one, including an artifact dispositioning itself, so a new audit has an
authoring-time discharge path that never requires editing an immutable file (§5 rule 3).

MEASURED DISCRIMINATION, because a predicate nobody measured is a guess. On the 693-artifact
corpus the header predicate admits exactly ONE table. `docs/audits/2026-05-24-dev-knowledge-self-audit.md`
carries a table literally headed "## Disposition ledger" with `File` and `Disposition` columns
and is correctly DECLINED: it predates the ruling, carries no evidence-locator column, and its
vocabulary is `WILL FIX`. One same-named, same-shaped, pre-ruling near-miss admitted 0 rows --
that is the false-admit number, and it is why the locator column is required rather than
optional.

EVERY TABLE, EVERY ROW -- the [#560] lesson, adopted rather than repeated. That row exists
because `review_artifact_coverage` reads only the FIRST Branch/HEAD triple per file, so a real
review in a second triple is invisible to it. This scanner walks every table in a file and
every row in a table; `tests/test_funnel_coverage.py` pins it with a fixture whose SECOND table
carries the only disposition. `[#560]`'s own defect is NOT fixed here -- it is that row's, and
it lives in the collision file this lane may not edit.

ESCAPED PIPES ARE REAL DATA HERE. The live ledger quotes each artifact's final metric line
verbatim, and those quotes contain `\\|`. A naive `split("|")` shredded two ACTIONED rows into
the tokens `SHALL\\` and `\\` during the measurement pass -- a silent two-row undercount that
looked exactly like a clean parse. The cell splitter therefore honours the escape.

READ-ONLY and Layer-2: this module never writes. The baseline file is regenerated by an
explicit `--write-baseline` invocation, never as a side effect of measuring.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# The ruled closed set (2026-08-17). Order is the ruling's own.
DISPOSITION_TERMS: tuple[str, ...] = ("ACTIONED", "FILED", "REJECTED", "SUPERSEDED")
PENDING_TERM = "PENDING"

# Bumped when the predicate changes. A baseline stamped with a DIFFERENT id is not
# commensurable with a live measurement and the ratchet refuses to compare them rather than
# letting a predicate revision silently rebase the debt -- the `silent_rule_ratchet` discipline
# ([#436]), which exists because a re-measurement that nobody reviewed is indistinguishable
# from a drain.
DETECTOR_ID = "funnel-coverage/v1"

# JSON, not YAML, and the reason is a MEASURED false positive in a sibling organ rather than
# a preference. `silent_rule_detector`'s governed corpus is `protocols/*.md`,
# `templates/**/*.{md,tmpl}` and `ecosystem/*.yaml`; this baseline enumerates 613 audit
# FILENAMES, one of which is `2026-07-06-arc5-must-verification.md`. Its slug contains the
# literal token `must`, so as an `ecosystem/*.yaml` file this baseline raises the silent-rule
# pool by +1 and FAILs the `[#436]` ratchet -- a data enumeration scoring as rule accretion,
# which is that detector's own stated residual limit ("occurrences in examples, quotations and
# already-enforced rules still count. This is a proxy").
#
# The lawful alternative is a fourth `EXCLUDED_RELPATHS` member -- the exact class already
# applied to `ecosystem/silent-rule-baseline.yaml` ("would otherwise count its own provenance
# prose, making the metric self-referential") and to `ecosystem/parity-surfaces.yaml`. That
# change is NOT taken here: `silent_rule_detector`'s docstring requires a `DETECTOR_ID` bump on
# ANY contract clause change, which forces a re-measure and re-stamp of another ratchet's
# CURATED baseline while sibling lanes are in flight. That is an operator act, not a lane's.
#
# So the format is the reversible half of the fork, and it is reported rather than quietly
# taken -- see the lane artifact's decisions section. JSON is also the honest shape for this
# file: it is machine-generated and machine-read, carries no doctrine, and needs no comments.
# It keeps the whole detector stdlib, `pyyaml` included.
BASELINE_RELPATH = "ecosystem/audit-funnel-baseline.json"
AUDITS_RELPATH = "docs/audits"

# `docs/audits/README.md` is GENERATED and cites every artifact by construction, so including
# it would make the index disposition itself. Excluded on the 2026-08-17 ledger's own stated
# precedent ("excluding the generated docs/audits/README.md, which cites everything by
# construction"), not by a fresh judgement call.
CORPUS_EXCLUDE: frozenset[str] = frozenset({"README.md"})

# A dated audit filename, with or without a `docs/audits/` prefix and with or without backticks.
_AUDIT_NAME_RE = re.compile(r"(\d{4}-\d{2}-\d{2}-[A-Za-z0-9._-]+?\.md)")

# Header cells that identify the artifact column. `file` is the ruled spelling; the other two
# are admitted so a future ledger that says `artifact` is not silently unread.
_FILE_HEADERS: frozenset[str] = frozenset({"file", "artifact", "audit"})
_DISPOSITION_HEADER = "disposition"
_LOCATOR_HEADER = "evidence locator"


class FunnelCoverageError(RuntimeError):
    """Raised when the corpus itself cannot be read. Never raised for a coverage gap."""


@dataclass(frozen=True)
class LedgerRow:
    """One parsed ledger row. `term` is upper-cased and stripped of bold markers."""
    audit: str
    term: str
    locator: str
    ledger: str


@dataclass
class Measurement:
    """The whole live picture. Pure data -- no filesystem handles, so it pickles and prints."""
    corpus: list[str] = field(default_factory=list)
    ledgers: list[str] = field(default_factory=list)
    dispositioned: dict[str, LedgerRow] = field(default_factory=dict)
    pending: dict[str, LedgerRow] = field(default_factory=dict)
    malformed: list[LedgerRow] = field(default_factory=list)
    dangling: list[LedgerRow] = field(default_factory=list)
    detector_id: str = DETECTOR_ID

    @property
    def uncovered(self) -> list[str]:
        """Artifacts with NO ledger record at all. PENDING is deliberately excluded --
        see the module docstring; a recorded open question is not an unlooked-at file."""
        known = set(self.dispositioned) | set(self.pending)
        return sorted(n for n in self.corpus if n not in known)


def split_cells(line: str) -> list[str] | None:
    """Split one markdown table row into cells, honouring `\\|` escapes.

    Returns None for a line that is not a table row. The escape handling is not decoration:
    the live ledger's verbatim-quote column contains escaped pipes, and ignoring them
    silently truncates real rows (module docstring).
    """
    s = line.strip()
    if not s.startswith("|"):
        return None
    s = s[1:]
    if s.endswith("|") and not s.endswith("\\|"):
        s = s[:-1]
    cells: list[str] = []
    buf: list[str] = []
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == "\\" and i + 1 < len(s) and s[i + 1] == "|":
            buf.append("|")
            i += 2
            continue
        if ch == "|":
            cells.append("".join(buf).strip())
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    cells.append("".join(buf).strip())
    return cells


def _is_separator(cells: list[str]) -> bool:
    """A markdown header separator row (`|---|:--:|`), which carries no data."""
    return bool(cells) and all(c and set(c) <= set("-: ") for c in cells)


def _normalise_term(cell: str) -> str:
    """`**ACTIONED**` / ` actioned ` -> `ACTIONED`. Bold markers are presentation."""
    return cell.strip().strip("*").strip().upper()


def scan_ledger(text: str, source: str) -> list[LedgerRow]:
    """Every ledger row in one document. Walks EVERY table and EVERY row ([#560] lesson).

    A table is a ledger only if its header carries a file-ish column, a `disposition` column
    AND an `evidence locator` column. The locator column is REQUIRED because the ruling makes
    the citation part of the disposition -- a term with nothing to resolve is not one.
    """
    rows: list[LedgerRow] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        header = split_cells(lines[i])
        if header is None or len(header) < 3:
            i += 1
            continue
        lowered = [c.strip().lower() for c in header]
        if (_DISPOSITION_HEADER not in lowered
                or _LOCATOR_HEADER not in lowered
                or not any(c in _FILE_HEADERS for c in lowered)):
            i += 1
            continue
        file_idx = next(k for k, c in enumerate(lowered) if c in _FILE_HEADERS)
        disp_idx = lowered.index(_DISPOSITION_HEADER)
        loc_idx = lowered.index(_LOCATOR_HEADER)
        widest = max(file_idx, disp_idx, loc_idx)

        j = i + 1
        sep = split_cells(lines[j]) if j < len(lines) else None
        if sep is not None and _is_separator(sep):
            j += 1
        while j < len(lines):
            body = split_cells(lines[j])
            if body is None or len(body) <= widest:
                break
            match = _AUDIT_NAME_RE.search(body[file_idx])
            if match:
                rows.append(LedgerRow(audit=match.group(1),
                                      term=_normalise_term(body[disp_idx]),
                                      locator=body[loc_idx].strip(),
                                      ledger=source))
            j += 1
        i = j
    return rows


def measure(repo_root: Path) -> Measurement:
    """Walk `docs/audits/`, parse every ledger, and classify the corpus.

    Raises FunnelCoverageError only when the directory itself is unreadable. A corpus with
    zero dispositions is a MEASUREMENT, not an error -- the whole point is to report it.
    """
    audits_dir = Path(repo_root) / AUDITS_RELPATH
    if not audits_dir.is_dir():
        raise FunnelCoverageError(f"{AUDITS_RELPATH} is not a directory under {repo_root}")

    try:
        paths = sorted(audits_dir.glob("*.md"))
    except OSError as exc:
        raise FunnelCoverageError(f"could not list {AUDITS_RELPATH}: {exc!r}") from exc

    m = Measurement()
    m.corpus = sorted(p.name for p in paths if p.name not in CORPUS_EXCLUDE)
    corpus_set = set(m.corpus)

    for p in paths:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            raise FunnelCoverageError(f"could not read {p.name}: {exc!r}") from exc
        rows = scan_ledger(text, p.name)
        if rows:
            m.ledgers.append(p.name)
        for row in rows:
            if row.audit not in corpus_set:
                # A ledger row naming an artifact that is not on disk. Reported, never
                # silently dropped: it is either a relocation or a typo, and both are the
                # ledger rotting rather than the corpus being covered.
                m.dangling.append(row)
                continue
            if row.term in DISPOSITION_TERMS and row.locator:
                m.dispositioned.setdefault(row.audit, row)
            elif row.term == PENDING_TERM:
                m.pending.setdefault(row.audit, row)
            else:
                # An off-vocabulary term, or a ruled term with an empty locator. Both are
                # NOT coverage -- and both are surfaced, because a malformed row is a
                # ledger defect and looks nothing like an unledgered file.
                m.malformed.append(row)

    m.ledgers.sort()
    return m


def render_baseline(m: Measurement, measured_at: str, measured_at_sha: str,
                    provenance: str) -> str:
    """Render the committed ratchet baseline as JSON.

    THE BASELINE NAMES FILES, NOT A COUNT, and that is the one place this ratchet is
    deliberately stronger than `[#436]`'s. A bare integer baseline is satisfied by
    dispositioning one old artifact while adding one new undispositioned one -- net zero,
    debt unchanged, gate silent. An identity set cannot be gamed that way: the check reports
    `live - baseline`, so a NEW uncovered artifact surfaces BY NAME even while the total
    falls. The silent-rule ratchet could not do this because its metric is an occurrence
    count with no attribution; here the unit is a filename, so the stronger form is free.

    `artifacts` may SHRINK (drain a name by ledgering that artifact) or hold. Adding a name
    is a RAISE -- it excuses an artifact that was skipped -- and it is a curated-baseline
    touch, i.e. an operator decision. HONEST LIMIT, stated rather than left to be found:
    nothing REFUSES a raise. The teeth are the named WARN, the attributable one-line diff,
    and the decision-budget rule -- not a code path. See the lane artifact's sol section.
    """
    payload = {
        "_": ("Committed baseline for the audit funnel-coverage ratchet (M3). Regenerate: "
              "python scripts/funnel_coverage.py --write-baseline. Contract, semantics and "
              "honest limits: scripts/funnel_coverage.py (module docstring + render_baseline)."),
        "detector_id": m.detector_id,
        "measured_at": measured_at,
        "measured_at_sha": measured_at_sha,
        "corpus": len(m.corpus),
        "dispositioned": len(m.dispositioned),
        "pending": len(m.pending),
        "uncovered": len(m.uncovered),
        "provenance": provenance.strip(),
        # The uncovered set enumerated by name -- closure-contract item 1. This IS the
        # enumeration; the lane artifact points here rather than restating 613 filenames in
        # prose (CLAUDE.md Sec.4: cite the surface that computes a roster, do not retype it).
        "artifacts": list(m.uncovered),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def load_baseline(repo_root: Path) -> dict | None:
    """Read the committed baseline, or None when it is absent/unreadable/malformed.

    None is a MEASUREMENT-refusing state, not a default: the caller reports an inert ratchet
    rather than treating a missing baseline as an empty one. An empty baseline would make
    every one of the 613 pre-existing artifacts read as a fresh regression, which is how a
    ratchet turns into noise on its first bad read.
    """
    path = Path(repo_root) / BASELINE_RELPATH
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or not isinstance(data.get("artifacts"), list):
        return None
    if not all(isinstance(a, str) for a in data["artifacts"]):
        return None
    return data


def render_report(m: Measurement) -> str:
    """Human-readable census. Used by `--report` and quoted into the lane artifact."""
    lines = [
        f"detector      {m.detector_id}",
        f"corpus N      {len(m.corpus)}   ({AUDITS_RELPATH}/*.md, excluding "
        f"{', '.join(sorted(CORPUS_EXCLUDE))})",
        f"ledgers       {len(m.ledgers)}   {', '.join(m.ledgers) or '(none)'}",
        f"dispositioned {len(m.dispositioned)}",
        f"pending       {len(m.pending)}",
        f"uncovered     {len(m.uncovered)}",
        f"malformed     {len(m.malformed)}",
        f"dangling      {len(m.dangling)}",
        "",
        "by term:",
    ]
    for term in DISPOSITION_TERMS:
        n = sum(1 for r in m.dispositioned.values() if r.term == term)
        lines.append(f"  {term:<11} {n}")
    return "\n".join(lines)


def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo-root", default=".", help="repository root (default: cwd)")
    ap.add_argument("--report", action="store_true", help="print the census")
    ap.add_argument("--list-uncovered", action="store_true",
                    help="print every uncovered artifact, one per line")
    ap.add_argument("--write-baseline", action="store_true",
                    help=f"regenerate {BASELINE_RELPATH} from the live measurement")
    ap.add_argument("--measured-at", default="", help="date stamp for --write-baseline")
    ap.add_argument("--measured-at-sha", default="", help="sha stamp for --write-baseline")
    ap.add_argument("--provenance-file", default="",
                    help="path to a text file whose contents become the provenance block")
    args = ap.parse_args(argv)
    try:
        m = measure(Path(args.repo_root))
    except FunnelCoverageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.list_uncovered:
        for name in m.uncovered:
            print(name)
        return 0
    if args.write_baseline:
        provenance = (Path(args.provenance_file).read_text(encoding="utf-8")
                      if args.provenance_file else "")
        target = Path(args.repo_root) / BASELINE_RELPATH
        target.write_text(
            render_baseline(m, args.measured_at, args.measured_at_sha, provenance),
            encoding="utf-8", newline="\n")
        print(f"funnel_coverage: wrote {BASELINE_RELPATH} "
              f"({len(m.uncovered)} uncovered of {len(m.corpus)})")
        return 0
    print(render_report(m))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
