#!/usr/bin/env python
"""gen_audit_index.py — generate docs/audits/README.md, a navigation index of the audits.

`docs/audits/**` is the corpus's single largest doc area (~190 dated artifacts); with no index,
finding an audit means an `ls` + guess. This generator enumerates every `docs/audits/*.md`
(date + slug + first-`# `-heading title) into a reverse-chronological index grouped by month —
the §5.5 navigation-overhead trigger, satisfied mechanically. The RETENTION policy (roll-up /
compaction of old audits, and whether to gate this index's freshness) is ADR-class and is
proposed separately ([#212] pairing); this is the index artifact only.

Loose top-level module BY DESIGN (mirrors gen_claude_rosters.py / gen_methodology_roster.py):
no codemap node, no ARCHITECTURE codemap regen on edit. Deterministic: same inputs -> byte-
identical output. Layer-2 read-only (ADR-28/36): writes NOTHING except the index target under
--write. The target README is itself EXCLUDED from the scan (an index never indexes itself).
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_AUDITS_DIR = _REPO_ROOT / "docs" / "audits"
_TARGET = _AUDITS_DIR / "README.md"

_GENERATED_NOTE = "<!-- generated by gen_audit_index.py; do not edit by hand -->"
_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+)$")
_TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


def _title_of(path: Path) -> str:
    """First `# ` heading in the file, or a loud placeholder (never silently blank)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "(unreadable)"
    m = _TITLE_RE.search(text)
    return m.group(1).replace("|", "/") if m else "(no # title)"


def collect_audits(audits_dir: Path | None = None) -> list[tuple[str, str, str, str]]:
    """[(date, slug, filename, title), ...] for every docs/audits/*.md except the index itself.

    `date`/`slug` parse from the `YYYY-MM-DD-slug.md` convention; a file not matching it gets
    date="" (sorted last under an 'Undated' group, never dropped). Sorted newest-first, then by
    filename descending for a stable within-day order. `audits_dir` resolves to the module
    `_AUDITS_DIR` at CALL time when None (so a monkeypatched global is honored).
    """
    audits_dir = audits_dir if audits_dir is not None else _AUDITS_DIR
    rows: list[tuple[str, str, str, str]] = []
    for p in audits_dir.glob("*.md"):
        if p.name == "README.md":
            continue
        m = _DATE_RE.match(p.stem)
        date, slug = (m.group(1), m.group(2)) if m else ("", p.stem)
        rows.append((date, slug, p.name, _title_of(p)))
    rows.sort(key=lambda r: (r[0], r[2]), reverse=True)
    return rows


def render_index(audits_dir: Path | None = None) -> str:
    rows = collect_audits(audits_dir)  # None -> collect_audits resolves _AUDITS_DIR at call time
    out = [
        "# Audits index — generated navigation map of `docs/audits/`",
        "",
        "> Mechanical reverse-chronological index of every `docs/audits/*.md` (date · slug ·",
        "> title), grouped by month. The §5.5 navigation-overhead trigger, satisfied by",
        "> generation. Retention/roll-up policy is proposed separately ([#212]).",
        "> Do not hand-edit. Regenerate: `python scripts/gen_audit_index.py --write`",
        "",
        _GENERATED_NOTE,
        "",
        f"**{len(rows)} audit documents.**",
        "",
    ]
    current_month = object()  # sentinel so a real "" month still emits a header once
    for date, slug, filename, title in rows:
        month = date[:7] if date else "Undated"
        if month != current_month:
            current_month = month
            out += ["", f"## {month}", ""]
        label = date if date else slug
        out.append(f"- [{label}]({filename}) — {title}")
    return "\n".join(out) + "\n"


def _cmd_write() -> int:
    _TARGET.write_text(render_index(), encoding="utf-8")
    print(f"gen_audit_index: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check. Exit 0 clean / 1 drift (+diff) / 2 target missing."""
    rel = _TARGET.relative_to(_REPO_ROOT)
    if not _TARGET.exists():
        print(f"error: {rel} not found — generate it: "
              f"python scripts/gen_audit_index.py --write", file=sys.stderr)
        return 2
    fresh = render_index()
    current = _TARGET.read_text(encoding="utf-8")
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile="README.md (current)", tofile="README.md (fresh)"))
    print(diff, file=sys.stderr)
    print(f"gen_audit_index: {rel} is stale vs docs/audits/ — regenerate: "
          f"python scripts/gen_audit_index.py --write", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_audit_index",
        description="Generate/check docs/audits/README.md (the audits navigation index)")
    parser.add_argument("--write", action="store_true", help="regenerate the index from disk")
    parser.add_argument("--check", action="store_true",
                        help="check the index against disk state (default action)")
    args = parser.parse_args(argv)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
