#!/usr/bin/env python
"""gen_intake_index.py -- generate the status-grouped Contents index in docs/intake/README.md (#307).

CONSUMED/REJECTED intake docs accumulate with no archival path; moving them would break the
intake-id join key consuming ADRs/epics cite (ADR-98 section 3) and a new subfolder hits ADR-101
section 1's top-level seal. Ruling (verdict sheet M4, option iii): status-line-only + NEVER move;
navigation via a generated index grouping by lifecycle state, derived on-edit from each doc's
frontmatter `status:` (no sweep), mirroring gen_audit_index.py. This generator MOVES NO FILE -- it
only splices a marker-bounded Contents block into the hand-authored docs/intake/README.md (the
doctrine sections 1-9 are preserved; only the block between the INTAKE-INDEX markers is rewritten).

Loose top-level module BY DESIGN (mirrors gen_audit_index.py / gen_doc_counts.py): no codemap node,
so editing it never forces an ARCHITECTURE codemap regen. Deterministic: same inputs -> byte-
identical output. Layer-2 read-only (ADR-28/36): writes NOTHING except the single README target
under --write.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_INTAKE_DIR = _REPO_ROOT / "docs" / "intake"
_TARGET = _INTAKE_DIR / "README.md"

_START_MARKER = "<!-- INTAKE-INDEX:START -->"
_END_MARKER = "<!-- INTAKE-INDEX:END -->"
_GENERATED_NOTE = "<!-- generated by gen_intake_index.py; do not edit by hand -->"

# The ADR-98 section 5 lifecycle order. A status outside this canon is NOT dropped -- it lands
# in a loud trailing "OTHER" group so a typo/new-state surfaces instead of vanishing.
_STATUS_ORDER = ("SEED", "DRAFT", "READY-FOR-TECHNICAL", "CONSUMED", "REJECTED")
_OTHER = "OTHER"

_TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
_FM_KV_RE = re.compile(r"^([a-z0-9-]+):\s*(.*?)\s*$", re.IGNORECASE)


def _parse_frontmatter(text: str) -> dict[str, str]:
    """The leading `---`...`---` YAML frontmatter as a flat {key: value} dict, or {} if absent.
    Minimal stdlib parse (no yaml dep -- mirrors gen_audit_index's zero-dep posture)."""
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    fm: dict[str, str] = {}
    closed = False
    for line in lines[1:]:
        if line.strip() == "---":
            closed = True
            break
        m = _FM_KV_RE.match(line)
        if m:
            fm[m.group(1).lower()] = m.group(2)
    # Unterminated frontmatter (no closing `---`) is INVALID -> return empty so the doc
    # surfaces loudly in OTHER with a MISSING-ID label, rather than being silently
    # mis-parsed from body lines that happen to match `status:` (codex-review 2026-07-11).
    return fm if closed else {}


def _title_of(text: str) -> str:
    m = _TITLE_RE.search(text)
    return m.group(1).replace("|", "/") if m else "(no # title)"


def collect_intakes(intake_dir: Path | None = None) -> list[tuple[str, str, str, str]]:
    """[(status, intake_id, filename, title), ...] for every docs/intake/*.md except README.

    `status` is the frontmatter `status:` bare word (uppercased), or "" (-> OTHER group).
    `intake_id` is the frontmatter `intake-id:` value, or "" when absent. Read-only; resolves
    `_INTAKE_DIR` at CALL time when None (so a monkeypatched global is honored)."""
    intake_dir = intake_dir if intake_dir is not None else _INTAKE_DIR
    rows: list[tuple[str, str, str, str]] = []
    for p in sorted(intake_dir.glob("*.md")):
        if p.name == "README.md":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            rows.append(("", "", p.name, "(unreadable)"))
            continue
        fm = _parse_frontmatter(text)
        status = (fm.get("status", "") or "").strip().upper()
        intake_id = (fm.get("intake-id", "") or "").strip()
        rows.append((status, intake_id, p.name, _title_of(text)))
    return rows


def _group(rows: list[tuple[str, str, str, str]]) -> dict[str, list[tuple[str, str, str, str]]]:
    groups: dict[str, list] = {}
    for row in rows:
        status = row[0] if row[0] in _STATUS_ORDER else _OTHER
        groups.setdefault(status, []).append(row)
    # Stable within-group order: by intake-id numeric when present, else filename.
    for g in groups.values():
        g.sort(key=lambda r: (int(r[1]) if r[1].isdigit() else 10**9, r[2]))
    return groups


def render_contents(intake_dir: Path | None = None) -> str:
    """The marker-block BODY (between START/END markers), ending with a newline."""
    rows = collect_intakes(intake_dir)
    groups = _group(rows)
    out = [_GENERATED_NOTE, "", f"**{len(rows)} intake documents.**"]
    for status in (*_STATUS_ORDER, _OTHER):
        g = groups.get(status)
        if not g:
            continue
        out += ["", f"### {status} ({len(g)})", ""]
        for _status, intake_id, filename, title in g:
            # A blank/missing intake-id is a schema break -> flag it LOUDLY; never render a
            # date fragment as a pseudo-id (which would read as `[2026]`, codex-review 2026-07-11).
            label = f"#{intake_id}" if intake_id else "MISSING-ID"
            out.append(f"- [{label}]({filename}) — {title}")
    return "\n".join(out) + "\n"


def _splice(content: str, block: str) -> str:
    # Require EXACTLY one START and one END with START before END. Reversed or duplicated
    # markers would let --write rewrite OUTSIDE the generated block and corrupt hand-authored
    # doctrine -- the one thing this splice must never do (codex-review 2026-07-11).
    if content.count(_START_MARKER) != 1 or content.count(_END_MARKER) != 1:
        raise RuntimeError(
            f"INTAKE-INDEX markers must appear EXACTLY once each in {_TARGET.name} -- add the "
            f"{_START_MARKER} / {_END_MARKER} pair once, then regenerate")
    start_idx = content.find(_START_MARKER)
    end_idx = content.find(_END_MARKER)
    if start_idx > end_idx:
        raise RuntimeError(
            f"INTAKE-INDEX START marker must precede END in {_TARGET.name}")
    return content[: start_idx + len(_START_MARKER)] + "\n" + block + content[end_idx:]


def _cmd_write() -> int:
    if not _TARGET.exists():
        print(f"error: {_TARGET} not found", file=sys.stderr)
        return 2
    new_content = _splice(_TARGET.read_text(encoding="utf-8"), render_contents())
    _TARGET.write_text(new_content, encoding="utf-8")
    print(f"gen_intake_index: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check. Exit 0 clean / 1 drift (+diff) / 2 target/markers missing."""
    rel = _TARGET.relative_to(_REPO_ROOT)
    if not _TARGET.exists():
        print(f"error: {rel} not found -- generate it: "
              f"python scripts/gen_intake_index.py --write", file=sys.stderr)
        return 2
    current = _TARGET.read_text(encoding="utf-8")
    try:
        fresh = _splice(current, render_contents())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile="README.md (current)", tofile="README.md (fresh)"))
    print(diff, file=sys.stderr)
    print(f"gen_intake_index: {rel} Contents block is stale vs docs/intake/ -- regenerate: "
          f"python scripts/gen_intake_index.py --write", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_intake_index",
        description="Generate/check the status-grouped Contents index in docs/intake/README.md")
    parser.add_argument("--write", action="store_true",
                        help="regenerate the Contents block in the README from disk")
    parser.add_argument("--check", action="store_true",
                        help="check the Contents block against disk state (default action)")
    args = parser.parse_args(argv)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
