#!/usr/bin/env python
"""gen_doc_counts.py — generate ecosystem/doc-counts.md (the #222 decoupled counts locus).

Moves ARCHITECTURE.md's three volatile count claims (audit check-count, pre-commit
gate-count, pytest collected) OUT of the freshness-gated file into a committed-generated
fragment that is NOT in `audit.py` `_FRESHNESS_FILES`. A count bump then touches only this
file, so `canonical_freshness` A2 (which keys off ARCHITECTURE.md's whole-file git-commit
date) is no longer tripped into forcing a `last_reviewed` re-stamp with no genuine re-read
(the 2026-07-01 forced-false-stamp failure; JOURNAL cadf53d). #222.

Loose top-level script BY DESIGN: the codemap enumerates only `scripts/<pkg>/` dirs with
`__init__.py` (`scripts/codemap/ast_walker.py`), so a loose module adds no codemap node and
editing it never forces an ARCHITECTURE.md codemap regen. Do NOT convert to a package — that
would re-couple this tool's edits to the freshness gate through the codemap hook.

Reuses the #89 derivers (`validate_doc_claims._CLAIMS`) — no re-derivation, single source of
truth for the numbers. The output-line TEMPLATES live here (the generator's format job) and
must embed the exact literal each matching `_CLAIMS` regex expects; a drift between the two
surfaces as a `doc_claims` `anchor-missing` WARN at ship-gate (self-detecting).

Layer-2 / read-only contract (ADR-28/36): reads repo state; writes NOTHING except the single
committed-generated target (ADR-80/86 committed-generated-zone precedent). `audit.py` itself
gains no write path.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Dual-import shape (mirrors audit.py's _vgb/_vdc imports): works whether invoked as
# `python scripts/gen_doc_counts.py` (scripts/ on sys.path) or `python -m scripts.gen_doc_counts`.
try:  # pragma: no cover - import-path shim
    from scripts import audit as _audit
    from scripts import validate_doc_claims as _vdc
except ImportError:  # pragma: no cover - import-path shim
    import audit as _audit
    import validate_doc_claims as _vdc

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_TARGET = _REPO_ROOT / "ecosystem" / "doc-counts.md"

_START_MARKER = "<!-- COUNTS:START -->"
_END_MARKER = "<!-- COUNTS:END -->"

# The three count claims this file owns (the CLAUDE.md §9 `precommit_hook_roster` set-claim
# stays on CLAUDE.md — not moved). Order defines the rendered line order.
_COUNT_CLAIM_NAMES = ("audit_check_count", "precommit_hook_count", "pytest_collected")

# claim-name -> output line template. The literal inside MUST match the corresponding
# `_CLAIMS` regex in validate_doc_claims.py (audit_check_count / precommit_hook_count /
# pytest_collected). Coupling is intentional + self-detecting (anchor-missing WARN on drift).
_TEMPLATES = {
    "audit_check_count": "- audit: **{} registered checks** (`python scripts/audit.py checks`)",
    "precommit_hook_count": "- pre-commit gates ({}) (`.pre-commit-config.yaml`)",
    "pytest_collected": "- tests: **{} collected** (`pytest --collect-only`)",
}

_GENERATED_NOTE = "<!-- generated by gen_doc_counts.py; do not edit by hand -->"


def _count_claims() -> list:
    """The three count Claims from the live registry (with their now-repointed `doc`)."""
    return [c for c in _vdc._CLAIMS if c.name in _COUNT_CLAIM_NAMES]


def _derive_values(run_expensive: bool) -> dict:
    """Fresh ground-truth values via the #89 derivers. pytest (expensive) → None when
    run_expensive is False or collection fails; the caller then reuses the file's value."""
    n = len(_audit.ALL_CHECKS)
    vals: dict = {}
    for c in _count_claims():
        if c.expensive and not run_expensive:
            vals[c.name] = None
        else:
            vals[c.name] = c.deriver(_REPO_ROOT, n)
    return vals


def _current_file_values() -> dict:
    """Values currently parsed out of the target file (via the _CLAIMS regexes), or {} if
    the file/anchors are absent. Used to preserve the expensive pytest line when a fresh
    derivation is unavailable (off-gate / pytest hiccup) rather than clobbering it."""
    if not _TARGET.exists():
        return {}
    text = _TARGET.read_text(encoding="utf-8")
    out: dict = {}
    for c in _count_claims():
        if c.anchor is None:
            continue
        m = c.anchor.search(text)
        if m:
            out[c.name] = int(m.group(1))
    return out


def _render_block(run_expensive: bool) -> str:
    """The marker-block body (between START/END), ending with a newline."""
    fresh = _derive_values(run_expensive)
    prior = _current_file_values()
    lines = [_GENERATED_NOTE]
    for name in _COUNT_CLAIM_NAMES:
        val = fresh.get(name)
        if val is None:  # expensive value unavailable — preserve the file's current one
            val = prior.get(name)
        if val is None:
            raise RuntimeError(
                f"cannot derive '{name}' and no prior value in {_TARGET.name} to preserve; "
                f"run with a working pytest (or generate the file's initial value first)")
        lines.append(_TEMPLATES[name].format(val))
    return "\n".join(lines) + "\n"


def _splice(content: str, block: str) -> str:
    start_idx = content.find(_START_MARKER)
    end_idx = content.find(_END_MARKER)
    if start_idx == -1 or end_idx == -1:
        raise RuntimeError(f"COUNTS markers not found in {_TARGET}")
    return (content[: start_idx + len(_START_MARKER)] + "\n" + block + content[end_idx:])


def _cmd_write(run_expensive: bool) -> int:
    if not _TARGET.exists():
        print(f"error: {_TARGET} not found (create the scaffold with markers first)",
              file=sys.stderr)
        return 2
    block = _render_block(run_expensive)
    new_content = _splice(_TARGET.read_text(encoding="utf-8"), block)
    _TARGET.write_text(new_content, encoding="utf-8", newline="\n")
    print(f"gen_doc_counts: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check(gate: bool) -> int:
    """Reconcile the file's count claims against fresh ground truth (reusing #89 reconcile).
    `--gate` skips the expensive pytest claim so pre-ship/commit checks stay fast. Exit 1 on
    any drift or anchor-missing (mirrors toc/codemap check semantics)."""
    results = _vdc.reconcile(_REPO_ROOT, len(_audit.ALL_CHECKS),
                             run_expensive=not gate, claims=_count_claims())
    bad = [r for r in results if r.status in ("mismatch", "anchor-missing")]
    for r in results:
        print(f"  {r.status:>14}  {r.name} (file {r.claimed or '-'} / actual {r.actual})")
    if bad:
        print(f"gen_doc_counts: {len(bad)} count claim(s) stale in "
              f"{_TARGET.relative_to(_REPO_ROOT)} — regenerate: "
              f"python scripts/gen_doc_counts.py --write", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="gen_doc_counts",
        description="Generate/check ecosystem/doc-counts.md (the #222 decoupled count claims)")
    parser.add_argument("--write", action="store_true",
                        help="regenerate the count block in the file (runs pytest)")
    parser.add_argument("--check", action="store_true",
                        help="check the file's counts against repo state (default action)")
    parser.add_argument("--gate", action="store_true",
                        help="with --check: skip the expensive pytest claim (fast)")
    args = parser.parse_args()
    if args.write:
        return _cmd_write(run_expensive=True)
    return _cmd_check(gate=args.gate)


if __name__ == "__main__":
    sys.exit(main())
