#!/usr/bin/env python
"""gen_claude_rosters.py — generate CLAUDE.md's derivable list fragments ([#258] S3, phase 1).

Phase 1 of the Tier-3 CLAUDE.md-generability plan (docs/audits/
2026-07-05-draft-tier3-claudemd-generability.md), scoped to the two hand-synced lists the
epic contract names: the repo-local COMMAND list (CLAUDE.md §7) and the recent-ADR list
(CLAUDE.md §11). Each is generated into a fragment under `.claude/generated/` and
`@`-imported from CLAUDE.md — the [#244] roster seam, extended to disk-derived surfaces.
CLAUDE.md's hand-prose (doctrine, pointers, §12 history) stays hand-authored and IN the
`canonical_freshness` gate; these fragments are OUT of `DEFAULT_FRESHNESS_FILES` (currency =
regeneration, the #222 decouple precedent).

DELIBERATELY NOT GENERATED (phase-1 boundary, recorded in the epic return):
- §9 pre-commit hook list — `validate_doc_claims.extract_claimed_hooks` window-anchors it in
  CLAUDE.md's raw text (an @import would void that check leg; retiring a gate leg needs its
  own arc + ADR note per the Tier-3 draft, migration risk 3).
- §8 skills — the enumeration is interwoven with archival doctrine prose, not a bare list.

Source-of-truth split (do NOT merge with gen_methodology_roster.py): that generator renders
the MANIFEST-declared deployable corpus; this one enumerates LOCAL DISK state
(`.claude/commands/*.md` frontmatter; `docs/decisions/ADR-*.md` headers). Different truths,
different files. The commands fragment lists every command file on disk — including any that
also appear in the deployed-corpus roster (disk truth is the point; the §7 prose says so).

Loose top-level module BY DESIGN (mirrors gen_methodology_roster.py): no codemap node, no
ARCHITECTURE codemap regen on edit. Do NOT convert to a package.

Deterministic: same inputs -> byte-identical output. Layer-2 read-only (ADR-28/36): writes
NOTHING except the two generated targets (under --write).
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_COMMANDS_DIR = _REPO_ROOT / ".claude" / "commands"
_DECISIONS_DIR = _REPO_ROOT / "docs" / "decisions"
_GENERATED_DIR = _REPO_ROOT / ".claude" / "generated"
_COMMANDS_TARGET = _GENERATED_DIR / "commands-repo.md"
_ADRS_TARGET = _GENERATED_DIR / "recent-adrs.md"

_GENERATED_NOTE = "<!-- generated by gen_claude_rosters.py; do not edit by hand -->"
_RECENT_ADR_COUNT = 5

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_ADR_FILE_RE = re.compile(r"^ADR-(\d+)-[\w.-]+\.md$")
_ADR_TITLE_RE = re.compile(r"^#\s+ADR-\d+:\s*(.+?)\s*$", re.MULTILINE)
# Both header dialects: `- **Status:** X` (list form, e.g. ADR-97) and `**Status:** X`
# (bare form, e.g. ADR-93). A trailing parenthetical/dash qualifier is trimmed to the bare
# status word(s) — the qualifier is decision prose, not list material.
_ADR_STATUS_RE = re.compile(r"^(?:-\s+)?\*\*Status:\*\*\s*(.+?)\s*$", re.MULTILINE)
_ADR_DATE_RE = re.compile(r"^(?:-\s+)?\*\*Date:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})", re.MULTILINE)


def _frontmatter_field(text: str, field: str) -> str | None:
    """A top-level `field: value` line from a leading YAML frontmatter block, or None.

    Deliberately regex-simple (single-line scalars only) — command frontmatter here is flat;
    no yaml dependency for two fields.
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    for line in m.group(1).splitlines():
        if line.startswith(f"{field}:"):
            return line[len(field) + 1:].strip() or None
    return None


def collect_commands(commands_dir: Path = _COMMANDS_DIR) -> list[tuple[str, str]]:
    """[(name, description), ...] for every `.claude/commands/*.md`, filename-sorted.

    Name = frontmatter `name:` if present, else the filename stem. Description = frontmatter
    `description:`, else a loud placeholder (a missing description should be visible, not
    silently dropped).
    """
    rows: list[tuple[str, str]] = []
    for p in sorted(commands_dir.glob("*.md")):
        text = p.read_text(encoding="utf-8")
        name = _frontmatter_field(text, "name") or p.stem
        desc = _frontmatter_field(text, "description") or "(no description frontmatter)"
        rows.append((name, desc))
    return rows


def collect_recent_adrs(decisions_dir: Path = _DECISIONS_DIR,
                        count: int = _RECENT_ADR_COUNT) -> list[tuple[int, str, str, str]]:
    """[(number, status, date, title), ...] for the last `count` ADRs by number, ascending.

    Header fields parsed from each ADR file (`# ADR-NN: Title` + `- **Status:**` +
    `- **Date:**`); a missing field renders as a loud `(unparsed)` rather than dropping
    the ADR (mechanical honesty over silent omission).
    """
    numbered: list[tuple[int, Path]] = []
    for p in decisions_dir.glob("ADR-*.md"):
        m = _ADR_FILE_RE.match(p.name)
        if m:
            numbered.append((int(m.group(1)), p))
    numbered.sort()
    rows: list[tuple[int, str, str, str]] = []
    for num, p in numbered[-count:]:
        text = p.read_text(encoding="utf-8")
        title_m = _ADR_TITLE_RE.search(text)
        title = title_m.group(1) if title_m else "(unparsed)"
        status_m = _ADR_STATUS_RE.search(text)
        date_m = _ADR_DATE_RE.search(text)
        status = status_m.group(1) if status_m else "(unparsed)"
        status = re.split(r"\s*[(—]", status, maxsplit=1)[0].strip() or "(unparsed)"
        date = date_m.group(1) if date_m else "(unparsed)"
        rows.append((num, status, date, title))
    return rows


def render_commands(commands_dir: Path = _COMMANDS_DIR) -> str:
    out = [
        "# Repo-level commands — generated from `.claude/commands/*.md` frontmatter",
        "",
        "> Disk enumeration of this repo's command files (name + description). Commands that",
        "> are also part of the deployed methodology corpus appear in the §9 roster too — that",
        "> file renders the manifest declaration; this one renders local disk truth.",
        "> Do not hand-edit. Regenerate: `python scripts/gen_claude_rosters.py --write`",
        "",
        _GENERATED_NOTE,
        "",
    ]
    out += [f"- `/{name}` — {desc}" for name, desc in collect_commands(commands_dir)]
    return "\n".join(out) + "\n"


def render_adrs(decisions_dir: Path = _DECISIONS_DIR) -> str:
    out = [
        f"# Recent ADRs (last {_RECENT_ADR_COUNT} by number) — generated from "
        "`docs/decisions/ADR-*.md` headers",
        "",
        "> Mechanical list (number - status - date - title). The editorial one-liners live in",
        "> `docs/decisions/README.md`; the decision content lives in each ADR.",
        "> Do not hand-edit. Regenerate: `python scripts/gen_claude_rosters.py --write`",
        "",
        _GENERATED_NOTE,
        "",
    ]
    out += [f"- ADR-{num} ({status}, {date}): {title}"
            for num, status, date, title in collect_recent_adrs(decisions_dir)]
    return "\n".join(out) + "\n"


_TARGETS: list[tuple[Path, "callable"]] = [
    (_COMMANDS_TARGET, render_commands),
    (_ADRS_TARGET, render_adrs),
]


def _cmd_write() -> int:
    _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for target, renderer in _TARGETS:
        target.write_text(renderer(), encoding="utf-8", newline="\n")
        print(f"gen_claude_rosters: wrote {target.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check across both fragments. Exit 0 clean / 1 drift (+diff) /
    2 a target missing — mirrors gen_methodology_roster.py semantics."""
    worst = 0
    for target, renderer in _TARGETS:
        rel = target.relative_to(_REPO_ROOT)
        if not target.exists():
            print(f"error: {rel} not found — generate it: "
                  f"python scripts/gen_claude_rosters.py --write", file=sys.stderr)
            worst = max(worst, 2)
            continue
        fresh = renderer()
        current = target.read_text(encoding="utf-8")
        if current == fresh:
            continue
        diff = "".join(difflib.unified_diff(
            current.splitlines(keepends=True), fresh.splitlines(keepends=True),
            fromfile=f"{target.name} (current)", tofile=f"{target.name} (fresh)"))
        print(diff, file=sys.stderr)
        print(f"gen_claude_rosters: {rel} is stale vs disk state — regenerate: "
              f"python scripts/gen_claude_rosters.py --write", file=sys.stderr)
        worst = max(worst, 1)
    return worst


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_claude_rosters",
        description="Generate/check CLAUDE.md's derivable fragments (.claude/generated/)")
    parser.add_argument("--write", action="store_true",
                        help="regenerate both fragments from disk state")
    parser.add_argument("--check", action="store_true",
                        help="check the fragments against disk state (default action)")
    args = parser.parse_args(argv)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
