#!/usr/bin/env python
"""gen_audit_index.py — generate docs/audits/README.md, a navigation index of the audits.

`docs/audits/**` is the corpus's single largest doc area (~190 dated artifacts); with no index,
finding an audit means an `ls` + guess. This generator enumerates every `docs/audits/*.md`
(date + slug + first-`# `-heading title) into a reverse-chronological index grouped by month —
the §5.5 navigation-overhead trigger, satisfied mechanically. The RETENTION policy is **ruled**:
ADR-100 (`docs/decisions/ADR-100-audit-retention-index-rule.md`) decided keep-all-accepted, and
folded and closed `[#212]` in doing so. ADR-100 ALSO names a count-tiered index shape, which is
**not built here** — this module still groups by month, and the tiering plus its freshness hook
are `[#269]`. The header says so rather than advertising a shape this code does not emit.

Loose top-level module BY DESIGN (mirrors gen_claude_rosters.py / gen_methodology_roster.py):
no codemap node, no ARCHITECTURE codemap regen on edit. Layer-2 read-only (ADR-28/36): writes
NOTHING except the index target under --write. The target README is itself EXCLUDED from the
scan (an index never indexes itself).

TRACKED FILES ONLY, and this is the determinism boundary. `collect_audits` globs the working
tree, so an UNTRACKED `docs/audits/2026-01-01-technical-scratch.md` used to render a row: the
generated bytes depended on one machine's private files and `--check` would red on every other
checkout of the same commit, making the freshness gate unholdable anywhere but the machine that
last regenerated. This is the SAME defect terra finding F1 found in `generate_organ_index.py`,
fixed there at `d5b19a2d`; the fix here is that fix, applied to its twin. It was not theoretical
in this module either -- the 2026-08-12 night-1 lane hit exactly this shape (a concurrent lane's
untracked audit in the shared working tree would have entered the index) and declared
`SKIP=audit-index-freshness` rather than commit a wrong index.

HONEST LIMIT, stated in `tracked_files`: outside a git work tree there is no tracked set, so
filtering is DISABLED rather than emptying the index -- the synthetic trees the tests build are
not repos, and returning nothing outside a checkout is a worse failure than the one prevented.

Deterministic: same COMMITTED inputs -> byte-identical output, asserted rather than claimed by
`test_an_untracked_audit_file_does_not_change_the_generated_bytes` (a real git repo).
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import subprocess
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_AUDITS_DIR = _REPO_ROOT / "docs" / "audits"
_TARGET = _AUDITS_DIR / "README.md"

_GENERATED_NOTE = "<!-- generated by gen_audit_index.py; do not edit by hand -->"

#: The placeholder `_title_of` returns for a file with no `# ` heading. Read by the title gate
#: below rather than re-derived, so the gate and the rendered row can never disagree about what
#: "title-less" means.
NO_TITLE = "(no # title)"

#: The committed measurement of which audits are title-less TODAY. JSON, not YAML, and that is
#: deliberate: `ecosystem/*.yaml` is inside the silent-rule detector's scope, so a baseline
#: written there would put its own explanatory comments into a normative-prose budget. The two
#: sibling baselines (`audit-consumer-baseline.json`, `audit-funnel-baseline.json`) are JSON for
#: their own reasons and this one matches them.
_TITLE_BASELINE_PATH = _REPO_ROOT / "ecosystem" / "audit-title-baseline.json"
_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+)$")
_TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


_AUTO = object()   # "resolve the tracked set yourself" sentinel for collect_audits()


def tracked_files(root: Path) -> frozenset[str] | None:
    """Repo-relative POSIX paths git TRACKS, or None when `root` is not a git work tree.

    THE DETERMINISM BOUNDARY (see the module header). None means "cannot tell" and disables
    filtering rather than emptying the index. Mirrors `generate_organ_index.tracked_files`
    deliberately -- the same defect deserves the same shape, not a second dialect.
    """
    try:
        out = subprocess.run(["git", "-C", str(root), "ls-files", "-z"],
                             capture_output=True, text=True, encoding="utf-8", timeout=30)
    except (OSError, subprocess.SubprocessError):
        # SubprocessError covers TimeoutExpired: this runs inside a pre-commit gate, and an
        # unbounded wait on a stalled git would hang the commit rather than fail it. Every
        # failure mode lands on the same fail-open answer (terra review 2026-08-12,
        # finding 2).
        return None
    if out.returncode != 0:
        return None
    return frozenset(p.replace("\\", "/") for p in out.stdout.split("\0") if p)


def _is_tracked(path: Path, root: Path, tracked: frozenset[str] | None) -> bool:
    """True when filtering is off (tracked is None) or `path` is in the tracked set.

    The repo-relative name is derived LEXICALLY -- the PARENT is resolved, the entry keeps
    its own name -- and that is load-bearing, not a style choice. Resolving the candidate
    followed a SYMLINK: an untracked `docs/audits/2026-02-02-scratch.md` pointing outside
    the repo resolved out of `root`, hit the ValueError branch below, and was INCLUDED, so
    the generated bytes depended on local scratch state again and the freshness gate could
    red on another checkout -- the exact defect the tracked-files filter exists to prevent,
    walking back in through the one door left open. Found by the terra review of
    2026-08-12 (finding 1) and REPRODUCED on a real repo before being accepted.

    The ValueError branch is retained and still INCLUDES, but it now means only what it
    says: the audits directory itself lies outside `root` (a synthetic/monkeypatched
    setup). Dropping a file the rule cannot judge would be the silent-shortening failure
    this filter exists to prevent, not a fix for it.
    """
    if tracked is None:
        return True
    try:
        rel = (path.parent.resolve() / path.name).relative_to(root.resolve()).as_posix()
    except ValueError:
        return True          # the DIRECTORY is outside the root -> not ours to judge
    return rel in tracked


def _title_of(path: Path) -> str:
    """First `# ` heading in the file, or a loud placeholder (never silently blank)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "(unreadable)"
    m = _TITLE_RE.search(text)
    return m.group(1).replace("|", "/") if m else "(no # title)"


def collect_audits(audits_dir: Path | None = None,
                   tracked: frozenset[str] | None | object = _AUTO,
                   root: Path | None = None,
                   ) -> list[tuple[str, str, str, str]]:
    """[(date, slug, filename, title), ...] for every TRACKED docs/audits/*.md except the index.

    `date`/`slug` parse from the `YYYY-MM-DD-slug.md` convention; a file not matching it gets
    date="" (sorted last under an 'Undated' group, never dropped). Sorted newest-first, then by
    filename descending for a stable within-day order. `audits_dir` resolves to the module
    `_AUDITS_DIR` at CALL time when None (so a monkeypatched global is honored).

    `tracked` defaults to the `_AUTO` sentinel, which resolves `tracked_files(_REPO_ROOT)` at
    CALL time (again so a monkeypatched root is honored); pass an explicit frozenset to pin it,
    or None to disable filtering. An UNTRACKED file is skipped, so the generated bytes are a
    function of COMMITTED state -- see the module header for why that is the whole point.
    """
    audits_dir = audits_dir if audits_dir is not None else _AUDITS_DIR
    # `root` is the repo the TRACKED SET is relative to, and it must be explicit. It was
    # implicitly `_REPO_ROOT` at both call sites, which is right for every live invocation and
    # silently wrong for any other repo: `_is_tracked` derives the repo-relative name against
    # this root, so a caller handing in another repo's `audits_dir` + `tracked` got every path
    # falling out of `relative_to` and being INCLUDED. The filter then did nothing while
    # appearing to be applied. Found 2026-08-26 by the [#590] content verifier, which is
    # exactly such a caller; the live behaviour is unchanged because the default is unchanged.
    root = root if root is not None else _REPO_ROOT
    if tracked is _AUTO:
        tracked = tracked_files(root)
    rows: list[tuple[str, str, str, str]] = []
    for p in sorted(audits_dir.glob("*.md")):
        if p.name == "README.md":
            continue
        if not _is_tracked(p, root, tracked):   # type: ignore[arg-type]
            continue
        m = _DATE_RE.match(p.stem)
        date, slug = (m.group(1), m.group(2)) if m else ("", p.stem)
        rows.append((date, slug, p.name, _title_of(p)))
    rows.sort(key=lambda r: (r[0], r[2]), reverse=True)
    return rows


def render_index(audits_dir: Path | None = None,
                 tracked: frozenset[str] | None | object = _AUTO,
                 root: Path | None = None) -> str:
    # None -> collect_audits resolves _AUDITS_DIR / _REPO_ROOT / the tracked set at call time
    rows = collect_audits(audits_dir, tracked, root)
    out = [
        "# Audits index — generated navigation map of `docs/audits/`",
        "",
        "> Mechanical reverse-chronological index of every `docs/audits/*.md` (date · slug ·",
        "> title), grouped by month. The §5.5 navigation-overhead trigger, satisfied by",
        "> generation. Retention is ruled keep-all-accepted (ADR-100); the count-tiered index",
        "> shape ADR-100 also names is [#269] and is NOT built — this index groups by month.",
        "> Do not hand-edit. Regenerate: `python scripts/gen_audit_index.py --write`",
        "",
        _GENERATED_NOTE,
        "",
        f"**{len(rows)} audit documents.**",
        "",
    ]
    current_month = object()  # sentinel so a real "" month still emits a header once
    for date, slug, filename, title in rows:
        month = date[:7] if date else "Undated"
        if month != current_month:
            current_month = month
            out += ["", f"## {month}", ""]
        label = date or slug
        out.append(f"- [{label}]({filename}) — {title}")
    return "\n".join(out) + "\n"


def load_title_baseline(path: Path | None = None) -> frozenset[str]:
    """The grandfathered title-less set. A missing or unreadable baseline reads as EMPTY.

    Empty is the STRICT direction: with no baseline every title-less artifact is unbaselined and
    the gate refuses. A missing baseline that read as "everything is fine" would be a gate that
    disarms itself by having its own input deleted.
    """
    target = _TITLE_BASELINE_PATH if path is None else path
    try:
        data = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return frozenset()
    names = data.get("title_less") if isinstance(data, dict) else None
    return frozenset(names) if isinstance(names, list) else frozenset()


def title_less(audits_dir: Path | None = None,
               tracked: frozenset[str] | None | object = _AUTO,
               root: Path | None = None) -> tuple[str, ...]:
    """Filenames of indexed audits carrying no `# ` heading, sorted.

    The rule is H1-PRESENT, not H1-FIRST. `_title_of` searches the whole file, so an artifact
    whose provenance blockquote precedes its heading indexes perfectly and is NOT reported here.
    Pinning the ORDER would refuse files that render correctly; the ordering preference belongs
    to whoever writes the persist template, and this gate's business is existence.
    """
    rows = collect_audits(audits_dir, tracked, root)
    return tuple(sorted(name for _, _, name, title in rows if title == NO_TITLE))


def unbaselined_title_less(audits_dir: Path | None = None,
                           tracked: frozenset[str] | None | object = _AUTO,
                           root: Path | None = None,
                           baseline: frozenset[str] | None = None) -> tuple[str, ...]:
    """Title-less audits NOT in the committed baseline — the refusal set."""
    known = load_title_baseline() if baseline is None else baseline
    return tuple(n for n in title_less(audits_dir, tracked, root) if n not in known)


def stale_baseline_entries(audits_dir: Path | None = None,
                           tracked: frozenset[str] | None | object = _AUTO,
                           root: Path | None = None,
                           baseline: frozenset[str] | None = None) -> tuple[str, ...]:
    """Baselined names that are no longer title-less — the DRAIN direction.

    A ratchet that only grows is a debt register nobody pays down, and a fixed artifact still
    sitting in the baseline hides the next real one. Covers two cases with one predicate: the
    file gained a heading, and the file is gone from the index entirely.
    """
    known = load_title_baseline() if baseline is None else baseline
    return tuple(sorted(known - set(title_less(audits_dir, tracked, root))))


def _cmd_write_title_baseline() -> int:
    payload = {
        "measurement": "docs/audits/*.md carrying no `# ` heading, at the commit stamped below",
        "detector": "gen_audit_index.title_less",
        "title_less": list(title_less()),
    }
    _TITLE_BASELINE_PATH.write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"gen_audit_index: wrote {_TITLE_BASELINE_PATH.relative_to(_REPO_ROOT)} "
          f"({len(payload['title_less'])} title-less)")
    return 0


def _cmd_write() -> int:
    _TARGET.write_text(render_index(), encoding="utf-8", newline="\n")
    print(f"gen_audit_index: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check PLUS the title gate.

    Exit 0 clean / 1 drift (+diff) or an unbaselined title-less audit / 2 target missing.
    The two legs are SEQUENTIAL, not combined: a stale index is reported alone, because a
    title measurement taken against a stale index would name rows that regeneration is
    about to change anyway.
    """
    rel = _TARGET.relative_to(_REPO_ROOT)
    if not _TARGET.exists():
        print(f"error: {rel} not found — generate it: "
              f"python scripts/gen_audit_index.py --write", file=sys.stderr)
        return 2
    fresh = render_index()
    current = _TARGET.read_text(encoding="utf-8")
    if current != fresh:
        diff = "".join(difflib.unified_diff(
            current.splitlines(keepends=True), fresh.splitlines(keepends=True),
            fromfile="README.md (current)", tofile="README.md (fresh)"))
        print(diff, file=sys.stderr)
        print(f"gen_audit_index: {rel} is stale vs docs/audits/ — regenerate: "
              f"python scripts/gen_audit_index.py --write", file=sys.stderr)
        return 1
    return _check_titles()


def _check_titles() -> int:
    """The TITLE gate. A fresh index is not the same as a navigable one.

    WHERE THIS BINDS, stated because the first version of this docstring got it wrong. It runs
    from TWO entry points with different coverage. Via `--check` it rides `audit-index-freshness`,
    which `[#590]` deliberately narrowed to the index and its generator — so that path fires when
    the INDEX is touched, NOT when an audit is added. Via `--check-titles` it is armed separately
    on `docs/audits/**`, which is the path that catches the adding commit. The separate arming is
    safe precisely because this check WRITES NOTHING: `[#590]`'s narrowing existed because forcing
    every lane to regenerate a shared file put that file in 6 of the last 7 conflicted merges, and
    a read-only check shares nothing to conflict over.

    Armed as a RATCHET against a committed baseline rather than as a day-one FAIL: twenty live
    artifacts are title-less at arm time, so a hard refusal would have to be bypassed on its
    first commit — which trains the bypass instead of the fix. Same posture as
    `check_adr_status_grammar`. Both directions are checked: a NEW title-less artifact refuses,
    and a baselined one that has since gained a heading is reported as drainable.
    """
    new = unbaselined_title_less()
    stale = stale_baseline_entries()
    if not new and not stale:
        return 0
    if new:
        print("gen_audit_index: audit(s) with NO `# ` heading and not in the baseline:",
              file=sys.stderr)
        for name in new:
            print(f"  {name}", file=sys.stderr)
        print("  every indexed audit carries a `# ` heading somewhere in the file — the index"
              " renders it as the row's title, and without one the row reads `(no # title)`."
              " A harvested artifact needs its own `# ` line ABOVE or BELOW its PROVENANCE"
              " blockquote; either order indexes. Fix the file, or record the exception:"
              " python scripts/gen_audit_index.py --write-title-baseline", file=sys.stderr)
    if stale:
        print("gen_audit_index: baselined name(s) that are no longer title-less — drain them:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        print("  python scripts/gen_audit_index.py --write-title-baseline", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_audit_index",
        description="Generate/check docs/audits/README.md (the audits navigation index)")
    parser.add_argument("--write", action="store_true", help="regenerate the index from disk")
    parser.add_argument("--check", action="store_true",
                        help="check the index against disk state (default action)")
    parser.add_argument("--check-titles", action="store_true", dest="check_titles",
                        help="check ONLY the title gate — reads files, never the index, which "
                             "is what lets it be armed on docs/audits/** without re-creating "
                             "the [#590] merge-conflict coupling")
    parser.add_argument("--write-title-baseline", action="store_true",
                        dest="write_title_baseline",
                        help="re-measure the grandfathered title-less set (a REVIEWED act)")
    args = parser.parse_args(argv)
    if args.write_title_baseline:
        return _cmd_write_title_baseline()
    if args.check_titles:
        return _check_titles()
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
