#!/usr/bin/env python
"""gen_audit_index.py — generate docs/audits/README.md, a navigation index of the audits.

`docs/audits/**` is the corpus's single largest doc area (~190 dated artifacts); with no index,
finding an audit means an `ls` + guess. This generator enumerates every `docs/audits/*.md`
(date + slug + first-`# `-heading title) into a reverse-chronological index grouped by month —
the §5.5 navigation-overhead trigger, satisfied mechanically. The RETENTION policy is **ruled**:
ADR-100 (`docs/decisions/ADR-100-audit-retention-index-rule.md`) decided keep-all-accepted, and
folded and closed `[#212]` in doing so. ADR-100 ALSO names a count-tiered index shape, which is
**not built here** — this module still groups by month, and the tiering plus its freshness hook
are `[#269]`. The header says so rather than advertising a shape this code does not emit.

Loose top-level module BY DESIGN (mirrors gen_claude_rosters.py / gen_methodology_roster.py):
no codemap node, no ARCHITECTURE codemap regen on edit. Layer-2 read-only (ADR-28/36): writes
NOTHING except the index target under --write. The target README is itself EXCLUDED from the
scan (an index never indexes itself).

TRACKED FILES ONLY, and this is the determinism boundary. `collect_audits` globs the working
tree, so an UNTRACKED `docs/audits/2026-01-01-technical-scratch.md` used to render a row: the
generated bytes depended on one machine's private files and `--check` would red on every other
checkout of the same commit, making the freshness gate unholdable anywhere but the machine that
last regenerated. This is the SAME defect terra finding F1 found in `generate_organ_index.py`,
fixed there at `d5b19a2d`; the fix here is that fix, applied to its twin. It was not theoretical
in this module either -- the 2026-08-12 night-1 lane hit exactly this shape (a concurrent lane's
untracked audit in the shared working tree would have entered the index) and declared
`SKIP=audit-index-freshness` rather than commit a wrong index.

HONEST LIMIT, stated in `tracked_files`: outside a git work tree there is no tracked set, so
filtering is DISABLED rather than emptying the index -- the synthetic trees the tests build are
not repos, and returning nothing outside a checkout is a worse failure than the one prevented.

Deterministic: same COMMITTED inputs -> byte-identical output, asserted rather than claimed by
`test_an_untracked_audit_file_does_not_change_the_generated_bytes` (a real git repo).
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_AUDITS_DIR = _REPO_ROOT / "docs" / "audits"
_TARGET = _AUDITS_DIR / "README.md"

_GENERATED_NOTE = "<!-- generated by gen_audit_index.py; do not edit by hand -->"
_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+)$")
_TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


_AUTO = object()   # "resolve the tracked set yourself" sentinel for collect_audits()


def tracked_files(root: Path) -> frozenset[str] | None:
    """Repo-relative POSIX paths git TRACKS, or None when `root` is not a git work tree.

    THE DETERMINISM BOUNDARY (see the module header). None means "cannot tell" and disables
    filtering rather than emptying the index. Mirrors `generate_organ_index.tracked_files`
    deliberately -- the same defect deserves the same shape, not a second dialect.
    """
    try:
        out = subprocess.run(["git", "-C", str(root), "ls-files", "-z"],
                             capture_output=True, text=True, encoding="utf-8")
    except OSError:
        return None
    if out.returncode != 0:
        return None
    return frozenset(p.replace("\\", "/") for p in out.stdout.split("\0") if p)


def _is_tracked(path: Path, root: Path, tracked: frozenset[str] | None) -> bool:
    """True when filtering is off (tracked is None) or `path` is in the tracked set."""
    if tracked is None:
        return True
    try:
        rel = path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return True          # outside the root -> not ours to judge; never silently drop
    return rel in tracked


def _title_of(path: Path) -> str:
    """First `# ` heading in the file, or a loud placeholder (never silently blank)."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "(unreadable)"
    m = _TITLE_RE.search(text)
    return m.group(1).replace("|", "/") if m else "(no # title)"


def collect_audits(audits_dir: Path | None = None,
                   tracked: frozenset[str] | None | object = _AUTO,
                   ) -> list[tuple[str, str, str, str]]:
    """[(date, slug, filename, title), ...] for every TRACKED docs/audits/*.md except the index.

    `date`/`slug` parse from the `YYYY-MM-DD-slug.md` convention; a file not matching it gets
    date="" (sorted last under an 'Undated' group, never dropped). Sorted newest-first, then by
    filename descending for a stable within-day order. `audits_dir` resolves to the module
    `_AUDITS_DIR` at CALL time when None (so a monkeypatched global is honored).

    `tracked` defaults to the `_AUTO` sentinel, which resolves `tracked_files(_REPO_ROOT)` at
    CALL time (again so a monkeypatched root is honored); pass an explicit frozenset to pin it,
    or None to disable filtering. An UNTRACKED file is skipped, so the generated bytes are a
    function of COMMITTED state -- see the module header for why that is the whole point.
    """
    audits_dir = audits_dir if audits_dir is not None else _AUDITS_DIR
    if tracked is _AUTO:
        tracked = tracked_files(_REPO_ROOT)
    rows: list[tuple[str, str, str, str]] = []
    for p in sorted(audits_dir.glob("*.md")):
        if p.name == "README.md":
            continue
        if not _is_tracked(p, _REPO_ROOT, tracked):   # type: ignore[arg-type]
            continue
        m = _DATE_RE.match(p.stem)
        date, slug = (m.group(1), m.group(2)) if m else ("", p.stem)
        rows.append((date, slug, p.name, _title_of(p)))
    rows.sort(key=lambda r: (r[0], r[2]), reverse=True)
    return rows


def render_index(audits_dir: Path | None = None,
                 tracked: frozenset[str] | None | object = _AUTO) -> str:
    # None -> collect_audits resolves _AUDITS_DIR / the tracked set at call time
    rows = collect_audits(audits_dir, tracked)
    out = [
        "# Audits index — generated navigation map of `docs/audits/`",
        "",
        "> Mechanical reverse-chronological index of every `docs/audits/*.md` (date · slug ·",
        "> title), grouped by month. The §5.5 navigation-overhead trigger, satisfied by",
        "> generation. Retention is ruled keep-all-accepted (ADR-100); the count-tiered index",
        "> shape ADR-100 also names is [#269] and is NOT built — this index groups by month.",
        "> Do not hand-edit. Regenerate: `python scripts/gen_audit_index.py --write`",
        "",
        _GENERATED_NOTE,
        "",
        f"**{len(rows)} audit documents.**",
        "",
    ]
    current_month = object()  # sentinel so a real "" month still emits a header once
    for date, slug, filename, title in rows:
        month = date[:7] if date else "Undated"
        if month != current_month:
            current_month = month
            out += ["", f"## {month}", ""]
        label = date if date else slug
        out.append(f"- [{label}]({filename}) — {title}")
    return "\n".join(out) + "\n"


def _cmd_write() -> int:
    _TARGET.write_text(render_index(), encoding="utf-8", newline="\n")
    print(f"gen_audit_index: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check. Exit 0 clean / 1 drift (+diff) / 2 target missing."""
    rel = _TARGET.relative_to(_REPO_ROOT)
    if not _TARGET.exists():
        print(f"error: {rel} not found — generate it: "
              f"python scripts/gen_audit_index.py --write", file=sys.stderr)
        return 2
    fresh = render_index()
    current = _TARGET.read_text(encoding="utf-8")
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile="README.md (current)", tofile="README.md (fresh)"))
    print(diff, file=sys.stderr)
    print(f"gen_audit_index: {rel} is stale vs docs/audits/ — regenerate: "
          f"python scripts/gen_audit_index.py --write", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_audit_index",
        description="Generate/check docs/audits/README.md (the audits navigation index)")
    parser.add_argument("--write", action="store_true", help="regenerate the index from disk")
    parser.add_argument("--check", action="store_true",
                        help="check the index against disk state (default action)")
    args = parser.parse_args(argv)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
