#!/usr/bin/env python
"""gen_intake_index.py -- generate the status-grouped Contents index in docs/intake/README.md (#307).

Navigation is via this generated index grouping by lifecycle state, derived on-edit from each
doc's frontmatter `status:` (no sweep), mirroring gen_audit_index.py. Archival model (operator
ruling 2026-07-22, superseding the earlier M4 never-move ruling): TERMINAL docs relocate
byte-identical to docs/intake/archive/ -- the depth-1 glob below drops them from the index while
their intake-id join keys stay valid at the archive path (README section 5). This generator
itself MOVES NO FILE -- the relocation is manual; it only splices a marker-bounded Contents block
into the hand-authored docs/intake/README.md (the doctrine sections 1-9 are preserved; only the
block between the INTAKE-INDEX markers is rewritten).

Loose top-level module BY DESIGN (mirrors gen_audit_index.py / gen_doc_counts.py): no codemap node,
so editing it never forces an ARCHITECTURE codemap regen. Deterministic: same inputs -> byte-
identical output. Layer-2 read-only (ADR-28/36): writes NOTHING except the single README target
under --write.
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

import yaml

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_INTAKE_DIR = _REPO_ROOT / "docs" / "intake"
_TARGET = _INTAKE_DIR / "README.md"
# Terminal docs relocate here byte-identical (README section 5). Out of the Contents index by
# the depth-1 glob; still IN the id namespace.
_ARCHIVE_DIRNAME = "archive"

_START_MARKER = "<!-- INTAKE-INDEX:START -->"
_END_MARKER = "<!-- INTAKE-INDEX:END -->"
_GENERATED_NOTE = "<!-- generated by gen_intake_index.py; do not edit by hand -->"

# The ruled lifecycle order (README section 5; the 2026-07-19 enum ruling recorded at
# docs/handoffs/2026-07-20-dev-knowledge-architect/SUPPLEMENT.md:68-70, deployed by #398).
# A status outside this canon is NOT dropped -- it lands in a loud trailing "OTHER" group
# so a typo/new-state surfaces instead of vanishing.
_STATUS_ORDER = ("SEED", "DRAFT", "READY", "ACCEPTED", "CONSUMED", "SUPERSEDED", "REJECTED")
_OTHER = "OTHER"

_TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


def _parse_frontmatter(text: str) -> dict[str, str]:
    """The leading `---`...`---` YAML frontmatter as a flat {key: value} dict, or {} if absent.

    Parsed with `yaml.safe_load` -- the same call `audit.check_vision_md` already makes on
    frontmatter, so this is the repo's existing precedent rather than a new dependency
    (`pyyaml>=6.0` is already declared; nothing is added to uv.lock).

    WHY THE HAND-ROLLED REGEX WENT: its key class was `[a-z0-9-]+`, which has no underscore,
    so every underscore-bearing key matched NOTHING and was dropped silently from a dict this
    docstring calls YAML frontmatter. `last_reviewed` and `reconciled_with` are both live
    conventions in this repo's own canonical docs. The visible consequence was one level up:
    `gen_intake_tree._off_projection_keys` -- the AC-4 residue enumeration -- reported no
    residue for such a key, green because it was looking at zero keys of that shape.

    Contracts preserved from the regex version:
      * no leading `---`                -> {}
      * unterminated (no closing `---`) -> {}, so the doc surfaces loudly in OTHER with a
        MISSING-ID label rather than being silently mis-parsed from body lines that happen
        to match `status:` (codex-review 2026-07-11)
      * keys lowercased, and values coerced to stripped strings so callers' `.strip()` /
        `.upper()` keep working where YAML would otherwise hand back a typed scalar (an
        unquoted ISO date parses to a `date`, which has no `.strip()`)

    Malformed YAML returns {} -- the same loud path as invalid frontmatter. A generator a
    pre-commit hook runs must not crash on one bad doc; the doc surfaces in OTHER instead.
    """
    if not text.startswith("---"):
        return {}
    block: list[str] = []
    closed = False
    for line in text.splitlines()[1:]:
        if line.strip() == "---":
            closed = True
            break
        block.append(line)
    if not closed:
        return {}
    try:
        data = yaml.safe_load("\n".join(block))
    except yaml.YAMLError:
        return {}
    if not isinstance(data, dict):
        return {}
    return {str(k).lower(): ("" if v is None else str(v)).strip() for k, v in data.items()}


def _title_of(text: str) -> str:
    m = _TITLE_RE.search(text)
    return m.group(1).replace("|", "/") if m else "(no # title)"


def collect_intakes(intake_dir: Path | None = None) -> list[tuple[str, str, str, str]]:
    """[(status, intake_id, filename, title), ...] for every docs/intake/*.md except README.

    `status` is the frontmatter `status:` bare word (uppercased), or "" (-> OTHER group).
    `intake_id` is the frontmatter `intake-id:` value, or "" when absent. Read-only; resolves
    `_INTAKE_DIR` at CALL time when None (so a monkeypatched global is honored)."""
    intake_dir = intake_dir if intake_dir is not None else _INTAKE_DIR
    rows: list[tuple[str, str, str, str]] = []
    for p in sorted(intake_dir.glob("*.md")):
        if p.name == "README.md":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            rows.append(("", "", p.name, "(unreadable)"))
            continue
        fm = _parse_frontmatter(text)
        status = (fm.get("status", "") or "").strip().upper()
        intake_id = (fm.get("intake-id", "") or "").strip()
        rows.append((status, intake_id, p.name, _title_of(text)))
    return rows


def collect_archived_intakes(intake_dir: Path | None = None) -> list[tuple[str, str]]:
    """[(intake_id, path relative to intake_dir), ...] for every archive/**/*.md.

    Archived docs are OUT of the Contents index by `collect_intakes`' depth-1 glob, but their
    ids stay ALLOCATED -- README section 5: "Archived docs drop out of the generated Contents
    index (depth-1 scan); their `intake-id` join keys stay valid at the archive path". So they
    count toward `next_free_id`, and an archived doc legitimately SHARES the id of the active
    doc that consumed it -- that share IS the join key (see `duplicate_id_reasons`).
    """
    intake_dir = intake_dir if intake_dir is not None else _INTAKE_DIR
    archive = intake_dir / _ARCHIVE_DIRNAME
    if not archive.is_dir():
        return []
    rows: list[tuple[str, str]] = []
    for p in sorted(archive.rglob("*.md")):
        if p.name == "README.md":
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        rows.append(((_parse_frontmatter(text).get("intake-id", "") or "").strip(),
                     p.relative_to(intake_dir).as_posix()))
    return rows


def duplicate_id_reasons(intake_dir: Path | None = None) -> list[str]:
    """Every `intake-id` ALLOCATION COLLISION in the tree as ASCII sentences; [] when clean.

    The organ behind README section 3's "next free across all history", which until now was
    prose with nothing behind it. On 2026-09-06 both mandatory generators were run against a
    tree carrying a duplicate id and BOTH wrote their output without a word -- the filings Q-3
    finding F1, ruled in `to-cc/ANSWER-filings-Q3.md`. A join key silently allocated twice makes
    a bare `#N` citation resolve to two documents, which is the one thing an id exists to prevent.

    WHAT IS A COLLISION AND WHAT IS THE MODEL WORKING -- the distinction this function exists to
    draw, because getting it wrong renumbers a deliberate structure:

      * TWO ACTIVE docs (`docs/intake/*.md`) on one id -> COLLISION. Neither is the other's
        provenance and the id no longer identifies a document.
      * An ARCHIVED doc sharing an ACTIVE doc's id -> LEGAL, and deliberate. It is the join key
        README section 5 keeps valid at the archive path: a draft unioned into a ruled pack stays
        in-folder as provenance under the same id, carrying `status: CONSUMED` and a
        `consumed-by:` naming the doc that holds the id live. Intake #14 is exactly this shape --
        two independent derivations (Fable + Codex) under one ruled pack, whose own text calls it
        "section 1 join-key discipline -- same intake-id 14".
      * TWO ARCHIVED docs on one id with NO active holder -> COLLISION. Nothing joins them, so the
        id is ambiguous with no live document to disambiguate it.

    Read-only, and deliberately git-free: a pre-commit gate pays one directory scan, not a ref
    walk. `next_free_id` is the half that must see every ref (D8's mechanism row).
    """
    active: dict[str, list[str]] = {}
    for _status, intake_id, filename, _title in collect_intakes(intake_dir):
        if intake_id:
            active.setdefault(intake_id, []).append(filename)
    archived: dict[str, list[str]] = {}
    for intake_id, relpath in collect_archived_intakes(intake_dir):
        if intake_id:
            archived.setdefault(intake_id, []).append(relpath)

    reasons: list[str] = []
    for intake_id in sorted(active, key=lambda v: (int(v) if v.isdigit() else 10**9, v)):
        held = sorted(active[intake_id])
        if len(held) > 1:
            reasons.append(
                f"intake-id {intake_id} is held by {len(held)} ACTIVE intake docs: "
                f"{', '.join(held)} -- an id is allocated once (README section 3). Earlier-merged "
                f"keeps the id; the later doc takes the next free one "
                f"(`python scripts/gen_intake_index.py --next-free`), and every citation of the "
                f"moved id moves in the SAME commit")
    for intake_id in sorted(archived, key=lambda v: (int(v) if v.isdigit() else 10**9, v)):
        held = sorted(archived[intake_id])
        if len(held) > 1 and intake_id not in active:
            reasons.append(
                f"intake-id {intake_id} is held by {len(held)} ARCHIVED intake docs and no active "
                f"doc joins them: {', '.join(held)} -- an archived id is a join key back to the "
                f"live doc that holds it (README section 5); with no live holder it resolves to "
                f"nothing and the two archived docs are simply ambiguous")
    return reasons


class RefScanError(RuntimeError):
    """The all-refs scan could not complete, so no id may be allocated from its answer.

    A SILENT DEGRADE IS THE DEFECT THIS MODULE EXISTS TO END (codex-review HIGH, 2026-09-07).
    The first cut swallowed every git failure and returned the working-tree answer while still
    reporting "working tree + all refs" -- so a missing git, a timeout, or one unreadable ref
    would hand out an id that a branch already holds, which is precisely the cross-branch
    collision D8's mechanism row names. An allocator that cannot see every ref must REFUSE, not
    guess; `--no-refs` stays the explicit, labelled opt-out.
    """


def _git(args: list[str], repo_root: Path, ok_codes: tuple[int, ...] = (0,)) -> str:
    """`git <args>` stdout. Raises `RefScanError` unless the exit code is in `ok_codes`.

    `git grep` needs `ok_codes=(0, 1)`: 1 means NO MATCH, which is the ordinary answer for a ref
    carrying no intake docs, while 2+ is a real error. Collapsing the two is how "this ref has
    nothing" and "this ref could not be read" became the same empty string.
    """
    try:
        proc = subprocess.run(["git", *args], cwd=str(repo_root), capture_output=True,
                              text=True, encoding="utf-8", errors="replace", timeout=120)
    except (OSError, subprocess.SubprocessError) as exc:
        raise RefScanError(f"`git {' '.join(args)}` could not run: {exc!r}") from exc
    if proc.returncode not in ok_codes:
        raise RefScanError(
            f"`git {' '.join(args)}` exited {proc.returncode}: "
            f"{(proc.stderr or '').strip()[:200] or 'no stderr'}")
    return proc.stdout


def allocated_ids(intake_dir: Path | None = None, scan_refs: bool = True,
                  repo_root: Path | None = None) -> dict[int, set[str]]:
    """{id: {where it is allocated}} over the WORKING TREE and, when `scan_refs`, EVERY ref.

    D8's mechanism row (`to-cc/DECLARE-SITTING-2026-09-06.md`), and the half that makes the
    collision recur if it is dropped: "next-free computed across ALL refs (local + origin
    branches), not `main` only". A colliding doc is BY DEFINITION not yet on `main` -- it is on
    the branch that is about to allocate the same id -- so an allocator that reads only the
    checked-out tree reproduces exactly the collision it exists to prevent. Witnessed the same
    night: id 76 was live on `docs/intake-031-two-chats` and on no other ref, so a tree-only
    max() would have handed out 76 a second time.
    """
    intake_dir = intake_dir if intake_dir is not None else _INTAKE_DIR
    repo_root = repo_root if repo_root is not None else _REPO_ROOT
    found: dict[int, set[str]] = {}

    def _record(raw: str, where: str) -> None:
        if raw.isdigit():
            found.setdefault(int(raw), set()).add(where)

    for _status, intake_id, filename, _title in collect_intakes(intake_dir):
        _record(intake_id, f"(working tree) {filename}")
    for intake_id, relpath in collect_archived_intakes(intake_dir):
        _record(intake_id, f"(working tree) {relpath}")

    if not scan_refs:
        return found
    refs = [r for r in _git(
        ["for-each-ref", "--format=%(refname)", "refs/heads", "refs/remotes"],
        repo_root).splitlines() if r]
    if not refs:
        # Every git checkout has at least one ref. Zero means git answered without answering.
        raise RefScanError("`git for-each-ref` listed no refs -- the ref scan cannot be trusted")
    for ref in refs:
        out = _git(["grep", "--full-name", "-n", "^intake-id:", ref, "--", "docs/intake"],
                   repo_root, ok_codes=(0, 1))
        for line in out.splitlines():
            parts = line.split(":", 3)
            if len(parts) < 4 or "intake-id:" not in parts[3]:
                continue
            path = parts[1]
            if path.endswith("/README.md"):
                continue
            _record(parts[3].split("intake-id:", 1)[1].strip(), f"{ref} {path}")
    return found


def next_free_id(intake_dir: Path | None = None, scan_refs: bool = True,
                 repo_root: Path | None = None) -> int:
    """The next `intake-id` to hand out: max(every id ever allocated, on any ref) + 1.

    Closed ids are NOT reused (README section 3, same discipline as BACKLOG ids), so this is a
    high-water mark and never a gap-filler -- reissuing a spent id would resurrect the exact
    ambiguity a renumbering was performed to remove.
    """
    ids = allocated_ids(intake_dir, scan_refs=scan_refs, repo_root=repo_root)
    return (max(ids) + 1) if ids else 1


def _group(rows: list[tuple[str, str, str, str]]) -> dict[str, list[tuple[str, str, str, str]]]:
    groups: dict[str, list] = {}
    for row in rows:
        status = row[0] if row[0] in _STATUS_ORDER else _OTHER
        groups.setdefault(status, []).append(row)
    # Stable within-group order: by intake-id numeric when present, else filename.
    for g in groups.values():
        g.sort(key=lambda r: (int(r[1]) if r[1].isdigit() else 10**9, r[2]))
    return groups


def render_row(intake_id: str, filename: str, title: str) -> str:
    """ONE rendered index row. Single definition of the row format, shared with
    gen_intake_tree.py's per-item nodes ([#383] wave 1) so the projection cannot drift
    into two copies. A blank/missing intake-id is a schema break -> flag it LOUDLY; never
    render a date fragment as a pseudo-id (which would read as `[2026]`, codex-review
    2026-07-11)."""
    label = f"#{intake_id}" if intake_id else "MISSING-ID"
    return f"- [{label}]({filename}) — {title}"


def render_contents(intake_dir: Path | None = None) -> str:
    """The marker-block BODY (between START/END markers), ending with a newline."""
    rows = collect_intakes(intake_dir)
    groups = _group(rows)
    out = [_GENERATED_NOTE, "", f"**{len(rows)} intake documents.**"]
    for status in (*_STATUS_ORDER, _OTHER):
        g = groups.get(status)
        if not g:
            continue
        out += ["", f"### {status} ({len(g)})", ""]
        for _status, intake_id, filename, title in g:
            out.append(render_row(intake_id, filename, title))
    return "\n".join(out) + "\n"


def _splice(content: str, block: str) -> str:
    # Require EXACTLY one START and one END with START before END. Reversed or duplicated
    # markers would let --write rewrite OUTSIDE the generated block and corrupt hand-authored
    # doctrine -- the one thing this splice must never do (codex-review 2026-07-11).
    if content.count(_START_MARKER) != 1 or content.count(_END_MARKER) != 1:
        raise RuntimeError(
            f"INTAKE-INDEX markers must appear EXACTLY once each in {_TARGET.name} -- add the "
            f"{_START_MARKER} / {_END_MARKER} pair once, then regenerate")
    start_idx = content.find(_START_MARKER)
    end_idx = content.find(_END_MARKER)
    if start_idx > end_idx:
        raise RuntimeError(
            f"INTAKE-INDEX START marker must precede END in {_TARGET.name}")
    return content[: start_idx + len(_START_MARKER)] + "\n" + block + content[end_idx:]


def _report_duplicates() -> int:
    """Print any allocation collision and return 3, or return 0 when the tree is clean.

    Exit 3 is its own class deliberately -- 1 means the Contents block is STALE (regenerate) and
    2 means the target/markers are missing, and neither remedy applies here: regenerating a
    colliding tree just writes the collision out again, which is precisely finding F1. Both verbs
    consult this BEFORE touching the README, so `--write` refuses rather than laundering a
    duplicate id into a generated index that then reads as authoritative.
    """
    reasons = duplicate_id_reasons()
    for reason in reasons:
        print(f"gen_intake_index: intake-id COLLISION -- {reason}", file=sys.stderr)
    return 3 if reasons else 0


def _cmd_write() -> int:
    if not _TARGET.exists():
        print(f"error: {_TARGET} not found", file=sys.stderr)
        return 2
    collision = _report_duplicates()
    if collision:
        return collision
    new_content = _splice(_TARGET.read_text(encoding="utf-8"), render_contents())
    _TARGET.write_text(new_content, encoding="utf-8", newline="\n")
    print(f"gen_intake_index: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_next_free(scan_refs: bool = True) -> int:
    """Print the next free intake-id and the high-water mark it came from. Exit 0.

    THE ALLOCATOR. Before this verb the rule lived only in README section 3's prose -- "next free
    across all history" -- and an author allocating an id read the folder listing, which
    under-reports by every archived doc and by every doc on a branch that has not merged.
    """
    try:
        ids = allocated_ids(scan_refs=scan_refs)
    except RefScanError as exc:
        print(f"gen_intake_index: REFUSING to allocate -- {exc}", file=sys.stderr)
        print("gen_intake_index: an id allocated from a partial ref scan can collide with a "
              "branch that already holds it. Fix git, or pass --no-refs and accept that the "
              "answer is the working tree ONLY.", file=sys.stderr)
        return 4
    nxt = (max(ids) + 1) if ids else 1
    scope = "working tree + all refs" if scan_refs else "working tree ONLY (--no-refs)"
    print(nxt)
    print(f"gen_intake_index: next free intake-id {nxt} -- {len(ids)} id(s) allocated, "
          f"high-water mark {max(ids) if ids else 0}, scanned {scope}", file=sys.stderr)
    if ids:
        for where in sorted(ids[max(ids)]):
            print(f"gen_intake_index:   high-water mark {max(ids)} at {where}", file=sys.stderr)
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check.

    Exit 0 clean / 1 drift (+diff) / 2 target/markers missing / 3 intake-id collision."""
    rel = _TARGET.relative_to(_REPO_ROOT)
    if not _TARGET.exists():
        print(f"error: {rel} not found -- generate it: "
              f"python scripts/gen_intake_index.py --write", file=sys.stderr)
        return 2
    collision = _report_duplicates()
    if collision:
        return collision
    current = _TARGET.read_text(encoding="utf-8")
    try:
        fresh = _splice(current, render_contents())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile="README.md (current)", tofile="README.md (fresh)"))
    print(diff, file=sys.stderr)
    print(f"gen_intake_index: {rel} Contents block is stale vs docs/intake/ -- regenerate: "
          f"python scripts/gen_intake_index.py --write", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_intake_index",
        description="Generate/check the status-grouped Contents index in docs/intake/README.md")
    parser.add_argument("--write", action="store_true",
                        help="regenerate the Contents block in the README from disk")
    parser.add_argument("--check", action="store_true",
                        help="check the Contents block against disk state (default action)")
    parser.add_argument("--next-free", action="store_true",
                        help="print the next free intake-id, computed across ALL refs (D8)")
    parser.add_argument("--no-refs", action="store_true",
                        help="with --next-free: read the working tree only (loses the D8 "
                             "guarantee; for an offline checkout, never for allocating an id)")
    args = parser.parse_args(argv)
    if args.next_free:
        return _cmd_next_free(scan_refs=not args.no_refs)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
