#!/usr/bin/env python
"""gen_methodology_roster.py — generate .claude/methodology-roster.md from the manifest ([#244] P3).

Closes Fable R3 (consumer CLAUDE.md rosters are hand-prose with no source of truth, so they
rot). The DEPLOYED methodology surface (commands / hooks / config the deploy tool ships) is
machine-generated from the single source of truth — `deploy/manifest-v*.yaml`'s
`components:[].roster` fields — and `@`-imported into CLAUDE.md. CLAUDE.md itself stays 100%
hand-prose so the `canonical_freshness` gate keeps full teeth; this generated file is OUT of
`DEFAULT_FRESHNESS_FILES` (its currency is regeneration, not a review stamp — the #222
`ecosystem/doc-counts.md` decouple precedent). Hub-local items (the surface with no manifest
entry) stay hand-authored in CLAUDE.md §7-§9 — do NOT source them here (operator boundary).

WHAT THIS DECLARES (LOCK-1, honesty): the manifest is the DEPLOYABLE corpus — what a
fully-deployed *consumer* receives — NOT a filesystem inventory of the repo this runs in. The
hub is the methodology *source*, so this roster lists components (e.g. the floor) the hub does
not itself install. The generated header says so; no reader should treat it as an install list.

Loose top-level module BY DESIGN (mirrors gen_doc_counts.py): the codemap enumerates only
`scripts/<pkg>/` dirs with `__init__.py`, so a loose module adds no codemap node and editing it
never forces an ARCHITECTURE.md codemap regen. Do NOT convert to a package.

Deterministic: same manifest bytes -> byte-identical output (the drift check depends on it).
Reads the manifest with `yaml.safe_load` directly (NOT `deploy.tool.load_manifest`) to stay
decoupled from the carrier machinery — this generator has a single, stable read concern.

Layer-2 read-only (ADR-28/36): reads repo state; writes NOTHING except the one generated target.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

import yaml

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_DEPLOY_DIR = _REPO_ROOT / "deploy"
_TARGET = _REPO_ROOT / ".claude" / "methodology-roster.md"

_GENERATED_NOTE = "<!-- generated by gen_methodology_roster.py; do not edit by hand -->"

# Fixed render order; a section with no active component is omitted. The vocabulary matches
# deploy/release_lint.py ALLOWED_ROSTER_SECTIONS — an unknown section fails loud (see render()).
_SECTION_ORDER = ["header", "command", "session-hook", "precommit-hook", "skill"]
_SECTION_HEADINGS = {
    "header": "Header context",
    "command": "Commands",
    "session-hook": "Session hooks",
    "precommit-hook": "Pre-commit hooks",
    "skill": "Skills",
}

_MANIFEST_VERSION_RE = re.compile(r"^manifest-v(\d+)\.(\d+)\.(\d+)\.yaml$")
# A roster line that BEGINS with a bare @path (e.g. the floor's "@.claude/CLAUDE-FLOOR.md ...").
# This file is @-imported into CLAUDE.md and Claude Code recurses into imports, so a bare leading
# @path would be (mis)read as a nested import — dangling on the hub (no floor). Backtick-wrap it
# (a code span is inert to the import parser); formatting-only, no content change.
_LEADING_IMPORT_RE = re.compile(r"^(@[\w./~-]+)")


def resolve_manifest_path(deploy_dir: Path = _DEPLOY_DIR) -> Path:
    """The current hub manifest: the MAX-semver `deploy/manifest-v*.yaml`.

    The hub IS the methodology source (its `deployed_methodology_version` is null by design),
    so the current roster reflects the latest released manifest. Deterministic: filesystem glob
    + semver sort. (P6 generalization — a consumer resolves its deployed version from
    ecosystem/deployed-versions.yaml — is intentionally NOT built here.)
    """
    candidates: list[tuple[tuple[int, int, int], Path]] = []
    for p in sorted(deploy_dir.glob("manifest-v*.yaml")):
        m = _MANIFEST_VERSION_RE.match(p.name)
        if m:
            candidates.append((tuple(int(g) for g in m.groups()), p))  # type: ignore[arg-type]
    if not candidates:
        raise RuntimeError(f"no manifest-v*.yaml found in {deploy_dir}")
    candidates.sort()
    return candidates[-1][1]


def _neutralize_import(line: str) -> str:
    """Backtick-wrap a leading @path token so the @import parser does not recurse into it."""
    return _LEADING_IMPORT_RE.sub(r"`\1`", line)


def collect_roster(manifest_path: Path) -> tuple[str, dict[str, list[str]]]:
    """(methodology_version, {section: [line, ...]}) for active components carrying a roster.

    Filters: status == 'active' AND roster is a mapping with non-null section+line. Removed
    tombstones (e.g. ruff-gate) and roster:null components (e.g. the L0 codex config) drop out.
    """
    data = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError(f"manifest did not parse to a mapping: {manifest_path}")
    version = str(data.get("methodology_version") or "").strip()
    buckets: dict[str, list[str]] = {s: [] for s in _SECTION_ORDER}
    for comp in data.get("components") or []:
        if comp.get("status") != "active":
            continue
        roster = comp.get("roster")
        if not isinstance(roster, dict):
            continue  # null / absent
        section = roster.get("section")
        line = roster.get("line")
        if not section or not line:
            continue
        if section not in buckets:
            raise RuntimeError(
                f"component {comp.get('id')!r} has unknown roster section {section!r} "
                f"(known: {', '.join(_SECTION_ORDER)})")
        buckets[section].append(str(line))
    return version, buckets


def render(manifest_path: Path) -> str:
    """The full generated file body (deterministic; ends with a single newline)."""
    version, buckets = collect_roster(manifest_path)
    out: list[str] = [
        f"# Methodology-deployed roster — generated (manifest v{version})",
        "",
        "> **This is the manifest-declared DEPLOYABLE methodology corpus** — the commands /",
        "> hooks / config a *fully-deployed consumer* receives, generated from",
        "> `deploy/manifest-v*.yaml`. It is **NOT** a filesystem inventory of this repo: the hub",
        "> is the methodology *source*, so this list includes components (e.g. the floor) the hub",
        "> itself does not install. Currency is by **regeneration**, not a review stamp — this",
        "> file is deliberately out of `DEFAULT_FRESHNESS_FILES`.",
        ">",
        "> Do not hand-edit. Regenerate: `python scripts/gen_methodology_roster.py --write`",
        "",
        _GENERATED_NOTE,
    ]
    for section in _SECTION_ORDER:
        lines = buckets[section]
        if not lines:
            continue
        out.append("")
        out.append(f"## {_SECTION_HEADINGS[section]}")
        for line in lines:
            out.append(f"- {_neutralize_import(line)}")
    return "\n".join(out) + "\n"


def _cmd_write() -> int:
    _TARGET.parent.mkdir(parents=True, exist_ok=True)
    _TARGET.write_text(render(resolve_manifest_path()), encoding="utf-8")
    print(f"gen_methodology_roster: wrote {_TARGET.relative_to(_REPO_ROOT)}")
    return 0


def _cmd_check() -> int:
    """Regen-and-diff drift check. Exit 0 clean / 1 drift (+unified diff) / 2 target missing —
    mirrors scripts/toc/check.py semantics."""
    if not _TARGET.exists():
        print(f"error: {_TARGET.relative_to(_REPO_ROOT)} not found — generate it: "
              f"python scripts/gen_methodology_roster.py --write", file=sys.stderr)
        return 2
    fresh = render(resolve_manifest_path())
    current = _TARGET.read_text(encoding="utf-8")
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile=f"{_TARGET.name} (current)", tofile=f"{_TARGET.name} (fresh)"))
    print(diff, file=sys.stderr)
    print("gen_methodology_roster: roster is stale vs the manifest — regenerate: "
          "python scripts/gen_methodology_roster.py --write", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_methodology_roster",
        description="Generate/check .claude/methodology-roster.md from the current manifest")
    parser.add_argument("--write", action="store_true",
                        help="regenerate the roster file from the manifest")
    parser.add_argument("--check", action="store_true",
                        help="check the roster against the manifest (default action)")
    args = parser.parse_args(argv)
    if args.write:
        return _cmd_write()
    return _cmd_check()


if __name__ == "__main__":
    sys.exit(main())
