"""generate_floor.py — child methodology-floor generator (ADR-78 O2 Bounded Hybrid).

Emits a child repo's `.claude/CLAUDE-FLOOR.md` + `.claude/CLAUDE-FLOOR.md.sha256` from
the ratified content set in `templates/child-methodology-floor.md.tmpl` (under the child's
own CC config dir, not the repo root), and refreshes the hub's
canonical floor-hash reference `templates/child-methodology-floor.sha256` (the currency
anchor the `/ship` staleness gate reads).

OPERATOR-INVOKED ONLY (ADR-73 rollout-moment). This generator must NEVER be wired to a
hook or a schedule, and never makes autonomous cross-repo writes: a child commits its own
floor (operator runs the generator with `--out-dir <child>`, then commits in the child
repo). Strict Layer-2 invariant — no runtime/scheduled cross-repo writes from the hub.

Determinism: the template content IS the shipped floor body, byte-for-byte. The floor is
written with LF newlines and hashed over LF-normalized UTF-8 bytes, so the sidecar hash is
stable across platforms (Windows `autocrlf` cannot break it) and a re-run from the same
template produces an identical hash.

Binding token-ceiling measure (operator-pinned 2026-06-07): the conservative
`ceil(len(text) / 3.5)` chars heuristic is THE gate (deterministic, dependency-free). A
real tokenizer, if installed, is informational only and is NOT consulted here. The refusal
threshold is 1,500 tokens (ADR-78 §4); trim content, never the rule.

F5 self-containment (ADR-72 / ADR-75 `methodology_surface` zone): the floor must carry no
hub-INTERNAL artifact references (backlog ids, LESSONS/JOURNAL/TOKEN-LOG, PROPOSALS,
handoff/transcript paths, HANDOFF_PROCESS, hub ADR numbers) and no external URLs. A single
LABELED, optional escape-hatch naming the `.dev-knowledge` hub is permitted (ADR-78
Decision 1) — that is a documentation pointer, not a load-bearing runtime reference.

Forward note (#136): when the obsolescence-pass doctrine lands in the hub PLAYBOOK, the
floor absorbs its one-liner at the NEXT regeneration of the template — the floor never runs
ahead of ratified hub doctrine.

Usage:
    python scripts/generate_floor.py check                  # validate only; no writes
    python scripts/generate_floor.py generate               # refresh hub hash ref + print
    python scripts/generate_floor.py generate --out-dir ../corp-sca-time-automation
"""

from __future__ import annotations

import hashlib
import math
import re
import sys
from pathlib import Path

import click

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent

TEMPLATE_PATH = _REPO_ROOT / "templates" / "child-methodology-floor.md.tmpl"
# Hub canonical floor-hash reference (the /ship staleness gate's currency anchor).
HUB_CANONICAL_SHA = _REPO_ROOT / "templates" / "child-methodology-floor.sha256"

FLOOR_FILENAME = "CLAUDE-FLOOR.md"
SIDECAR_FILENAME = "CLAUDE-FLOOR.md.sha256"
# The floor lives under the child's own CC config dir, not the repo root (keeps the
# operator's workspace uncluttered). Created if absent at generate time.
CHILD_CLAUDE_DIRNAME = ".claude"

# ---------------------------------------------------------------------------
# Install note — the COMPLETE, surprise-free runbook the generator hands a child
# at rollout. Baked from the 2026-06-08 corp-sca pilot lessons so the re-pilot is
# friction-free: (a) the @-include line, (b) the child-side hash-verify hook script
# with SPLIT imports (no ruff E401) on .claude/ paths, (c) the pre-commit hook as a COMPLETE
# from-scratch-valid config (top-level `repos:`, create-if-absent vs append-to-existing guidance --
# a bare fragment broke the clean-slate re-pilot), (d) the EXPLICIT `pre-commit install` step
# (the hook is wired-but-INERT without it), (e) tamper-revert via `git checkout HEAD --`
# (NOT the index form, which restores from the staged tamper), (f) the .gitignore
# CONTENTS-form negation block so a child whose .claude/ is ignored tracks the floor with a
# plain `git add` (no `git add -f`) -- a bare `.claude/` DIRECTORY exclusion blocks negations
# entirely (git won't re-include a file under an excluded dir), so it must be `.claude/*`.
# Raw string so the emitted regex backslashes and `\r\n` in the script body stay literal.
INSTALL_NOTE = r"""
========================= CHILD FLOOR INSTALL NOTE =========================
The floor + sidecar are written under the child's .claude/. To arm them, do all
SIX steps in the child repo (each is required -- config presence is not enforcement):

1. Reference the floor from the child's CLAUDE.md so CC auto-loads it at session
   start. Add this line (it resolves transitively and fails soft if the file moves):

       @.claude/CLAUDE-FLOOR.md

2. Create the child-side hash-verify hook script at .claude/check_floor_hash.py
   (verbatim -- LF-normalized hashing matches the hub generator + audit.py):

       #!/usr/bin/env python3
       '''Pre-commit guard: verify .claude/CLAUDE-FLOOR.md matches its .sha256 sidecar.
       Generated by the .dev-knowledge floor generator (ADR-78). Do not hand-edit the
       floor; regenerate from the hub instead.'''
       import hashlib
       import re
       import sys
       from pathlib import Path

       FLOOR = Path(".claude/CLAUDE-FLOOR.md")
       SIDECAR = Path(".claude/CLAUDE-FLOOR.md.sha256")


       def _norm(text):
           return text.replace("\r\n", "\n").replace("\r", "\n")


       def main():
           if not FLOOR.exists():
               return 0  # floor not adopted here; nothing to verify
           actual = hashlib.sha256(
               _norm(FLOOR.read_text(encoding="utf-8")).encode("utf-8")).hexdigest()
           if not SIDECAR.exists():
               print("CLAUDE-FLOOR.md.sha256 sidecar missing -- regenerate via the hub "
                     "generator.", file=sys.stderr)
               return 1
           m = re.search(r"[0-9a-f]{64}", SIDECAR.read_text(encoding="utf-8"))
           expected = m.group(0) if m else ""
           if actual != expected:
               print("floor hash drift: %s != sidecar %s -- regenerate via the hub "
                     "generator, or restore with `git checkout HEAD -- "
                     ".claude/CLAUDE-FLOOR.md`." % (actual[:12], expected[:12]),
                     file=sys.stderr)
               return 1
           return 0


       if __name__ == "__main__":
           sys.exit(main())

3. Add this hook to the child's .pre-commit-config.yaml (system language -- no env
   to provision; the filespec arms it only when the floor or its sidecar changes).
   If the child has NO .pre-commit-config.yaml yet, create the file with EXACTLY the
   block below (the top-level `repos:` key is included so it is valid from scratch).
   If a .pre-commit-config.yaml already EXISTS, do NOT add a second `repos:` -- append
   only the `- repo: local` item to the existing top-level `repos:` list, matching
   that file's indentation:

       repos:
         - repo: local
           hooks:
             - id: floor-hash-verify
               name: Verify CLAUDE-FLOOR.md matches its sha256 sidecar
               entry: python .claude/check_floor_hash.py
               language: system
               files: '^\.claude/CLAUDE-FLOOR\.md(\.sha256)?$'
               pass_filenames: false

4. ARM the hook -- run this in the child clone (writes untracked .git/hooks/, so it
   does NOT travel with the repo: EVERY fresh clone must run it itself):

       pre-commit install

5. Make the floor, sidecar, and hook script git-TRACKABLE. If the child's .gitignore
   ignores .claude/, those three files are untracked -- a plain `git add` skips them and
   you would need a fragile `git add -f` on every refresh. Git canNOT re-include a file
   whose parent DIRECTORY is excluded, so a bare `.claude/` line does NOT work with
   negations; it must be the CONTENTS-form `.claude/*`. Edit the child's .gitignore so the
   .claude/ section reads EXACTLY this (CHANGE a bare `.claude/` line to `.claude/*`; if the
   child has no .claude/ ignore at all, add the block as-is):

       .claude/*
       !.claude/CLAUDE-FLOOR.md
       !.claude/CLAUDE-FLOOR.md.sha256
       !.claude/check_floor_hash.py

   (If a bare `.claude/` line MUST stay, instead insert `!.claude/` then `.claude/*` above
   the three negations -- merely appending `.claude/*` AFTER a surviving bare `.claude/`
   does NOT work, because the directory is already excluded.) Verify:
   `git check-ignore .claude/CLAUDE-FLOOR.md` now prints nothing (no longer ignored), so the
   three files stage with a plain `git add` -- no -f.

6. Commit the floor, sidecar, hook script, and config change IN the child repo.

To restore a tampered/edited floor to the committed version, use the HEAD form
(the bare `git checkout -- <file>` restores from the INDEX and will NOT undo a
staged tamper):

       git checkout HEAD -- .claude/CLAUDE-FLOOR.md

To refresh after the hub template changes, re-run the hub generator with
--out-dir <this child> and commit the refreshed floor + sidecar.
============================================================================
"""

# Binding ceiling + binding token measure (operator-pinned). See module docstring.
FLOOR_TOKEN_CEILING = 1500
_TOKEN_CHARS_PER_TOKEN = 3.5

# F5 blacklist — hub-internal artifact tokens that MUST NOT surface in the floor
# (ADR-75 methodology_surface zone, T1 boundary). The bare `.dev-knowledge` hub name is
# deliberately ABSENT: a labeled optional escape-hatch is permitted (ADR-78 Decision 1).
F5_BLACKLIST: list[tuple[str, re.Pattern[str]]] = [
    ("backlog-id", re.compile(r"\[#\d+\]")),
    ("LESSONS.md", re.compile(r"LESSONS\.md", re.IGNORECASE)),
    ("JOURNAL.md", re.compile(r"JOURNAL\.md", re.IGNORECASE)),
    ("TOKEN-LOG", re.compile(r"TOKEN-LOG", re.IGNORECASE)),
    ("PROPOSALS log", re.compile(r"logs/PROPOSALS", re.IGNORECASE)),
    ("handoffs path", re.compile(r"docs/handoffs", re.IGNORECASE)),
    ("transcripts path", re.compile(r"docs/decisions/transcripts", re.IGNORECASE)),
    ("HANDOFF_PROCESS", re.compile(r"HANDOFF_PROCESS", re.IGNORECASE)),
    ("hub ADR ref", re.compile(r"\bADR-\d+\b", re.IGNORECASE)),
]

_URL_RE = re.compile(r"https?://", re.IGNORECASE)


def normalize(text: str) -> str:
    """LF-normalize so hashing is stable across platforms (autocrlf-proof)."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


def estimate_tokens(text: str) -> int:
    """Binding token estimate: ceil(chars / 3.5) over LF-normalized text."""
    return math.ceil(len(normalize(text)) / _TOKEN_CHARS_PER_TOKEN)


def floor_sha256(text: str) -> str:
    """sha256 hexdigest over LF-normalized UTF-8 bytes (matches sidecar + hub ref)."""
    return hashlib.sha256(normalize(text).encode("utf-8")).hexdigest()


def f5_hits(text: str) -> list[str]:
    """Labels of any hub-internal artifact tokens found in the floor (empty = clean)."""
    return [label for label, pat in F5_BLACKLIST if pat.search(text)]


def url_hits(text: str) -> list[str]:
    """External URLs found in the floor (zero-URL policy; empty = clean)."""
    return _URL_RE.findall(text)


def render_floor(template_path: Path = TEMPLATE_PATH) -> str:
    """Read the template and return the floor body (LF-normalized, single trailing NL)."""
    body = normalize(template_path.read_text(encoding="utf-8"))
    return body if body.endswith("\n") else body + "\n"


def validate(floor: str) -> list[str]:
    """Return a list of blocking issues for the floor body (empty = valid)."""
    issues: list[str] = []
    tokens = estimate_tokens(floor)
    if tokens > FLOOR_TOKEN_CEILING:
        issues.append(
            f"token ceiling exceeded: {tokens} > {FLOOR_TOKEN_CEILING} "
            f"(binding measure ceil(chars/{_TOKEN_CHARS_PER_TOKEN})) — trim content, never the rule"
        )
    leaks = f5_hits(floor)
    if leaks:
        issues.append(f"F5 self-containment violation — hub-internal token(s) present: {leaks}")
    urls = url_hits(floor)
    if urls:
        issues.append(f"zero-URL policy violation — external URL(s) present: {urls}")
    return issues


def _write_text_lf(path: Path, text: str) -> None:
    """Write text with LF newlines (no platform translation) so on-disk bytes match the hash."""
    path.write_text(normalize(text), encoding="utf-8", newline="\n")


@click.group()
def cli() -> None:
    """Child methodology-floor generator (ADR-78). Operator-invoked only."""


@cli.command("check")
@click.option("--template", "template", default=None,
              help="Override template path (default templates/child-methodology-floor.md.tmpl).")
def cmd_check(template: str | None) -> None:
    """Validate the floor (ceiling, F5, URLs); print hash + token count. NO writes.

    Exits 1 if the floor violates any binding rule — usable as a hub-side gate.
    """
    tpath = Path(template) if template else TEMPLATE_PATH
    floor = render_floor(tpath)
    issues = validate(floor)
    tokens = estimate_tokens(floor)
    digest = floor_sha256(floor)
    click.echo(f"template: {tpath}")
    click.echo(f"tokens (binding chars/{_TOKEN_CHARS_PER_TOKEN}): {tokens} / ceiling {FLOOR_TOKEN_CEILING}")
    click.echo(f"sha256 (LF-normalized): {digest}")
    if issues:
        for i in issues:
            click.echo(f"  FAIL: {i}", err=True)
        sys.exit(1)
    click.echo("floor valid (ceiling OK, F5 clean, no external URLs).")


@cli.command("generate")
@click.option("--out-dir", "out_dir", default=None,
              help="Child repo dir to write CLAUDE-FLOOR.md + .sha256 into. "
                   "Omit to only refresh the hub canonical hash reference + print.")
@click.option("--template", "template", default=None,
              help="Override template path (default templates/child-methodology-floor.md.tmpl).")
def cmd_generate(out_dir: str | None, template: str | None) -> None:
    """Emit the floor + sidecar (and refresh the hub canonical hash reference).

    Refuses if the floor violates the token ceiling, F5 self-containment, or the
    zero-URL policy. Deterministic: same template → same hash. With --out-dir, writes
    .claude/CLAUDE-FLOOR.md + .claude/CLAUDE-FLOOR.md.sha256 into that child repo
    (creating .claude/ if absent; operator commits them THERE) and prints the complete
    install note. Always refreshes the hub's templates/child-methodology-floor.sha256
    anchor.
    """
    tpath = Path(template) if template else TEMPLATE_PATH
    floor = render_floor(tpath)
    issues = validate(floor)
    if issues:
        click.echo("REFUSED — floor failed validation:", err=True)
        for i in issues:
            click.echo(f"  - {i}", err=True)
        sys.exit(1)

    digest = floor_sha256(floor)

    # Always refresh the hub canonical hash reference (idempotent — stable per template).
    _write_text_lf(HUB_CANONICAL_SHA, digest + "\n")
    try:
        ref_label = HUB_CANONICAL_SHA.relative_to(_REPO_ROOT)
    except ValueError:
        ref_label = HUB_CANONICAL_SHA
    click.echo(f"hub canonical hash refreshed: {ref_label} = {digest}")

    if out_dir:
        out = Path(out_dir)
        if not out.is_dir():
            click.echo(f"REFUSED — --out-dir is not a directory: {out}", err=True)
            sys.exit(1)
        claude_dir = out / CHILD_CLAUDE_DIRNAME
        claude_dir.mkdir(exist_ok=True)  # the child's own CC config dir; create if absent
        _write_text_lf(claude_dir / FLOOR_FILENAME, floor)
        _write_text_lf(claude_dir / SIDECAR_FILENAME, digest + "\n")
        click.echo(f"wrote {claude_dir / FLOOR_FILENAME}")
        click.echo(f"wrote {claude_dir / SIDECAR_FILENAME}")
        click.echo(f"tokens (binding): {estimate_tokens(floor)} / {FLOOR_TOKEN_CEILING}")
        click.echo(INSTALL_NOTE)
    else:
        click.echo("(no --out-dir; child artifacts not written — hub reference refreshed only)")


if __name__ == "__main__":
    cli()
