#!/usr/bin/env python
"""generate_organ_index.py — emit docs/ORGAN-INDEX.md, the machine-derived organ roster ([#132]).

WHAT THIS KILLS. "Operator-as-registry": the answer to *which organs exist, what fires
each one, and does it reach reality today* is currently supplied from the operator's
memory plus three hand-maintained prose surfaces (CLAUDE.md §7-§9, ARCHITECTURE Ch2, the
manifest roster). Each is accurate only until the next organ lands. This generator reads
the organ sources themselves and emits one index, on the established generator +
regen-and-diff-freshness-hook pattern (`gen_audit_index.py`, `gen_claude_rosters.py`,
`gen_methodology_roster.py`, `scripts/codemap/`, `scripts/toc/`).

ARCHITECTURE Ch2 already names this file as its intended successor: *"A generated
`docs/ORGAN-INDEX.md` (#132) will become its verified source once it ships … When they
disagree, trust the index."* So the vocabulary here is Ch2's, deliberately, and not a
second dialect:

  distribution  Ch2 "Layer"  — L0 (global ~/.claude) · hub · plugin · pre-commit
  status        Ch2 "Status" — ARMED · RETIRED · DECLARED

WHAT IT DOES NOT CARRY, stated so a reader does not infer coverage that is absent:
**failure posture**. Whether an organ fails closed, fails soft, or only proposes is a
judgement about its code, recoverable from neither a frontmatter block nor a hook id.
Ch2 carries it by hand and stays the source for that column. This index is exhaustive
about *what exists and what fires it*; it is silent about *what happens when it says no*.

SOURCES (the row's own list). Repo-tracked, so the output is a pure function of the
commit:
  .claude/agents/*.md · .claude/commands/*.md · .claude/skills/*/SKILL.md ·
  .claude/workflows/* · .claude/rules/*.md · .claude/settings.json (hooks +
  enabledPlugins) · .pre-commit-config.yaml · plugins/*/ (plugin.json, commands/,
  hooks/hooks.json) · deploy/manifest-v*.yaml (for the `deployed` annotation)

Plus one DECLARED source, `ecosystem/organ-registry.yaml`, which carries the user-level
(`~/.claude`, Ch2 layer L0) organs. **Why declared and not walked:** a live `~/.claude`
read would make the rendered bytes machine-dependent, and a regen-and-diff freshness gate
over machine-dependent bytes reds on every host but the one that last regenerated. The
registry keeps the gate deterministic and portable; `--probe-user-level` is the
non-gating diagnostic that reads the live `~/.claude` and reports drift against it. That
pair is this module's answer to the [#132] "absorbs #248" clause — see the registry file
header for the fork and which arm each half takes.

`.claude/settings.local.json` is deliberately NOT read: it is untracked, so including it
would reintroduce exactly the machine-dependence the registry exists to avoid.

Loose top-level module BY DESIGN (mirrors gen_audit_index.py / gen_claude_rosters.py /
gen_methodology_roster.py): the codemap enumerates only `scripts/<pkg>/` dirs carrying an
`__init__.py`, so a loose module adds no codemap node and editing it never forces an
ARCHITECTURE.md codemap regen. Do NOT convert it to a package.

Deterministic: same committed inputs -> byte-identical output (the drift check depends on
it, and `test_render_never_reads_the_user_home` asserts it against an emptied HOME).
Layer-2 read-only (ADR-28/36): reads repo state; writes NOTHING except the one generated
target under --write. `--check` and `--probe-user-level` write nothing at all.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import NamedTuple

import yaml

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
_TARGET_REL = Path("docs") / "ORGAN-INDEX.md"

_GENERATED_NOTE = "<!-- generated by generate_organ_index.py; do not edit by hand -->"

# The CLOSED organ-class vocabulary. "Covering all organ classes" (the row's Done-when) is
# measured against this tuple, so the predicate is checkable rather than impressionistic:
# every member gets a section in the rendered index, an empty one included.
ORGAN_CLASSES: tuple[str, ...] = (
    "agent", "command", "skill", "workflow", "rule",
    "session-hook", "git-hook", "plugin",
)

_CLASS_BLURB = {
    "agent": "subagents dispatched with their own context window",
    "command": "operator-invoked slash commands",
    "skill": "model-invoked skills (the model decides when to load one)",
    "workflow": "multi-agent workflow specifications",
    "rule": "always-on instruction files loaded into every session",
    "session-hook": "Claude Code lifecycle hooks (SessionStart / Stop / PreToolUse / …)",
    "git-hook": "git-stage gates declared in `.pre-commit-config.yaml`",
    "plugin": "installable plugins that carry organs of their own",
}

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
# A roster line names its organ before the em-dash separator or an opening parenthesis:
#   "/ship — merge the current branch…"  ->  "/ship"
#   "Stop: propose_closures (tier1…)"    ->  "Stop: propose_closures"
_ROSTER_NAME_RE = re.compile(r"^(.*?)(?:\s+[—-]\s|\s\()")
_MANIFEST_VERSION_RE = re.compile(r"^manifest-v(\d+)\.(\d+)\.(\d+)\.yaml$")
# The script a hook command invokes, used as the hook's display name: the last path-ish
# token ending in a known script extension.
_SCRIPT_TOKEN_RE = re.compile(r"([\w.-]+\.(?:py|ps1|js|sh))")
_EXT_RE = re.compile(r"\.(?:py|ps1|js|sh)$")

_STATUS_ARMED = "ARMED"
_STATUS_RETIRED = "RETIRED"
_STATUS_DECLARED = "DECLARED"
_UNPARSED = "(unparsed)"


class Organ(NamedTuple):
    """One row of the index — the six columns the [#132] row names, in its order."""

    name: str
    cls: str
    trigger: str
    source: str
    distribution: str
    status: str


# --------------------------------------------------------------------------------------
# small readers (each degrades LOUDLY — a source it cannot parse yields a visible row or
# an explicit absence, never a silently shorter index)
# --------------------------------------------------------------------------------------

def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _frontmatter_field(text: str, field: str) -> str | None:
    """A top-level `field: value` scalar from a leading YAML frontmatter block, or None.

    Regex-simple by design, matching `gen_claude_rosters._frontmatter_field`: organ
    frontmatter here is flat, and a folded `description: >` block is read as empty rather
    than mis-joined (only `name`/`description` are consumed, and `description` is used
    solely for the RETIRED derivation below).
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    for line in m.group(1).splitlines():
        if line.startswith(f"{field}:"):
            return line[len(field) + 1:].strip() or None
    return None


def _status_from_description(description: str | None) -> str:
    """RETIRED iff the organ's own description says so — derived, never hand-flagged.

    `/override`'s frontmatter opens `RETIRED (ADR-85 amendment …)`, which is the organ
    declaring its own status at the source. Reading it here means a retirement recorded
    once shows up in the index without a second edit anywhere.
    """
    if description and description.strip().upper().startswith("RETIRED"):
        return _STATUS_RETIRED
    return _STATUS_ARMED


def _rel(path: Path, root: Path) -> str:
    """Repo-relative POSIX path — stable across platforms (the gate compares bytes)."""
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _script_name(command: str) -> str | None:
    """The script a hook command runs, e.g. `propose_closures.py`, or None."""
    hits = _SCRIPT_TOKEN_RE.findall(command)
    return hits[-1] if hits else None


# --------------------------------------------------------------------------------------
# collectors — one per organ source
# --------------------------------------------------------------------------------------

def collect_agents(root: Path) -> list[Organ]:
    out = []
    for p in sorted((root / ".claude" / "agents").glob("*.md")):
        text = _read(p) or ""
        name = _frontmatter_field(text, "name") or p.stem
        out.append(Organ(name, "agent", "subagent-dispatch", _rel(p, root), "hub",
                         _status_from_description(_frontmatter_field(text, "description"))))
    return out


def collect_commands(root: Path) -> list[Organ]:
    out = []
    for p in sorted((root / ".claude" / "commands").glob("*.md")):
        text = _read(p) or ""
        name = _frontmatter_field(text, "name") or p.stem
        out.append(Organ(f"/{name}", "command", "operator-invoke", _rel(p, root), "hub",
                         _status_from_description(_frontmatter_field(text, "description"))))
    return out


def collect_skills(root: Path) -> list[Organ]:
    out = []
    for d in sorted((root / ".claude" / "skills").glob("*")):
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            continue
        text = _read(skill_md) or ""
        name = _frontmatter_field(text, "name") or d.name
        out.append(Organ(name, "skill", "model-invoke", _rel(skill_md, root), "hub",
                         _status_from_description(_frontmatter_field(text, "description"))))
    return out


def collect_workflows(root: Path) -> list[Organ]:
    d = root / ".claude" / "workflows"
    return [Organ(p.name, "workflow", "operator (Workflow) or cloud Routine",
                  _rel(p, root), "hub", _STATUS_ARMED)
            for p in sorted(d.glob("*")) if p.is_file()]


def collect_rules(root: Path) -> list[Organ]:
    d = root / ".claude" / "rules"
    return [Organ(p.stem, "rule", "context-load (every session)", _rel(p, root), "hub",
                  _STATUS_ARMED)
            for p in sorted(d.glob("*.md"))]


def _settings(root: Path) -> tuple[dict, bool]:
    """(parsed .claude/settings.json, parsed_ok). Never raises — an unreadable settings
    file produces a visible `(unparsed)` row rather than a silently hook-less index."""
    text = _read(root / ".claude" / "settings.json")
    if text is None:
        return {}, True          # absent is a real, honest answer: no session hooks here
    try:
        return json.loads(text), True
    except (json.JSONDecodeError, ValueError):
        return {}, False


def collect_session_hooks(root: Path) -> list[Organ]:
    data, ok = _settings(root)
    rel = ".claude/settings.json"
    if not ok:
        return [Organ("(settings.json unparseable)", "session-hook", _UNPARSED, rel,
                      "hub", _UNPARSED)]
    return _hooks_from_mapping(data.get("hooks") or {}, rel, "hub", _STATUS_ARMED)


def _hooks_from_mapping(hooks: dict, source: str, distribution: str,
                        status: str) -> list[Organ]:
    """Claude Code's `{event: [{matcher, hooks: [{command}]}]}` shape -> Organ rows.

    Name is `<Event>: <script>`; trigger is the event plus its matcher when one narrows
    it, which is the distinction Ch2's Trigger column makes by hand.
    """
    out = []
    for event in sorted(hooks):
        for group in hooks[event] or []:
            matcher = (group.get("matcher") or "").strip()
            for hook in group.get("hooks") or []:
                command = hook.get("command") or ""
                script = _script_name(command) or "(inline command)"
                trigger = f"{event} ({matcher})" if matcher else event
                out.append(Organ(f"{event}: {script}", "session-hook", trigger, source,
                                 distribution, status))
    return out


def collect_git_hooks(root: Path) -> list[Organ]:
    """Every hook id in `.pre-commit-config.yaml`, with its stage as the trigger.

    Stage resolution mirrors pre-commit's own: a hook's explicit `stages:` wins, else the
    file's `default_stages:`, else pre-commit's built-in default. Rendering the resolved
    stage (rather than the declared one) is the point — a gate's trigger is what it does,
    not what it omits to say.
    """
    text = _read(root / ".pre-commit-config.yaml")
    rel = ".pre-commit-config.yaml"
    if text is None:
        return []
    try:
        data = yaml.safe_load(text) or {}
    except yaml.YAMLError:
        return [Organ("(.pre-commit-config.yaml unparseable)", "git-hook", _UNPARSED, rel,
                      "pre-commit", _UNPARSED)]
    default_stages = data.get("default_stages") or ["pre-commit"]
    out = []
    for repo in data.get("repos") or []:
        origin = repo.get("repo", "local")
        for hook in repo.get("hooks") or []:
            hid = hook.get("id")
            if not hid:
                continue
            stages = hook.get("stages") or default_stages
            source = rel if origin == "local" else f"{rel} → {origin}"
            out.append(Organ(str(hid), "git-hook", ", ".join(str(s) for s in stages),
                             source, "pre-commit", _STATUS_ARMED))
    return sorted(out)


def _enabled_plugin_names(root: Path) -> set[str]:
    """Plugin names enabled in settings.json, stripped of their `@marketplace` suffix."""
    data, ok = _settings(root)
    if not ok:
        return set()
    return {str(k).split("@", 1)[0] for k, v in (data.get("enabledPlugins") or {}).items()
            if v}


def collect_plugins(root: Path) -> list[Organ]:
    """Each `plugins/<name>/` — the plugin itself plus the commands and hooks it carries.

    Status is DERIVED from settings.json `enabledPlugins` and INHERITED by everything the
    plugin ships: a disabled plugin's `/ship` is present on disk and reaches nothing, and
    an index that called it ARMED would be making exactly the claim this file exists to
    stop making.
    """
    enabled = _enabled_plugin_names(root)
    out: list[Organ] = []
    for plugin_json in sorted((root / "plugins").glob("*/.claude-plugin/plugin.json")):
        plugin_dir = plugin_json.parent.parent
        text = _read(plugin_json) or ""
        try:
            meta = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            meta = {}
        name = str(meta.get("name") or plugin_dir.name)
        version = str(meta.get("version") or "")
        status = _STATUS_ARMED if name in enabled else _STATUS_DECLARED
        trigger = ("enabled in .claude/settings.json" if status == _STATUS_ARMED
                   else "declared, not enabled here")
        if version:
            trigger = f"{trigger} (v{version})"
        out.append(Organ(name, "plugin", trigger, _rel(plugin_json, root), "plugin",
                         status))
        for cmd in sorted((plugin_dir / "commands").glob("*.md")):
            ctext = _read(cmd) or ""
            cname = _frontmatter_field(ctext, "name") or cmd.stem
            cstatus = status if status != _STATUS_ARMED else _status_from_description(
                _frontmatter_field(ctext, "description"))
            out.append(Organ(f"/{cname}", "command", "operator-invoke", _rel(cmd, root),
                             "plugin", cstatus))
        hooks_json = plugin_dir / "hooks" / "hooks.json"
        htext = _read(hooks_json)
        if htext is not None:
            try:
                hdata = json.loads(htext)
            except (json.JSONDecodeError, ValueError):
                hdata = {}
            out += _hooks_from_mapping(hdata.get("hooks") or {}, _rel(hooks_json, root),
                                       "plugin", status)
    return out


def collect_declared(root: Path) -> list[Organ]:
    """The `ecosystem/organ-registry.yaml` rows — the off-repo (L0) organs.

    A malformed row renders with `(unparsed)` in the field it is missing rather than being
    dropped: a registry entry that vanishes because of a typo is the failure mode this
    whole index exists to remove.
    """
    text = _read(root / "ecosystem" / "organ-registry.yaml")
    if text is None:
        return []
    try:
        data = yaml.safe_load(text) or {}
    except yaml.YAMLError:
        return [Organ("(organ-registry.yaml unparseable)", "rule", _UNPARSED,
                      "ecosystem/organ-registry.yaml", "L0", _UNPARSED)]
    out = []
    for row in data.get("organs") or []:
        if not isinstance(row, dict):
            continue
        cls = str(row.get("class") or _UNPARSED)
        out.append(Organ(
            str(row.get("name") or _UNPARSED),
            cls if cls in ORGAN_CLASSES else _UNPARSED,
            str(row.get("trigger") or _UNPARSED),
            str(row.get("source") or _UNPARSED),
            str(row.get("distribution") or "L0"),
            str(row.get("status") or _UNPARSED),
        ))
    return out


# --------------------------------------------------------------------------------------
# the `deployed` annotation
# --------------------------------------------------------------------------------------

def resolve_manifest_path(root: Path) -> Path | None:
    """The MAX-semver `deploy/manifest-v*.yaml`, or None. Mirrors
    `gen_methodology_roster.resolve_manifest_path`, but returns None instead of raising —
    this generator degrades to un-annotated rows rather than failing the gate."""
    candidates: list[tuple[tuple[int, ...], Path]] = []
    for p in sorted((root / "deploy").glob("manifest-v*.yaml")):
        m = _MANIFEST_VERSION_RE.match(p.name)
        if m:
            candidates.append((tuple(int(g) for g in m.groups()), p))
    if not candidates:
        return None
    candidates.sort()
    return candidates[-1][1]


def deployed_organ_names(root: Path) -> set[str]:
    """Organ names the current manifest declares deployable, from `roster[].line`.

    HONEST LIMIT, stated because the annotation looks stronger than it is: this is a
    NAME-TOKEN match against the leading segment of each active roster line, not a
    resolved artifact identity. A roster line re-worded to lead with different text
    silently drops its annotation. The `roster-freshness` hook already gates the roster
    against the manifest, so the drift window is roster-line PHRASING only — and the
    annotation is decoration on a row that is otherwise fully derived.

    One phrasing difference is real today and is absorbed rather than tolerated (see
    `_deployed_match`): the manifest writes the Tier-1 Stop hook as
    `Stop: propose_closures`, while the hook's own command names `propose_closures.py`.
    Matching also on the extension-stripped form keeps that row annotated.
    """
    path = resolve_manifest_path(root)
    if path is None:
        return set()
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):
        return set()
    names: set[str] = set()
    for comp in data.get("components") or []:
        if comp.get("status") != "active":
            continue
        roster = comp.get("roster")
        if not isinstance(roster, dict):
            continue
        line = str(roster.get("line") or "").strip()
        if not line:
            continue
        m = _ROSTER_NAME_RE.match(line)
        names.add((m.group(1) if m else line).strip())
    return names


def _deployed_match(name: str, deployed: set[str]) -> bool:
    """Is this organ named by an active manifest roster line?

    Exact match first, then the extension-stripped form — the manifest names the Tier-1
    Stop hook `Stop: propose_closures` while the hook command names `propose_closures.py`,
    and an index that dropped the `deployed` mark over a `.py` would be reporting a
    distribution fact wrongly rather than reporting a phrasing difference.
    """
    return name in deployed or _EXT_RE.sub("", name) in deployed


# --------------------------------------------------------------------------------------
# assembly + render
# --------------------------------------------------------------------------------------

def collect_organs(root: Path = _REPO_ROOT) -> list[Organ]:
    """Every organ, from every source, with the `deployed` annotation applied.

    Order is the render order: class order per ORGAN_CLASSES, then name within a class.
    Deterministic by construction — every collector sorts, and nothing reads `~`.
    """
    organs: list[Organ] = []
    for collector in (collect_agents, collect_commands, collect_skills, collect_workflows,
                      collect_rules, collect_session_hooks, collect_git_hooks,
                      collect_plugins, collect_declared):
        organs += collector(root)

    deployed = deployed_organ_names(root)
    annotated = [
        o._replace(distribution=f"{o.distribution} · deployed")
        if _deployed_match(o.name, deployed) else o
        for o in organs
    ]
    class_rank = {c: i for i, c in enumerate(ORGAN_CLASSES)}
    annotated.sort(key=lambda o: (class_rank.get(o.cls, len(ORGAN_CLASSES)), o.name,
                                  o.source))
    return annotated


def _cell(value: str) -> str:
    """Markdown-table-safe cell: a literal pipe would silently split the row."""
    return value.replace("|", "\\|")


def render_index(root: Path = _REPO_ROOT) -> str:
    organs = collect_organs(root)
    by_class: dict[str, list[Organ]] = {c: [] for c in ORGAN_CLASSES}
    for o in organs:
        by_class.setdefault(o.cls, []).append(o)

    coverage = " · ".join(f"{c} {len(by_class.get(c, []))}" for c in ORGAN_CLASSES)
    out = [
        "# Organ index — generated inventory of every organ in this repo",
        "",
        "> **What fires, from where, and does it reach reality today.** Machine-derived",
        "> from the organ sources themselves — `.claude/{agents,commands,skills,workflows,",
        "> rules}`, `.claude/settings.json`, `.pre-commit-config.yaml`, the",
        "> `tier1-lifecycle` plugin manifest — plus the DECLARED user-level (`L0`) rows in",
        "> `ecosystem/organ-registry.yaml`. Vocabulary is `ARCHITECTURE.md` Ch2's:",
        "> **distribution** is Ch2's Layer (`L0` · `hub` · `plugin` · `pre-commit`),",
        "> **status** is Ch2's Status (`ARMED` · `RETIRED` · `DECLARED`), and",
        "> `· deployed` marks an organ the current `deploy/manifest-v*.yaml` ships to",
        "> consumers.",
        ">",
        "> **This index does NOT carry failure posture** (fail-closed / fail-soft /",
        "> propose-only). That is a judgement about an organ's code, derivable from no",
        "> frontmatter block or hook id; `ARCHITECTURE.md` Ch2 carries it by hand and stays",
        "> the source for it. Read this file for *what exists and what fires it*, Ch2 for",
        "> *what happens when it says no*.",
        ">",
        "> The `L0` rows are DECLARED, not walked: reading the operator's `~/.claude` live",
        "> would make these bytes machine-dependent and the freshness gate unholdable on",
        "> any other host. `python scripts/generate_organ_index.py --probe-user-level` is",
        "> the non-gating diagnostic that compares the registry against a live `~/.claude`.",
        ">",
        "> Do not hand-edit. Regenerate: `python scripts/generate_organ_index.py --write`",
        "",
        _GENERATED_NOTE,
        "",
        f"**{len(organs)} organs across {len(ORGAN_CLASSES)} classes.**",
        "",
        f"**Coverage:** {coverage}",
    ]
    for cls in ORGAN_CLASSES:
        rows = by_class.get(cls, [])
        out += ["", f"## {cls}", "", f"_{_CLASS_BLURB.get(cls, '')}_", ""]
        if not rows:
            out.append("_(no organ in this class)_")
            continue
        out += ["| Name | Class | Trigger | Source | Distribution | Status |",
                "|---|---|---|---|---|---|"]
        for o in rows:
            out.append(
                f"| `{_cell(o.name)}` | {_cell(o.cls)} | {_cell(o.trigger)} "
                f"| `{_cell(o.source)}` | {_cell(o.distribution)} | {_cell(o.status)} |")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------------------

def _cmd_write(root: Path) -> int:
    target = root / _TARGET_REL
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_index(root), encoding="utf-8", newline="\n")
    print(f"generate_organ_index: wrote {_TARGET_REL.as_posix()}")
    return 0


def _cmd_check(root: Path) -> int:
    """Regen-and-diff drift check. Exit 0 clean / 1 stale (+unified diff) / 2 target
    missing — the same three-way contract the peer generators' freshness hooks run."""
    target = root / _TARGET_REL
    rel = _TARGET_REL.as_posix()
    if not target.exists():
        print(f"error: {rel} not found — generate it: "
              f"python scripts/generate_organ_index.py --write", file=sys.stderr)
        return 2
    fresh = render_index(root)
    current = target.read_text(encoding="utf-8")
    if current == fresh:
        return 0
    diff = "".join(difflib.unified_diff(
        current.splitlines(keepends=True), fresh.splitlines(keepends=True),
        fromfile=f"{rel} (current)", tofile=f"{rel} (fresh)"))
    print(diff, file=sys.stderr)
    print(f"generate_organ_index: {rel} is stale vs the organ sources — regenerate: "
          f"python scripts/generate_organ_index.py --write", file=sys.stderr)
    return 1


def _live_user_level(home: Path) -> list[tuple[str, str]]:
    """[(name, source), …] read from a live `~/.claude` — commands, skills, agents, rules.

    Names are rendered the way the registry writes them (`/name` for a command) so the two
    sets compare directly. Read-only; a missing directory is simply absent.
    """
    base = home / ".claude"
    found: list[tuple[str, str]] = []
    for sub, fmt in (("commands", "/{}"), ("agents", "{}"), ("rules", "{}")):
        for p in sorted((base / sub).glob("*.md")):
            found.append((fmt.format(p.stem), f"~/.claude/{sub}/{p.name}"))
    for d in sorted((base / "skills").glob("*")):
        if (d / "SKILL.md").is_file():
            found.append((d.name, f"~/.claude/skills/{d.name}/"))
    return found


# The classes `_live_user_level` can actually inventory. A session hook is a command
# STRING inside `~/.claude/settings.json`, not a file the probe can enumerate, so
# comparing those rows would report every one of them as missing — false drift, which is
# worse than the silence it replaces.
_PROBEABLE_CLASSES = frozenset({"command", "agent", "rule", "skill"})


def _cmd_probe_user_level(root: Path, home: Path) -> int:
    """Diagnostic: live `~/.claude` vs the declared registry. Writes nothing, gates
    nothing, ALWAYS exits 0 — a machine-dependent reading has no place in a check."""
    declared = {o.name for o in collect_declared(root) if o.cls in _PROBEABLE_CLASSES}
    live = _live_user_level(home)
    live_names = {n for n, _ in live}

    print(f"generate_organ_index --probe-user-level (home: {home})")
    print("  read-only diagnostic; wired into no gate; writes nothing")
    undeclared = [(n, s) for n, s in live if n not in declared]
    absent = sorted(n for n in declared if n not in live_names)
    for name, source in undeclared:
        print(f"  undeclared: {name}  ({source}) — present in ~/.claude, "
              f"absent from ecosystem/organ-registry.yaml")
    for name in absent:
        print(f"  declared but absent: {name} — in the registry, not found under "
              f"{home / '.claude'}")
    if not undeclared and not absent:
        print("  no drift: every probeable ~/.claude organ matches the registry")
    print("  SCOPE: commands / agents / rules / skills only. Session hooks in "
          "~/.claude/settings.json are declared-only and NOT probed — they are command "
          "strings, not a file inventory, so this report says nothing about them.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_organ_index",
        description="Generate/check docs/ORGAN-INDEX.md (the machine-derived organ roster)")
    parser.add_argument("--write", action="store_true",
                        help="regenerate the index from the organ sources")
    parser.add_argument("--check", action="store_true",
                        help="check the index against the sources (default action)")
    parser.add_argument("--probe-user-level", action="store_true",
                        help="read-only drift report: live ~/.claude vs the declared "
                             "registry (writes nothing, always exits 0)")
    parser.add_argument("--repo-root", default=None,
                        help="repo root to operate on (defaults to this script's repo)")
    parser.add_argument("--home", default=None,
                        help="home directory for --probe-user-level (defaults to ~)")
    args = parser.parse_args(argv)

    root = Path(args.repo_root).resolve() if args.repo_root else _REPO_ROOT
    if args.probe_user_level:
        home = Path(args.home).resolve() if args.home else Path.home()
        return _cmd_probe_user_level(root, home)
    if args.write:
        return _cmd_write(root)
    return _cmd_check(root)


if __name__ == "__main__":
    sys.exit(main())
