#!/usr/bin/env python
"""quality_requirements.py -- the reader, validator and renderer for the quality register.

WHAT THIS MAKES TRUE. `ecosystem/quality-requirements.yaml` is a file until something reads
it; AN2-1's whole complaint about the previous state was that requirements lived somewhere
nothing consulted. This module is the consulting. It is wired as the
`quality-requirements-freshness` pre-commit hook, so a register that breaks its own schema,
or an ARCHITECTURE section that no longer matches the register, refuses the commit.

THE SCHEMA IS THE HONESTY MECHANISM, and it is asymmetric on purpose:

  * `status: measured` REQUIRES `organ` and `trip_test`.
  * `status: candidate` FORBIDS both -- not "omits", forbids. A candidate that names an
    organ is the exact failure the register exists to prevent (a requirement dressed as
    enforcement), so the validator refuses it rather than ignoring the extra key.

The heavier half of the proof is NOT here. `schema_defects` can see that a `measured` entry
names a trip-test; it cannot see whether that trip-test would notice the organ being
removed. `tests/test_quality_requirements.py` runs each trip against a NEUTERED stand-in
for its organ and requires it to go RED -- a trip-test that passes with the organ disabled
is proving nothing, and it is refused there. Stating the split here so a reader of this
module does not mistake the schema pass for the whole verdict.

WHAT THIS MODULE DOES NOT DO, said plainly because the neighbouring organs do it and the
distinction is easy to lose: it computes NO edges. It reads a DECLARED relation --
`organ:` and `trip_test:` are written by hand in the register -- and resolves each side to
a path. It does not scan source text to infer which test covers which module (that is
`scripts/impacted_tests.py`), it does not derive citation or generation edges (that is
`scripts/file_purpose_graph.py`), and adding such a derivation here would be a new private
edge computation rather than a reader.

RENDERING. One marker-delimited section in `ARCHITECTURE.md`, regenerated from the register
and compared byte-for-byte -- the same regen-and-diff idiom as `codemap-freshness` and the
generated indices, so the rendered section cannot drift from the data and cannot be
hand-edited into agreement.

Usage:
    python scripts/quality_requirements.py check              # schema + render agreement
    python scripts/quality_requirements.py render --write     # rewrite the ARCHITECTURE block
"""

from __future__ import annotations

import difflib
import logging
import re
import sys
from pathlib import Path
from typing import Any, Iterable, Optional

import click
import yaml

_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent

REGISTER_REL = "ecosystem/quality-requirements.yaml"
ARCHITECTURE_REL = "ARCHITECTURE.md"

START_MARKER = "<!-- QUALITY-REQUIREMENTS:START -->"
END_MARKER = "<!-- QUALITY-REQUIREMENTS:END -->"
GENERATED_NOTE = (
    "<!-- generated by scripts/quality_requirements.py from "
    "ecosystem/quality-requirements.yaml; do not edit by hand -->"
)

STATUS_MEASURED = "measured"
STATUS_CANDIDATE = "candidate"
STATUSES = (STATUS_MEASURED, STATUS_CANDIDATE)

#: Fields every entry carries, whatever its status.
COMMON_FIELDS = ("id", "attribute", "status", "statement", "metric", "incident", "source")
#: Fields a `measured` entry carries and a `candidate` entry is refused for carrying.
MEASURED_ONLY_FIELDS = ("organ", "trip_test")
#: Fields that are permitted anywhere and required nowhere.
OPTIONAL_FIELDS = ("note",)

_ID_RE = re.compile(r"^QR-[A-Z]+-\d{3}$")
_TRIP_RE = re.compile(r"^(?P<file>tests/[A-Za-z0-9_./-]+\.py)::(?P<test>[A-Za-z0-9_]+)$")

logger = logging.getLogger("quality-requirements")


class RegisterError(RuntimeError):
    """The register could not be read at all -- absent, unparseable, or the wrong shape."""


# ---------------------------------------------------------------------------- loading


def register_path(repo_root: Optional[Path] = None) -> Path:
    return Path(repo_root or _REPO_ROOT) / REGISTER_REL


def load(repo_root: Optional[Path] = None) -> dict[str, Any]:
    """Parse the register and return its mapping, or raise `RegisterError`.

    An absent or unparseable register raises rather than returning an empty mapping: a
    reader that degrades to "no requirements" turns a broken file into a clean report,
    which is the same class of lie the register's own `candidate` rule refuses.
    """
    path = register_path(repo_root)
    if not path.exists():
        raise RegisterError(f"{REGISTER_REL} is absent -- the register cannot be read")
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise RegisterError(f"{REGISTER_REL} is not parseable YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise RegisterError(f"{REGISTER_REL} does not parse to a mapping")
    return data


def requirements(register: dict[str, Any]) -> list[dict[str, Any]]:
    rows = register.get("requirements")
    if not isinstance(rows, list):
        raise RegisterError(f"{REGISTER_REL} carries no `requirements:` list")
    return [row for row in rows if isinstance(row, dict)]


def measured(register: dict[str, Any]) -> list[dict[str, Any]]:
    return [r for r in requirements(register) if r.get("status") == STATUS_MEASURED]


def candidates(register: dict[str, Any]) -> list[dict[str, Any]]:
    return [r for r in requirements(register) if r.get("status") == STATUS_CANDIDATE]


def parse_trip(value: str) -> tuple[str, str]:
    """`tests/x.py::test_y` -> `("tests/x.py", "test_y")`, or raise `RegisterError`."""
    match = _TRIP_RE.match(str(value))
    if not match:
        raise RegisterError(
            f"trip_test {value!r} is not in `tests/<file>.py::<test function>` form")
    return match.group("file"), match.group("test")


# ---------------------------------------------------------------------------- schema


def schema_defects(register: dict[str, Any]) -> list[str]:
    """Every way the register breaks its own contract, as reader-facing sentences.

    Empty list means the register is well-formed. It does NOT mean the measured entries
    are proven -- see this module's docstring for where that half lives.
    """
    defects: list[str] = []
    attributes = register.get("attributes")
    if not isinstance(attributes, dict) or not attributes:
        return [f"{REGISTER_REL} carries no `attributes:` mapping"]

    floor = register.get("floor")
    if not isinstance(floor, dict) or not str(floor.get("tier", "")).strip():
        defects.append(
            "the register declares no `floor:` block with a `tier:` -- a component with no "
            "floor declaration cannot tell a consumer whether it is owed this register")
    elif not str(floor.get("reason", "")).strip():
        defects.append("the `floor:` block declares a tier with no `reason:`")

    try:
        rows = requirements(register)
    except RegisterError as exc:
        return defects + [str(exc)]
    if not rows:
        return defects + [f"{REGISTER_REL} carries zero requirements"]

    seen: set[str] = set()
    for index, row in enumerate(rows, start=1):
        rid = str(row.get("id", "")).strip()
        where = rid or f"entry {index}"
        if not _ID_RE.match(rid):
            defects.append(f"{where}: id is not in `QR-<ATTRIBUTE-CODE>-<NNN>` form")
        if rid in seen:
            defects.append(f"{where}: duplicate id -- an id is a citation target and is unique")
        seen.add(rid)

        attribute = row.get("attribute")
        if attribute not in attributes:
            defects.append(
                f"{where}: attribute {attribute!r} is outside the declared set "
                f"{sorted(attributes)}")
        elif rid and not rid.startswith(f"QR-{attributes[attribute]}-"):
            defects.append(
                f"{where}: id does not carry its attribute's code "
                f"{attributes[attribute]!r} -- the id and the attribute disagree")

        status = row.get("status")
        if status not in STATUSES:
            defects.append(f"{where}: status {status!r} is outside {list(STATUSES)}")

        for field in COMMON_FIELDS:
            if not str(row.get(field, "")).strip():
                defects.append(f"{where}: `{field}` is absent or empty")

        unknown = set(row) - set(COMMON_FIELDS) - set(MEASURED_ONLY_FIELDS) - set(OPTIONAL_FIELDS)
        if unknown:
            defects.append(f"{where}: unknown field(s) {sorted(unknown)}")

        if status == STATUS_MEASURED:
            for field in MEASURED_ONLY_FIELDS:
                if not str(row.get(field, "")).strip():
                    defects.append(
                        f"{where}: status is `measured` and `{field}` is absent -- a measured "
                        f"entry names the thing that enforces it and the proof that it refuses")
            trip = row.get("trip_test")
            if trip:
                try:
                    parse_trip(trip)
                except RegisterError as exc:
                    defects.append(f"{where}: {exc}")
        elif status == STATUS_CANDIDATE:
            for field in MEASURED_ONLY_FIELDS:
                if field in row:
                    defects.append(
                        f"{where}: status is `candidate` and it carries `{field}` -- a "
                        f"candidate that names an enforcement is the failure this register "
                        f"exists to prevent. Promote it to `measured` with a trip-test, or "
                        f"drop the field")
    return defects


def unresolved_organs(register: dict[str, Any],
                      repo_root: Optional[Path] = None) -> list[str]:
    """Measured entries whose `organ` or `trip_test` file does not exist in the tree."""
    root = Path(repo_root or _REPO_ROOT)
    out: list[str] = []
    for row in measured(register):
        rid = row.get("id", "?")
        organ = str(row.get("organ", "")).strip()
        if organ and not (root / organ).exists():
            out.append(f"{rid}: organ {organ!r} does not resolve to a file in the tree")
        trip = str(row.get("trip_test", "")).strip()
        if not trip:
            continue
        try:
            trip_file, _ = parse_trip(trip)
        except RegisterError as exc:
            out.append(f"{rid}: {exc}")
            continue
        if not (root / trip_file).exists():
            out.append(f"{rid}: trip-test file {trip_file!r} does not exist")
    return out


# ---------------------------------------------------------------------------- rendering


def _one_line(text: Any) -> str:
    """Collapse a folded YAML scalar to one table cell, escaping the column separator."""
    return " ".join(str(text).split()).replace("|", "\\|")


def _counts(rows: Iterable[dict[str, Any]]) -> tuple[int, int, int]:
    rows = list(rows)
    m = sum(1 for r in rows if r.get("status") == STATUS_MEASURED)
    c = sum(1 for r in rows if r.get("status") == STATUS_CANDIDATE)
    return len(rows), m, c


def render_section(register: dict[str, Any]) -> str:
    """The ARCHITECTURE body between the markers -- the whole register in one screen.

    One row per requirement, ordered as the register writes them, so a reader scanning the
    table meets the attributes grouped. The STATEMENT is the only prose in the table; the
    metric, the incident and the notes stay in the register, because a section that
    reproduced them would be a copy that rots rather than a view that renders.
    """
    rows = requirements(register)
    total, n_measured, n_candidate = _counts(rows)
    floor = register.get("floor") or {}
    lines = [
        f"Register: `{REGISTER_REL}` (v{register.get('register_version', '?')}) — "
        f"{total} requirement(s), {n_measured} measured, {n_candidate} candidate. "
        f"Floor tier: {floor.get('tier', '?')}.",
        "",
        "A **measured** row names the organ that enforces it and the trip-test that proves the "
        "organ refuses; the trip-test is itself run against a neutered organ and has to go RED, "
        "so a trip-test that passes unconditionally is refused rather than counted. A "
        "**candidate** row carries neither field — a requirement with no enforcement is recorded "
        "as one instead of being attached to the nearest plausible organ.",
        "",
        "| id | attribute | status | requirement | organ | trip-test |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        trip = str(row.get("trip_test", "")).strip()
        trip_cell = f"`{trip.split('::')[-1]}`" if trip else "—"
        organ = str(row.get("organ", "")).strip()
        organ_cell = f"`{organ}`" if organ else "—"
        lines.append(
            f"| `{row.get('id', '?')}` | {row.get('attribute', '?')} | "
            f"{row.get('status', '?')} | {_one_line(row.get('statement', ''))} | "
            f"{organ_cell} | {trip_cell} |")
    lines += [
        "",
        "TRIGGER: the `quality-requirements-freshness` pre-commit hook (schema + this section's "
        "regen-and-diff) and `tests/test_quality_requirements.py` (organ resolution + the "
        "neutered-organ leg). CONSUMERS: this section, and the methodology floor, which carries "
        "the register's discipline to every consumer repo.",
        GENERATED_NOTE,
    ]
    return "\n".join(lines)


def _split_architecture(text: str) -> tuple[str, str]:
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise RegisterError(
            f"{ARCHITECTURE_REL} carries no well-formed "
            f"{START_MARKER} / {END_MARKER} pair -- the rendered section has no home")
    return text[: start + len(START_MARKER)], text[end:]


def current_section(repo_root: Optional[Path] = None) -> str:
    """The committed body between the markers, stripped of the surrounding newlines."""
    path = Path(repo_root or _REPO_ROOT) / ARCHITECTURE_REL
    text = path.read_text(encoding="utf-8")
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise RegisterError(
            f"{ARCHITECTURE_REL} carries no well-formed marker pair for the register section")
    return text[start + len(START_MARKER): end].strip("\n")


def render_defects(repo_root: Optional[Path] = None) -> list[str]:
    """A unified diff of committed-vs-regenerated, or an empty list when they agree."""
    register = load(repo_root)
    want = render_section(register)
    have = current_section(repo_root)
    if want == have:
        return []
    diff = difflib.unified_diff(
        have.splitlines(), want.splitlines(),
        fromfile=f"{ARCHITECTURE_REL} (committed)", tofile="regenerated from the register",
        lineterm="")
    return [f"{ARCHITECTURE_REL}'s register section is stale versus "
            f"{REGISTER_REL}:"] + list(diff)


def write_section(repo_root: Optional[Path] = None) -> bool:
    """Splice the regenerated section into ARCHITECTURE.md. True when bytes changed."""
    root = Path(repo_root or _REPO_ROOT)
    path = root / ARCHITECTURE_REL
    text = path.read_text(encoding="utf-8")
    head, tail = _split_architecture(text)
    body = render_section(load(root))
    rebuilt = f"{head}\n{body}\n{tail}"
    if rebuilt == text:
        return False
    path.write_text(rebuilt, encoding="utf-8", newline="\n")
    return True


# ---------------------------------------------------------------------------- CLI


@click.group()
def cli() -> None:
    """The quality-requirements register ([#765], AN2-1)."""


@cli.command("check")
@click.option("--repo-root", default=str(_REPO_ROOT), help="Repository root to check.")
def check_cmd(repo_root: str) -> None:
    """REFUSE a register that breaks its schema, or a stale ARCHITECTURE section.

    The refusal names every defect rather than the first, because a register is edited as a
    whole and a reader fixing one line at a time pays a commit cycle per line.
    """
    root = Path(repo_root).resolve()
    try:
        register = load(root)
    except RegisterError as exc:
        raise click.ClickException(str(exc)) from exc
    problems = schema_defects(register)
    problems += unresolved_organs(register, root)
    problems += render_defects(root)
    if problems:
        raise click.ClickException(
            "REFUSED -- the quality register does not hold.\n\n"
            + "\n".join(f"  {line}" for line in problems)
            + "\n\nRegenerate the section with: "
              "python scripts/quality_requirements.py render --write")
    total, n_measured, n_candidate = _counts(requirements(register))
    logger.info("quality-requirements: OK -- %d requirement(s), %d measured, %d candidate",
                total, n_measured, n_candidate)


@cli.command("render")
@click.option("--repo-root", default=str(_REPO_ROOT), help="Repository root to render into.")
@click.option("--write", is_flag=True, default=False,
              help="Rewrite the ARCHITECTURE section in place (default: print it).")
def render_cmd(repo_root: str, write: bool) -> None:
    """Render the register into ARCHITECTURE.md's marker-delimited section."""
    root = Path(repo_root).resolve()
    try:
        if write:
            changed = write_section(root)
            logger.info("quality-requirements: %s",
                        "ARCHITECTURE.md section rewritten" if changed
                        else "ARCHITECTURE.md section already current")
        else:
            click.echo(render_section(load(root)))
    except RegisterError as exc:
        raise click.ClickException(str(exc)) from exc


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stdout)
    cli()


if __name__ == "__main__":
    main()
