#!/usr/bin/env python
"""worktree_import_proof.py — does THIS checkout's pytest import THIS checkout's source? ([#429])

WHAT THIS IS
------------
[#429]'s done-when, verbatim: *"a satellite can provision a worktree AND prove by a runnable
check that its pytest imports THAT worktree's source"*. This module is that check. It is the
half the row calls unbuilt, and it is deliberately the FIRST thing built, because leg (b) —
the per-worktree venv — is a remedy whose absence is silent without it.

THE FAILURE IT EXISTS TO CATCH, stated once. A shared editable install lives in an interpreter's
site-packages and points at ONE checkout. Inside a git worktree of the same repo, `import pkg`
therefore resolves to the PRIMARY checkout's source. The worktree's `pytest` then exercises code
the lane never touched and reports the result against the lane's branch: **green tests about the
wrong tree, with nothing in the output saying so.** That is the exact silent-failure class this
fleet hunts, and no amount of documentation survives it — a note in a doc does not fail a build.

WHY IT RUNS PYTEST RATHER THAN JUST IMPORTING. The row says *its pytest*, not *its interpreter*,
and the distinction is load-bearing: pytest inserts rootdir/conftest paths of its own, loads
plugins, and honours an ini file that can add `pythonpath` or `testpaths`. An `import` performed
by this script would prove a claim about a DIFFERENT process than the one whose greenness is
being trusted. So the proof spawns the repo's real pytest, under the repo's own ini, and asks
the assertion from inside a collected test — the same process shape that produces the green.

The same reasoning is why the child runs under `PYTHONSAFEPATH` (see `_child_env`): matching the
repo's pytest is not enough if the proof's own *entry point* injects a path the real command
would not. A proof whose verdict depends on how the proof was launched is not a proof.

PORTABILITY IS THE POINT (leg (a)). Nothing here is hub-shaped: the package list is read from
the target repo's own `pyproject.toml`, the interpreter is discovered per-checkout, and the
repo may carry no `.worktreeinclude` at all. `ai-council` — the row's named satellite, verified
to have no manifest — is the proving subject, and it is reached by pointing `--repo` at it.

POSTURE — READ-ONLY, AND WIRED INTO NO GATE. Layer 2 (ADR-28/36): it drives no state in a child
repo. It writes exactly one file, into the system temp directory, and removes it; the target
tree is never written to — `-p no:cacheprovider` suppresses `.pytest_cache` and
`PYTHONDONTWRITEBYTECODE` suppresses `__pycache__`, so the no-leftovers round-trip holds even
on the repo being proved. Both were found by the test that asserts it rather than assumed.
Whether it should gate is a separate ruling — the `/preflight` adoption-first precedent.

EXIT CODES — a skip never greens.
  0  PASS            every declared package resolved inside the checkout
  1  FAIL            at least one resolved outside it, or pytest could not run the proof
  2  internal error  the tool could not look (an error BLOCKS; it never reports a silent pass)
  3  NOT-APPLICABLE  the repo declares no importable package AND no pytest ini to root
A distinct code for NOT-APPLICABLE is deliberate. Folding it into 0 would let a repo the tool
cannot actually examine report the same verdict as one it examined and cleared — which is the
failure mode the whole module exists to refuse.

HONEST LIMITS
  * A conforming IMPORT is not a conforming ENVIRONMENT. This proves where the source came
    from, not that the dependency set matches the lock. `uv run --locked` covers that axis.
  * The package list comes from `pyproject.toml`. A repo that ships an importable package
    without declaring it there is invisible to the discovery step — `--packages` is the
    override, and the report always names which packages it actually checked, so a short list
    is readable as a short list rather than as a clean bill of health.
  * A repo with no per-checkout venv is not refused up front. The proof runs against whatever
    interpreter the checkout resolves to and lets the import location decide, because "no venv"
    is a diagnosis, not a verdict: a repo with no importable package is unaffected by it.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

EXIT_PASS = 0
EXIT_FAIL = 1
EXIT_ERROR = 2
EXIT_NOT_APPLICABLE = 3

#: Written into the system temp dir, collected by the target repo's pytest, deleted after.
#: It reports rather than asserts: a failed assertion inside pytest yields a traceback, while
#: the caller needs the resolved paths for BOTH outcomes to write a useful report.
_PROOF_TEST = '''\
"""Generated by scripts/worktree_import_proof.py — deleted when the run ends."""
import importlib
import json
import os
import pathlib


def test_imports_resolve_inside_this_checkout(pytestconfig):
    root = pathlib.Path(os.environ["WT_PROOF_ROOT"]).resolve()
    names = [n for n in os.environ["WT_PROOF_PACKAGES"].split(",") if n]
    resolved = {}
    for name in names:
        try:
            module = importlib.import_module(name)
        except Exception as exc:  # noqa: BLE001 - an unimportable package is a reportable result
            resolved[name] = {"error": f"{type(exc).__name__}: {exc}"}
            continue
        origin = getattr(module, "__file__", None)
        if origin is None:  # namespace package - report its search paths instead
            paths = [str(pathlib.Path(p).resolve()) for p in getattr(module, "__path__", [])]
            resolved[name] = {"namespace_paths": paths}
            continue
        resolved[name] = {"file": str(pathlib.Path(origin).resolve())}
    payload = {
        "root": str(root),
        "rootdir": str(pathlib.Path(str(pytestconfig.rootpath)).resolve()),
        "executable": str(pathlib.Path(os.sys.executable).resolve()),
        "prefix": str(pathlib.Path(os.sys.prefix).resolve()),
        "packages": resolved,
    }
    pathlib.Path(os.environ["WT_PROOF_OUT"]).write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
'''


#: Interpreters tried, in order, when the checkout has no `.venv` of its own. `py` leads on
#: purpose: the Windows launcher lives in `C:\Windows` and starts the SYSTEM interpreter, so it
#: is the one name no venv activation can shadow. That matters because the system interpreter is
#: where a shared editable install actually lives — the ai-council repo-root conftest names it
#: as the cause in as many words ("a bare `python` / `py` resolves `ai_council` to the primary
#: checkout from any cwd"). Resolving to whatever venv the CALLER happened to have active would
#: make the verdict a property of this seat rather than of the target repo.
_FALLBACK_INTERPRETERS = ("py", "python3", "python")


class ProofError(Exception):
    """Raised when the tool cannot look — distinct from looking and finding a bad import."""


@dataclass
class Proof:
    """One checkout, examined."""

    root: Path
    packages: tuple[str, ...]
    interpreter: list[str]
    venv_inside_checkout: bool
    rootdir: Path | None = None
    resolved: dict[str, dict] = field(default_factory=dict)
    outside: list[str] = field(default_factory=list)
    pytest_returncode: int | None = None
    pytest_output: str = ""

    @property
    def passed(self) -> bool:
        return self.pytest_returncode == 0 and not self.outside and bool(self.resolved)


# --- discovery --------------------------------------------------------------------------

def resolve_root(repo: Path) -> Path:
    """The checkout `repo` sits in. Inside a linked worktree this is the WORKTREE root, which
    is the whole point — `--show-toplevel` reports the working tree, not the common git dir."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, encoding="utf-8", timeout=30,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise ProofError(f"cannot run git in {repo}: {exc}") from exc
    if proc.returncode != 0:
        raise ProofError(f"not a git checkout: {repo} ({proc.stderr.strip()})")
    return Path(proc.stdout.strip()).resolve()


def _read_pyproject(root: Path) -> dict:
    path = root / "pyproject.toml"
    if not path.is_file():
        return {}
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ProofError(f"cannot read {path}: {exc}") from exc


def _package_dir_exists(root: Path, name: str) -> bool:
    """True when `name` is on disk here as a real package — under the root or a `src/` layout.
    Discovery is filtered through this so a declared-but-absent name is not reported as a
    package the proof "checked": an import that could never have resolved locally proves
    nothing about which checkout won."""
    top = name.split(".")[0]
    for base in (root, root / "src"):
        candidate = base / top
        if (candidate / "__init__.py").is_file() or (base / f"{top}.py").is_file():
            return True
    return False


def declared_packages(root: Path) -> tuple[str, ...]:
    """Importable package names this repo declares, filtered to those that exist on disk.

    Two sources, in order: the setuptools `include` globs (`ai_council*` -> `ai_council`), then
    the distribution name normalised to an import name (`ai-council` -> `ai_council`). The
    second is the fallback because a repo may configure packaging in a way this does not model;
    the disk filter is what keeps either source from inventing a name.
    """
    data = _read_pyproject(root)
    found: list[str] = []

    includes = (
        data.get("tool", {})
        .get("setuptools", {})
        .get("packages", {})
        .get("find", {})
        .get("include", [])
    )
    for pattern in includes:
        if not isinstance(pattern, str):
            continue
        name = pattern.rstrip("*").rstrip(".")
        if name and _package_dir_exists(root, name) and name not in found:
            found.append(name)

    if not found:
        dist = data.get("project", {}).get("name")
        if isinstance(dist, str):
            name = dist.replace("-", "_")
            if _package_dir_exists(root, name):
                found.append(name)

    return tuple(found)


def _venv_python(root: Path) -> Path | None:
    """The checkout's OWN interpreter, if it has one materialised."""
    for relative in ("Scripts/python.exe", "bin/python"):
        candidate = root / ".venv" / relative
        if candidate.is_file():
            return candidate
    return None


def _caller_free_path() -> str:
    """PATH with the CALLER's own virtualenv removed.

    Load-bearing, and learned by getting it wrong: this tool is normally invoked from the hub
    under `uv run`, so `sys.executable` and `PATH[0]` are the HUB's venv. Handing that to an
    unprovisioned satellite checkout produces a FAIL whose stated cause is
    `ModuleNotFoundError` — technically a failure, but not the one the row is about, and a
    reader would take it as "the package is missing" rather than "the package came from the
    wrong checkout". Stripping the caller's prefix makes the child resolve the interpreter a
    real seat in that repo would resolve: the system one, where the shared editable install
    actually lives. That is the interpreter whose silent wrong-tree import is the whole finding.
    """
    prefix = Path(sys.prefix).resolve()
    kept = []
    for entry in os.environ.get("PATH", "").split(os.pathsep):
        if not entry:
            continue
        try:
            resolved = Path(entry).resolve()
        except (OSError, ValueError):
            kept.append(entry)
            continue
        if resolved == prefix or prefix in resolved.parents:
            continue
        kept.append(entry)
    return os.pathsep.join(kept)


def resolve_interpreter(root: Path) -> tuple[list[str], bool]:
    """Return (argv prefix that runs python for this checkout, is-it-the-checkout's-own).

    A materialised `<root>/.venv` wins outright — it needs no tool on PATH and it is the exact
    thing leg (b) installs. Falling back is deliberate rather than a refusal: an unprovisioned
    checkout is precisely the state the proof should be able to examine and FAIL, and refusing
    to run there would make the failure unwitnessable. The fallback resolves against a
    caller-free PATH so the answer is about the target repo, not about this seat.
    """
    own = _venv_python(root)
    if own is not None:
        return [str(own)], True

    path = _caller_free_path()
    for candidate in _FALLBACK_INTERPRETERS:
        found = shutil.which(candidate, path=path)
        if found:
            return [found], False
    return [sys.executable], False


# --- the proof --------------------------------------------------------------------------

def _pytest_ini_arg(root: Path) -> list[str]:
    """Use the repo's OWN pytest configuration when it has one, so the proof runs under the
    same ini as the green it is vouching for (`testpaths`, `pythonpath`, plugins)."""
    data = _read_pyproject(root)
    if data.get("tool", {}).get("pytest", {}).get("ini_options") is not None:
        return ["-c", str(root / "pyproject.toml")]
    for name in ("pytest.ini", "tox.ini", "setup.cfg"):
        if (root / name).is_file():
            return ["-c", str(root / name)]
    return []


def _child_env(root: Path, packages: tuple[str, ...], out: Path) -> dict[str, str]:
    """The child's environment, with the inherited venv pointers REMOVED.

    `VIRTUAL_ENV` / `PYTHONHOME` / `PYTHONPATH` leak the parent seat's environment into the
    child and are exactly the leak under investigation — a proof that inherited them could
    report the parent's answer while appearing to ask the child. `PYTHONNOUSERSITE` blocks the
    per-user site-packages, another cross-checkout path the interpreter would otherwise honour.
    """
    env = dict(os.environ)
    for leaked in ("VIRTUAL_ENV", "PYTHONHOME", "PYTHONPATH", "PYTHONSTARTUP"):
        env.pop(leaked, None)
    env["PATH"] = _caller_free_path()
    env["PYTHONNOUSERSITE"] = "1"
    # THE FALSE-PASS THIS CLOSES (terra P1, 2026-08-07). `python -m pytest` prepends the CWD to
    # `sys.path`; the command a lane actually runs — `uv run --locked pytest`, i.e. the console
    # script — does not. Without this, a FLAT-LAYOUT package resolves out of the worktree purely
    # because the proof's own entry point put it there, and the proof reports PASS about a
    # package the real command would have taken from the shared install in the primary checkout.
    # It was not hypothetical: in the recorded ai-council FAIL, `config` (flat layout) reported
    # PASS in the very checkout whose `ai_council` (src layout) was demonstrably coming from the
    # primary. `PYTHONSAFEPATH` makes `-m` behave like the console script, so the proof and the
    # command it vouches for resolve imports the same way — which is the whole of its value.
    env["PYTHONSAFEPATH"] = "1"
    # Importing the target's packages compiles them, and the bytecode lands in the TARGET tree
    # as `__pycache__/`. Every fleet repo gitignores it, so it would never have shown up as
    # dirt — which is exactly why it is worth suppressing rather than tolerating: a read-only
    # organ whose only writes are invisible ones is still an organ that writes.
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["WT_PROOF_ROOT"] = str(root)
    env["WT_PROOF_PACKAGES"] = ",".join(packages)
    env["WT_PROOF_OUT"] = str(out)
    return env


def run_proof(root: Path, packages: tuple[str, ...]) -> Proof:
    """Spawn the checkout's pytest on a generated test and read back what it resolved."""
    interpreter, own_venv = resolve_interpreter(root)
    proof = Proof(root=root, packages=packages, interpreter=interpreter,
                  venv_inside_checkout=own_venv)

    with tempfile.TemporaryDirectory(prefix="wt-import-proof-") as tmp:
        tmpdir = Path(tmp)
        test_file = tmpdir / "test_wt_import_proof.py"
        test_file.write_text(_PROOF_TEST, encoding="utf-8", newline="\n")
        out_file = tmpdir / "result.json"

        argv = [
            *interpreter, "-m", "pytest",
            str(test_file),
            "-q",
            "-p", "no:cacheprovider",          # no .pytest_cache left in the target tree
            "-o", "addopts=",                  # drop the repo's own addopts (e.g. `-n auto`)
            "--rootdir", str(root),
            *_pytest_ini_arg(root),
        ]
        try:
            completed = subprocess.run(
                argv, cwd=str(root), capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=600,
                env=_child_env(root, packages, out_file),
            )
        except (OSError, subprocess.SubprocessError) as exc:
            raise ProofError(f"cannot run pytest for {root}: {exc}") from exc

        proof.pytest_returncode = completed.returncode
        proof.pytest_output = (completed.stdout + completed.stderr).strip()

        if out_file.is_file():
            try:
                payload = json.loads(out_file.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                raise ProofError(f"unreadable proof result: {exc}") from exc
            proof.resolved = payload.get("packages", {})
            rootdir = payload.get("rootdir")
            proof.rootdir = Path(rootdir) if rootdir else None

    proof.outside = sorted(
        name for name, info in proof.resolved.items() if not _inside(root, info)
    )
    return proof


def _inside(root: Path, info: dict) -> bool:
    """True when everything this package resolved to lives under `root`. An import ERROR is
    NOT inside: a package that would not load cannot be evidence that the right one did."""
    if "error" in info:
        return False
    if "file" in info:
        return root in Path(info["file"]).parents
    paths = info.get("namespace_paths") or []
    return bool(paths) and all(root in Path(p).parents for p in paths)


# --- reporting --------------------------------------------------------------------------

def render(proof: Proof, applicable: bool) -> str:
    lines = [f"checkout   : {proof.root}"]
    lines.append(f"interpreter: {' '.join(proof.interpreter)}")
    lines.append(
        "venv       : "
        + ("inside the checkout (.venv)" if proof.venv_inside_checkout
           else "NOT inside the checkout - no <root>/.venv; the ambient interpreter was used")
    )
    if proof.rootdir is not None:
        agrees = "matches the checkout" if proof.rootdir == proof.root else "DIFFERS from the checkout"
        lines.append(f"pytest root: {proof.rootdir} ({agrees})")
    if not applicable:
        lines.append("")
        lines.append("NOT-APPLICABLE - this repo declares no importable package in pyproject.toml,")
        lines.append("so there is no import whose checkout could be wrong. Nothing was proved.")
        return "\n".join(lines)

    lines.append("")
    for name in proof.packages:
        info = proof.resolved.get(name)
        if info is None:
            lines.append(f"  ?    {name}: pytest reported nothing for this package")
        elif "error" in info:
            lines.append(f"  FAIL {name}: {info['error']}")
        elif "file" in info:
            mark = "PASS" if _inside(proof.root, info) else "FAIL"
            lines.append(f"  {mark} {name} -> {info['file']}")
        else:
            mark = "PASS" if _inside(proof.root, info) else "FAIL"
            lines.append(f"  {mark} {name} -> namespace {info.get('namespace_paths')}")

    lines.append("")
    if proof.passed:
        lines.append("PASS - this checkout's pytest imports this checkout's source.")
    else:
        lines.append("FAIL - this checkout's pytest does NOT import this checkout's source.")
        lines.append("")
        lines.append("Remedy - give the checkout its own environment, then re-run this proof:")
        lines.append(f"  python scripts/worktree_seed.py --plan {proof.root}")
        if proof.pytest_returncode not in (0, None):
            lines.append("")
            lines.append(f"pytest exited {proof.pytest_returncode}:")
            lines.append(proof.pytest_output[-2000:])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Prove that a checkout's pytest imports THAT checkout's source ([#429]).",
    )
    parser.add_argument("--repo", default=".",
                        help="path inside the checkout to prove (default: cwd)")
    parser.add_argument("--packages", default="",
                        help="comma-separated import names, overriding pyproject discovery")
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = parser.parse_args(argv)

    try:
        root = resolve_root(Path(args.repo))
        if args.packages:
            packages = tuple(n.strip() for n in args.packages.split(",") if n.strip())
        else:
            packages = declared_packages(root)

        if not packages:
            proof = Proof(root=root, packages=(), interpreter=resolve_interpreter(root)[0],
                          venv_inside_checkout=resolve_interpreter(root)[1])
            report = render(proof, applicable=False)
            print(json.dumps({"verdict": "not-applicable", "root": str(root)}, indent=2)
                  if args.json else report)
            return EXIT_NOT_APPLICABLE

        proof = run_proof(root, packages)
    except ProofError as exc:
        print(f"worktree_import_proof: {exc}", file=sys.stderr)
        return EXIT_ERROR

    if args.json:
        print(json.dumps({
            "verdict": "pass" if proof.passed else "fail",
            "root": str(proof.root),
            "rootdir": str(proof.rootdir) if proof.rootdir else None,
            "interpreter": proof.interpreter,
            "venv_inside_checkout": proof.venv_inside_checkout,
            "packages": proof.resolved,
            "outside": proof.outside,
            "pytest_returncode": proof.pytest_returncode,
        }, indent=2))
    else:
        print(render(proof, applicable=True))
    return EXIT_PASS if proof.passed else EXIT_FAIL


if __name__ == "__main__":
    raise SystemExit(main())
