"""`check_organ_truth` -- the index tells the truth, and an organ with no moment is a FAIL.

lane-l3-organ-truth. Thin ADAPTER over two readers that hold the logic:

  * `scripts/graph_queries.py` `organ_moments` -- for every organ in the process roster, is it
    declared at a moment (`ecosystem/harness.yaml`, L1's declaration), declared optional and not
    yet built, or declared NOWHERE?
  * `scripts/generate_organ_index.py` `arming_contradictions` -- does any hook's arming claim in
    the committed `ecosystem/organ-index.md` contradict the live `.pre-commit-config.yaml` /
    `.claude/settings.json`?

THREE FAIL LEGS, each one Finding so the operator reads which leg fired:
  1. an organ declared nowhere;
  2. an organ declared `optional` and not yet built -- ONE FINDING PER ORGAN, naming the lane
     that owes it (a declared-but-required organ whose command is missing FAILs the same way);
  3. an index arming claim that contradicts the live config, or an index that is absent (a
     check that cannot compute its ground truth FAILs, it does not skip -- register ruling Z-G4).

THE TIER, AND THE CONVENTION IT FOLLOWS. `audit.py`'s tier rule puts a FAIL-capable check at
COMMIT ("rule (a)"), and this one is FAIL-capable. It is declared `TIER_SHIP` anyway, as the
FOURTH declared exception -- after `fleet_parity`, `routing_agreement` and `funnel_lifecycle`,
and on exactly the ground the last two record: it measures NON-ZERO on live main today, and what
clears it is an act a committing lane may not perform. The declaration file is L1's alone (the
wave-2 order forbids every lane but L7 one line of it), the unbuilt organs are other lanes' work,
and the stale index is regenerated by the integrator at merge. A COMMIT tier would wedge every
commit in the repository on defects no committer can repair. PROMOTION CONDITION, written down:
flip to `TIER_COMMIT` when this check measures 0 on main.

WHAT IS NOT DONE TO MAKE IT PASS. The roster is not narrowed: every process node counts,
dispositioned orphans included, because a disposition rules on a TRIGGER and this check asks
about a DECLARATION. The verdict is `fail`, never `unavailable` (which `_check_outcome` projects
onto `pass`).

HONEST LIMIT: "declared" means a command in the declaration NAMES the file (or imports it, or a
dotted organ id names its module). A script reached only through another declared script is not
itself declared -- which is the point of asking, and also means a helper module reads as
declared-nowhere until something declares it or it is retired.

Child-repo-safe: no `ecosystem/harness.yaml` -> `n/a` (subject-absent). Read-only (Layer 2).
"""

from __future__ import annotations

from pathlib import Path

from ._common import Finding, _na, _NA_SUBJECT_ABSENT

try:  # top-level name first: the tests patch THIS module object, and a `scripts.`-qualified
    import graph_queries as _gq  # import would hand the check a second copy of it
    import generate_organ_index as _goi
except ImportError:  # pragma: no cover -- a caller that imports `scripts` as a package
    from scripts import generate_organ_index as _goi
    from scripts import graph_queries as _gq

CHECK_NAME = "organ_truth"

#: How many names a rolled-up Finding spells out before pointing at the query that lists all.
_SHOWN = 8


def _fail(evidence: str) -> Finding:
    return Finding(CHECK_NAME, "fail", evidence.replace("|", "/"))


def _rolled(items: list[str], what: str, where: str) -> str:
    shown = ", ".join(items[:_SHOWN])
    more = f" (+{len(items) - _SHOWN} more)" if len(items) > _SHOWN else ""
    return f"{len(items)} {what}: {shown}{more}. Full list: {where}"


def check_organ_truth(repo_path: Path) -> list[Finding]:
    root = Path(repo_path)
    if not (root / _gq.MOMENTS_DECLARATION_REL).is_file():
        return [_na(CHECK_NAME, _NA_SUBJECT_ABSENT,
                    f"no {_gq.MOMENTS_DECLARATION_REL} -- this repo declares no moments")]

    findings: list[Finding] = []
    try:
        rows = _gq.organ_moments(root, roster=_gq.roster_rows(root))
    except Exception as exc:  # noqa: BLE001 -- a check that cannot see its subject FAILs loudly
        return [_fail(f"the organ roster or the moments declaration could not be read, so no "
                      f"organ was checked: {exc!r}")]

    for row in rows:
        if row.status in (_gq.MOMENT_OPTIONAL_UNBUILT, _gq.MOMENT_MISSING):
            findings.append(_fail(_gq.unbuilt_evidence(row)))
    nowhere = [r.path for r in rows if r.status == _gq.MOMENT_NOWHERE]
    if nowhere:
        findings.append(_fail(_rolled(
            nowhere, f"organ(s) declared at no moment and no spine stage in "
                     f"{_gq.MOMENTS_DECLARATION_REL}",
            "`python scripts/graph_queries.py moments`")))

    contradictions = _goi.arming_contradictions(root)
    if contradictions is None:
        findings.append(_fail("ecosystem/organ-index.md is absent, so no arming claim could be "
                              "held against the live config"))
    elif contradictions:
        findings.append(_fail(_rolled(
            contradictions, "index arming claim(s) contradicting the live config",
            "regenerate with `python scripts/generate_organ_index.py --write`, then re-run")))

    if findings:
        return findings
    at_moment = sum(1 for r in rows if r.status == _gq.MOMENT_DECLARED)
    return [Finding(CHECK_NAME, "pass",
                    f"all {at_moment} roster organ(s) are declared at a moment or a spine stage, "
                    f"no declared organ is unbuilt, and every index arming claim matches the "
                    f"live config")]
