"""`check_organ_truth` -- the index tells the truth, and an organ with no moment is a FAIL.

lane-l3-organ-truth. Thin ADAPTER over two readers that hold the logic:

  * `scripts/graph_queries.py` `organ_moments` -- for every organ in the process roster, is it
    declared at a moment (`ecosystem/harness.yaml`, L1's declaration), declared optional and not
    yet built, or declared NOWHERE?
  * `scripts/generate_organ_index.py` `arming_contradictions` -- does any hook's arming claim in
    the committed `ecosystem/organ-index.md` contradict the live `.pre-commit-config.yaml` /
    `.claude/settings.json`?

FAIL AND WARN LEGS, each one Finding so the operator reads which leg fired:
  1. an organ with NO CALLER anywhere AND no recorded fate (R-W3-4: declared at no moment, and
     not called by an armed or dated-manual pre-commit hook, a conductor job, another wiring
     surface, or a `fates:` entry in the declaration) -- all named;
  1a. an organ with no caller whose `fates:` entry (R-W4-1) has a `manual_until` date that has
      PASSED -- dated debt come due is a FAIL, not a warning, so it does not sit forever;
  2. an organ declared `optional` and not yet built -- ONE FINDING PER ORGAN, naming the lane
     that owes it (a declared-but-required organ whose command is missing FAILs the same way);
  3. an index arming claim that contradicts the live config, or an index that is absent (a
     check that cannot compute its ground truth FAILs, it does not skip -- register ruling Z-G4).

TWO WARN LEGS (R-W4-1): an organ with no caller whose fate is a `manual_until` date not yet
reached (the date itself is quoted, so the WARN names when it becomes a FAIL); an organ whose
fate is `retire_candidate: true` (rolled into one list headed for the operator's GO). A fate
whose shape is `moment: <name>` reads as OK -- no Finding at all -- when that moment's own
organs left a receipt in the last 30 days (the organ fires as part of a moment the census's own
reader does not credit it at); with no such receipt it falls back to leg 1, unfated.

FATES ARE A RECORD, NOT A NARROWING (R-W3-4, R-W4-1). `ecosystem/harness.yaml`'s `fates:` block
is the disposition a prior census recorded for the organs it found uncalled -- this check reads
it, it does not write it, and it never treats a fate as excusing the roster: every uncalled
organ is still counted and named in exactly one of the four legs above.

THE TIER, AND THE CONVENTION IT FOLLOWS. `audit.py`'s tier rule puts a FAIL-capable check at
COMMIT ("rule (a)"), and this one is FAIL-capable. It is declared `TIER_SHIP` anyway, as the
FOURTH declared exception -- after `fleet_parity`, `routing_agreement` and `funnel_lifecycle`,
and on exactly the ground the last two record: it measures NON-ZERO on live main today, and what
clears it is an act a committing lane may not perform. The declaration file is L1's alone (the
wave-2 order forbids every lane but L7 one line of it), the unbuilt organs are other lanes' work,
and the stale index is regenerated by the integrator at merge. A COMMIT tier would wedge every
commit in the repository on defects no committer can repair. PROMOTION CONDITION, written down:
flip to `TIER_COMMIT` when this check measures 0 on main.

WHAT IS NOT DONE TO MAKE IT PASS. The roster is not narrowed: every process node counts,
dispositioned orphans included, because a disposition rules on a TRIGGER and this check asks
about a DECLARATION. The verdict is `fail`, never `unavailable` (which `_check_outcome` projects
onto `pass`).

HONEST LIMIT: "declared" means a command in the declaration NAMES the file (or imports it, or a
dotted organ id names its module). A script reached only through another declared script is not
itself declared -- which is the point of asking, and also means a helper module reads as
declared-nowhere until something declares it or it is retired.

Child-repo-safe: no `ecosystem/harness.yaml` -> `n/a` (subject-absent). Read-only (Layer 2).
"""

from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path

import yaml

from ._common import Finding, _na, _NA_SUBJECT_ABSENT

try:  # top-level name first: the tests patch THIS module object, and a `scripts.`-qualified
    import graph_queries as _gq  # import would hand the check a second copy of it
    import generate_organ_index as _goi
except ImportError:  # pragma: no cover -- a caller that imports `scripts` as a package
    from scripts import generate_organ_index as _goi
    from scripts import graph_queries as _gq

CHECK_NAME = "organ_truth"

PRECOMMIT_REL = ".pre-commit-config.yaml"
CONDUCTOR_REL = ".github/workflows/conductor.yml"

#: A script an argv names, and the `python -m scripts.pkg.mod` spelling of one.
_SCRIPT_PATH_RE = re.compile(r"(?:scripts|plugins)/[\w./-]+\.(?:py|ps1)")
_DASH_M_RE = re.compile(r"-m\s+(scripts(?:\.\w+)+)")
#: `SKIP: a,b` -- the hooks a conductor step opts out of.
_HOOK_ID_RE = re.compile(r"[\w.-]+")

#: How many names a rolled-up Finding spells out before pointing at the query that lists all.
_SHOWN = 8


def _fail(evidence: str) -> Finding:
    return Finding(CHECK_NAME, "fail", evidence.replace("|", "/"))


def _warn(evidence: str) -> Finding:
    return Finding(CHECK_NAME, "warn", evidence.replace("|", "/"))


def _rolled(items: list[str], what: str, where: str) -> str:
    shown = ", ".join(items[:_SHOWN])
    more = f" (+{len(items) - _SHOWN} more)" if len(items) > _SHOWN else ""
    return f"{len(items)} {what}: {shown}{more}. Full list: {where}"


def _scripts_named(text: str) -> set[str]:
    """Every `scripts/<x>.py` a command string runs -- by path, or by `-m scripts.x.y`."""
    named = set(_SCRIPT_PATH_RE.findall(text))
    for dotted in _DASH_M_RE.findall(text):
        named.add(dotted.replace(".", "/") + ".py")
    return named


def _precommit_hooks(root: Path) -> list[dict]:
    """Every hook in `.pre-commit-config.yaml`, with the stages it RESOLVES to and the date its
    manual stage lapses -- read from the config, never restated. `[]` when the file is absent."""
    path = root / PRECOMMIT_REL
    try:
        text = path.read_text(encoding="utf-8")
        data = yaml.safe_load(text)
    except (OSError, yaml.YAMLError):
        return []
    if not isinstance(data, dict):
        return []
    dated = _goi._manual_until_by_hook(text)
    defaults = data.get("default_stages") or ["pre-commit"]
    hooks: list[dict] = []
    for repo in data.get("repos") or []:
        for hook in (repo.get("hooks") or []) if isinstance(repo, dict) else []:
            if not isinstance(hook, dict) or not hook.get("id"):
                continue
            hooks.append({"id": str(hook["id"]),
                          "stages": {str(s) for s in (hook.get("stages") or defaults)},
                          "manual_until": dated.get(str(hook["id"])),
                          "scripts": _scripts_named(str(hook.get("entry") or ""))})
    return hooks


def _conductor_steps(root: Path) -> list[tuple[str, str, str]]:
    """`(job, run text, effective SKIP)` for every `run:` step of every job in the conductor workflow.

    `SKIP` resolves the way Actions resolves any env var: workflow, then job, then step, the
    narrower scope overriding the wider one (the whole value, not a merge).
    """
    try:
        data = yaml.safe_load((root / CONDUCTOR_REL).read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return []
    if not isinstance(data, dict):
        return []

    def skip_of(scope: object, inherited: str) -> str:
        env = scope.get("env") if isinstance(scope, dict) else None
        return str(env["SKIP"]) if isinstance(env, dict) and env.get("SKIP") is not None             else inherited

    workflow_skip = skip_of(data, "")
    steps: list[tuple[str, str, str]] = []
    for job, body in (data.get("jobs") or {}).items():
        job_skip = skip_of(body, workflow_skip)
        for step in (body.get("steps") or []) if isinstance(body, dict) else []:
            if isinstance(step, dict) and isinstance(step.get("run"), str):
                steps.append((str(job), step["run"], skip_of(step, job_skip)))
    return steps


def declared_callers(root: Path) -> dict[str, str]:
    """`{script path: who calls it}` from the two surfaces that fire without a human in the loop.

    R-W3-4. Both are read from their OWN config files, so the answer moves when the config does:

      * `.pre-commit-config.yaml` -- a hook that is ARMED (any stage but `manual`) or is manual
        WITH a `manual_until` date. An UNDATED manual hook is not a caller on its own: nothing
        commits to firing it and no date says when it must be re-armed or retired.
      * `.github/workflows/conductor.yml` -- any script a job's `run:` step names, and the hooks a
        step sweeps with `pre-commit run --hook-stage manual` (less that step's `SKIP`). A manual
        hook the conductor actually runs IS called, by the conductor -- not by being called armed.

    HONEST LIMIT: direct callers only. A helper reached only through another script is not named
    here; the census's own `wired_elsewhere` (the graph's transitive reach) supplies that leg.
    """
    hooks = _precommit_hooks(root)
    callers: dict[str, str] = {}
    for hook in hooks:
        if hook["stages"] != {"manual"}:
            why = f"pre-commit hook `{hook['id']}` (armed)"
        elif hook["manual_until"]:
            why = f"pre-commit hook `{hook['id']}` (manual until {hook['manual_until']})"
        else:
            continue
        for script in hook["scripts"]:
            callers.setdefault(script, why)
    for job, run, skip in _conductor_steps(root):
        for script in _scripts_named(run):
            callers.setdefault(script, f"conductor job `{job}`")
        if "--hook-stage manual" not in run:
            continue
        skipped = set(_HOOK_ID_RE.findall(skip))
        for hook in hooks:
            if hook["stages"] == {"manual"} and hook["id"] not in skipped:
                for script in hook["scripts"]:
                    callers.setdefault(script, f"conductor job `{job}` (runs manual hook "
                                               f"`{hook['id']}`)")
    return callers


#: How many days old a moment's own receipt may be and still count as "the moment is firing" for
#: a `moment:` fate (R-W4-1).
_FATE_RECEIPT_WINDOW_DAYS = 30


def _today() -> _dt.date:
    """The date a `manual_until` fate is read against -- one seam, so a test can move it."""
    return _dt.date.today()


def _parse_date(value: object) -> "_dt.date | None":
    """`YYYY-MM-DD` -> a date, or `None` on anything else. `None` reads as a FAIL (dated debt
    with an unparseable date is not honestly WARN-able), never as a silent pass."""
    try:
        return _dt.date.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None


def _load_fates(root: Path) -> dict[str, dict]:
    """`{organ path: fate mapping}` from `ecosystem/harness.yaml`'s `fates:` block (R-W3-4,
    R-W4-1) -- the disposition a prior census recorded for each organ it found with no caller.
    Each entry carries EXACTLY ONE of `manual_until`, `retire_candidate`, `moment` (the shape the
    declaration's own comment names); a malformed entry raises, the same posture as an unreadable
    declaration -- a check that cannot see its own ground truth FAILs, it does not skip it.
    """
    path = root / _gq.MOMENTS_DECLARATION_REL
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{_gq.MOMENTS_DECLARATION_REL} is not a mapping")
    fates: dict[str, dict] = {}
    for entry in raw.get("fates") or []:
        if not isinstance(entry, dict) or not entry.get("path"):
            raise ValueError(
                f"{_gq.MOMENTS_DECLARATION_REL}: a fates entry is not a mapping with a `path`")
        shapes = [k for k in ("manual_until", "retire_candidate", "moment")
                 if entry.get(k) not in (None, False)]
        if len(shapes) != 1:
            raise ValueError(
                f"{_gq.MOMENTS_DECLARATION_REL}: fate for {entry['path']!r} must carry exactly "
                f"one of manual_until, retire_candidate, moment (found {shapes or 'none'})")
        fates[str(entry["path"])] = entry
    return fates


def _moment_ran_recently(root: Path, moment_name: str, today: _dt.date) -> bool:
    """Did ANY organ `harness.yaml` declares at `moment_name` leave a receipt in the last
    `_FATE_RECEIPT_WINDOW_DAYS` days? The evidence a `moment: <name>` fate needs (R-W4-1): the
    organ is not itself declared there (the census's own reader would have found it and this
    fate would not exist), but the moment it claims to ride along with is actually firing.
    """
    try:
        doc = yaml.safe_load((root / _gq.MOMENTS_DECLARATION_REL).read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return False
    moment = next((m for m in (doc or {}).get("moments") or []
                  if isinstance(m, dict) and m.get("name") == moment_name), None)
    if not moment:
        return False
    receipts_dir = root / "logs" / "receipts"
    for organ in moment.get("organs") or []:
        receipt = receipts_dir / str(organ.get("receipt") or "")
        try:
            mtime = _dt.date.fromtimestamp(receipt.stat().st_mtime)
        except OSError:
            continue
        if (today - mtime).days <= _FATE_RECEIPT_WINDOW_DAYS:
            return True
    return False


def check_organ_truth(repo_path: Path) -> list[Finding]:
    root = Path(repo_path)
    if not (root / _gq.MOMENTS_DECLARATION_REL).is_file():
        return [_na(CHECK_NAME, _NA_SUBJECT_ABSENT,
                    f"no {_gq.MOMENTS_DECLARATION_REL} -- this repo declares no moments")]

    findings: list[Finding] = []
    try:
        rows = _gq.organ_moments(root, roster=_gq.roster_rows(root))
        fates = _load_fates(root)
    except Exception as exc:  # noqa: BLE001 -- a check that cannot see its subject FAILs loudly
        return [_fail(f"the organ roster, the moments declaration or its `fates:` block could "
                      f"not be read, so no organ was checked: {exc!r}")]

    for row in rows:
        if row.status in (_gq.MOMENT_OPTIONAL_UNBUILT, _gq.MOMENT_MISSING):
            findings.append(_fail(_gq.unbuilt_evidence(row)))
    # R-W3-4: an organ no MOMENT declares is still an organ someone may call. It fails only when
    # NOTHING calls it -- not a pre-commit hook (armed, or manual and dated), not a conductor
    # job, not any other wiring surface the graph reaches it from. Every roster row still counts.
    callers = declared_callers(root)
    undeclared = [r for r in rows if r.status == _gq.MOMENT_NOWHERE]
    uncalled = [r for r in undeclared if r.path not in callers and not r.wired_elsewhere]

    # R-W4-1: a recorded fate is DATED DEBT, not silence. Split the uncalled roster by what
    # harness.yaml's `fates:` block says about each -- the roster is not narrowed, every row
    # above still lands in exactly one bucket below.
    today = _today()
    unfated: list[str] = []
    past_due: list[str] = []
    dated_debt: list[str] = []
    retiring: list[str] = []
    for row in uncalled:
        fate = fates.get(row.path)
        if fate is None:
            unfated.append(row.path)
        elif fate.get("retire_candidate"):
            retiring.append(row.path)
        elif fate.get("manual_until"):
            until = _parse_date(fate["manual_until"])
            label = f"{row.path} (manual_until {fate['manual_until']})"
            (past_due if until is None or until < today else dated_debt).append(label)
        elif fate.get("moment"):
            if _moment_ran_recently(root, str(fate["moment"]), today):
                continue  # OK: the fate is satisfied, no Finding at all
            unfated.append(f"{row.path} (fate declares moment `{fate['moment']}` but it left no "
                           f"receipt in the last {_FATE_RECEIPT_WINDOW_DAYS} days)")
        else:  # pragma: no cover -- `_load_fates` already refuses any other shape
            unfated.append(row.path)

    # These four ALL-NAME, never `_rolled()`'s truncated preview: the roster is not narrowed even
    # in what the operator is shown (pinned by test_an_organ_with_no_caller_fails_and_is_named,
    # which fixtures more organs than any rolled-up preview would list).
    if unfated:
        findings.append(_fail(
            f"{len(unfated)} organ(s) have no caller anywhere and no recorded fate -- no moment "
            f"or spine stage in {_gq.MOMENTS_DECLARATION_REL}, no armed or dated-manual "
            f"pre-commit hook, no conductor job, no other wiring surface, and no `fates:` entry: "
            f"{', '.join(unfated)}. Give each one a moment, a `manual_until` date, or a "
            f"RETIRE-CANDIDATE fate."))
    if past_due:
        findings.append(_fail(
            f"{len(past_due)} organ(s) carry a `manual_until` fate that has PASSED -- dated debt "
            f"is now due: {', '.join(past_due)}. Arm each one, re-date it with a fresh reason, or "
            f"record a RETIRE-CANDIDATE fate."))
    if dated_debt:
        findings.append(_warn(
            f"{len(dated_debt)} organ(s) carry a `manual_until` fate not yet due: "
            f"{', '.join(dated_debt)}"))
    if retiring:
        findings.append(_warn(
            f"{len(retiring)} organ(s) carry a RETIRE-CANDIDATE fate for the operator's GO: "
            f"{', '.join(retiring)}"))

    contradictions = _goi.arming_contradictions(root)
    if contradictions is None:
        findings.append(_fail("ecosystem/organ-index.md is absent, so no arming claim could be "
                              "held against the live config"))
    elif contradictions:
        findings.append(_fail(_rolled(
            contradictions, "index arming claim(s) contradicting the live config",
            "regenerate with `python scripts/generate_organ_index.py --write`, then re-run")))

    if findings:
        return findings
    at_moment = sum(1 for r in rows if r.status == _gq.MOMENT_DECLARED)
    called = len(undeclared)
    return [Finding(CHECK_NAME, "pass",
                    f"all {len(rows)} roster organ(s) have a caller: {at_moment} are declared at "
                    f"a moment or a spine stage and {called} are called by a hook, the conductor "
                    f"or another wiring surface; no declared organ is unbuilt, and every index "
                    f"arming claim matches the live config")]
