"""`check_handoff_bundle_structure` — extracted from `scripts/audit.py` by [#533].

Moved BYTE-IDENTICAL, together with the three `_BUNDLE_*` constants it exclusively owns.
`_BUNDLE_EXCLUDE_DIRS` stayed behind in `_common` because `check_handoff_probes` — held in
the facade by the `_gitenv` path-load — reads it too. No logic, naming, formatting or
docstring change; `audit.py` re-exports every name.
"""

from __future__ import annotations

import re
from pathlib import Path

from ._common import _BUNDLE_EXCLUDE_DIRS, _na, Finding


# Per-file line budgets for a v4 handoff bundle (HANDOFF_PROCESS §4).
_BUNDLE_BUDGETS = {
    "01_ROLE.md": 100,
    "02_METHODOLOGY.md": 200,
    "03_PROJECT.md": 150,
    "04_RECENT.md": 250,
    "05_NOW.md": 100,
    "06_QUESTIONS.md": 80,
    "07_ASK_BACK.md": 50,
}
# The 8 required files: README + 01–07.
_BUNDLE_REQUIRED_FILES = ["README.md", *_BUNDLE_BUDGETS.keys()]

# A v4 bundle declares its contract via this README stamp (added v4.2 item D).
# The optional `(?:\.\d+)?` matches a patch segment (v4.3.1) without capturing it —
# major.minor still drive the v4.3+ gate. Without it, three-segment stamps (v4.3.1,
# first used 2026-05-31) silently fail to match and the bundle is skipped, not validated.
_BUNDLE_STAMP_RE = re.compile(
    r"Generated by HANDOFF_PROCESS v(\d+)\.(\d+)(?:\.\d+)? \(status: (?:beta|stable)\)"
)


def check_handoff_bundle_structure(repo_path: Path) -> list[Finding]:
    """Historical v4 handoff-bundle structure validator (HANDOFF_PROCESS v4.3 item F).

    Post-#149 flip, v5 is canonical and emits a different artifact (lean residual +
    probe manifest + thin boot — no 8-file bundle), so this check now governs only the
    HISTORICAL v4 bundles. v5-bundle validation is owned by the read-only teeth validator
    (`scripts/verify_handoff_probes.py`, #163 — now live and gating via `check_handoff_probes`
    in ALL_CHECKS); the manual probe-gate (HANDOFF_PROCESS.md §5) remains the rationale-quality
    backstop.

    Scans docs/handoffs/<slug>/ and validates only STAMPED v4 bundles — those whose
    README.md carries the `Generated by HANDOFF_PROCESS v4.x (status: beta|stable)`
    stamp. v5 bundles carry no v4 stamp, so they are skipped here by design. Pre-stamp
    bundles (the v4.1 first-run) and v3.x sync bundles predate the contract and are out
    of scope (preserved historical evidence). The four-tag section is required only for
    v4.3+ bundles.

    Per stamped bundle: 8 files present (README + 01–07); README carries a
    `## Drift cross-check` section; 04_RECENT carries `## Load-bearing facts` (and,
    for v4.3+, `## Four-tag discipline (canonical)`); per-file line budgets respected.
    Excludes aborted/, in-progress/, archive/. Read-only (ADR-28/36).
    """
    handoffs = repo_path / "docs" / "handoffs"
    if not handoffs.exists():
        return [_na("handoff_bundle_structure", "NOT-APPLICABLE",
                        "no docs/handoffs/ — nothing to validate")]

    violations: list[str] = []
    validated = 0
    for d in sorted(handoffs.iterdir()):
        if not d.is_dir() or d.name in _BUNDLE_EXCLUDE_DIRS:
            continue
        readme = d / "README.md"
        if not readme.exists():
            continue  # v3.x sync bundles use 00_README.md — not a v4 bundle
        readme_text = readme.read_text(encoding="utf-8")
        stamp = _BUNDLE_STAMP_RE.search(readme_text)
        if not stamp:
            continue  # pre-stamp / non-v4 bundle — out of scope
        validated += 1
        is_v43_plus = (int(stamp.group(1)), int(stamp.group(2))) >= (4, 3)

        for fname in _BUNDLE_REQUIRED_FILES:
            if not (d / fname).exists():
                violations.append(f"{d.name}: missing {fname}")

        if "## Drift cross-check" not in readme_text:
            violations.append(f"{d.name}/README.md: missing '## Drift cross-check' section")

        recent = d / "04_RECENT.md"
        if recent.exists():
            recent_text = recent.read_text(encoding="utf-8")
            if "## Load-bearing facts" not in recent_text:
                violations.append(f"{d.name}/04_RECENT.md: missing '## Load-bearing facts' section")
            if is_v43_plus and "## Four-tag discipline (canonical)" not in recent_text:
                violations.append(
                    f"{d.name}/04_RECENT.md: missing '## Four-tag discipline (canonical)' "
                    "section (v4.3+ requirement)")

        for fname, budget in _BUNDLE_BUDGETS.items():
            fpath = d / fname
            if not fpath.exists():
                continue
            nlines = len(fpath.read_text(encoding="utf-8").splitlines())
            if nlines > budget:
                violations.append(f"{d.name}/{fname}: {nlines} lines > budget {budget}")

    if violations:
        evidence = (f"{len(violations)} violation(s) across {validated} stamped bundle(s): "
                    + "; ".join(violations[:5]))
        if len(violations) > 5:
            evidence += f" … (+{len(violations) - 5} more)"
        return [Finding("handoff_bundle_structure", "fail", evidence)]
    return [Finding("handoff_bundle_structure", "pass",
                    f"{validated} stamped v4 bundle(s) valid (structure + sections + budgets)")]
